### ISSUE TITLE
Measure bluetooth bandwidth with disabled BLE discovering and disabled WiFi

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1000]

**Comment by evabishchevich** [comment]
I've tested 3 devices with/without BLE/WiFi. The interesting fact that Samsung devices send data to Nexus 6P really slow but Nexus sends data to Samsung with an average speed.
The results:
Without discovery				With discovery			
Wifi off		Wifi on		Wifi off		Wifi on	
	to 6p		to 6p		to 6p		to 6p
First session		First session					
0,024	0,006	0,021	0,007	0,013	0,005	0,013	0,003
0,022	0,009	0,023	0,005	0,013	0,004	0,014	0,003
0,028	0,008	0,015	0,004	0,016	0,005	0,012	0,005
0,02	0,007	0,008	0,009	0,015		0,011	0,004
0,03	0,008	0,008		0,013		0,015	
0,026	0,007	0,017		0,018		0,013	
0,027		0,015		0,017		0,011	
0,019		0,02		0,017		0,01	
0,022		0,02		0,015		0,013	
0,028		0,018		0,015		0,015	
		0,022		0,013		0,013	
		0,016		0,013		0,013	
		0,024		0,014		0,023	
		0,02		0,015		0,021	
		0,022		0,016		0,014	
		0,02		0,016		0,019	
		0,02				0,018	
		0,02				0,014	
							
Average	Average	Average	Average	Average	Average	Average	Average
0,0246	0,0075	0,01828	0,00625	0,01494	0,00467	0,01456	0,00375
							
Second session		Second session		The same session. Nexus had a little bit higher values			
0,042		0,027	0,01	0,017			
0,038		0,031	0,007	0,02			
0,03		0,024	0,006	0,02			
0,029		0,031	0,008	0,017			
0,037		0,024		0,017			
0,036		0,042		0,02			
0,033		0,036		0,02			
0,031		0,037		0,016			
0,042		0,03					
0,034		0,025					
0,032		0,036					
0,034		0,036					
0,043		0,033					
0,04		0,023					
0,045		0,03					
0,032		0,033					
		0,028					
		0,026					
		0,029					
							
Average		Average	Average	Average			
0,03613		0,03058	0,00775	0,018375			
							
Avg 2 sessions		Avg 2 sessions	Avg 2 sessions	Avg with nexus			
0,03037		0,02443	0,007	0,01608

**Comment by larryonoff** [comment]
The main thing that we proved with this issue that Thali works over Bluetooth with 2 devices, i.e. Samsung Galaxy S6 + Nexus 6P,  Samsung Galaxy S7 + Nexus 6P, Samsung Galaxy S6 + Samsung Galaxy S7.
