### ISSUE TITLE
Need a `catch` in `thali/test/www/jxcore/UnitTest_app.js` for the call `ThaliMobile.getNetworkStatus()`

### ISSUE THREAD

**Issue by larryonoff** [thaliproject/Thali_CordovaPlugin#1002]

**Comment by yaronyg** [comment]
The key here is that we need to make sure the tests fail when we get that catch. I think all we have to do is emit "console.log('****TEST_LOGGER:[PROCESS_ON_EXIT_FAILED]****');" and exit.

**Comment by yaronyg** [comment]
Closing as #982 contains the fix for this.
