### ISSUE TITLE
Android doesn't notify our BtLib about scan result from ble scanner

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1005]

**Comment by evabishchevich** [comment]
Probably the root of evil is the same like in thaliproject/Thali_CordovaPlugin_BtLibrary#88 .

**Comment by evabishchevich** [comment]
Found out thaliproject/Thali_CordovaPlugin#1037 while working on this issue

**Comment by yaronyg** [comment]
Blocked on an issue with test server that we should be able to resolve very soon.

**Comment by yaronyg** [comment]
Please confirm if this issue still exists, otherwise please close it.

**Comment by yaronyg** [comment]
@evabishchevich Does this issue still exist?

**Comment by vasilevskayaem** [comment]
can't reproduce

**Comment by evabishchevich** [comment]
@yaronyg @vasilevskayaem See the https://github.com/thaliproject/Thali_CordovaPlugin_BtLibrary/issues/88#issuecomment-261901895
