### ISSUE TITLE
"Coordinated replication action test" in testThaliReplicationPeerActionCoordinated.js does the  work even after it's finished

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1006]

**Comment by andrew-aladev** [comment]
1. Our thali tape should not care about completed tests. We should be properly unbinded from socket after finish.
2. We need fix tests like `testThaliReplicationPeerActionCoordinated` in order to block any activity after teardown.

**Comment by andrew-aladev** [comment]
I am still working on this issue.

We have a problem: socket.io-client >= 1.4.6 just hangs, socket.io-client >= 1.4.0 <= 1.4.5 hangs after random period of time. socket.io-client <= 1.3.7 works fine.
Maybe this is related to jxcore, but I am not sure. I will try to run it with recent node later. For now we can use 1.3.7
