### ISSUE TITLE
Disable tests for iOS that `enable / disable` `WiFi / Bluetooth`

### ISSUE THREAD

**Issue by larryonoff** [thaliproject/Thali_CordovaPlugin#1015]
We need to disable on iOS only! It's important getting tests success at least locally (not CI).

**Comment by larryonoff** [comment]
please keep @dersim-davaod updated about this issue.

**Comment by larryonoff** [comment]
please merge the code into super-branch

**Comment by larryonoff** [comment]
@artemjackson please start working on the issue on Monday ASAP, not @andrew-aladev

**Comment by artemjackson** [comment]
@larryonoff @yaronyg  The issue solution is a `vNext_artemjackson_1015` branch.
Tests (excluding the tests that triggers WiFi) passed successfully on 2 iOS devices locally.

Also we had to disable tests that relate to `PouchDB` because of some issues that should be  solved by #998.

**Comment by artemjackson** [comment]
The `vNext_artemjackson_1015` branch has just updated with #998.
So @dersim-davaod  is going to test it on local devices one more time.

**Comment by yaronyg** [comment]
@artemjackson BTW the tests need to be with at least 3 devices to show we really work.
