### ISSUE TITLE
Get one test to pass in CI

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1017]
Something is wrong with coordination server in CI. To try and figure out what we should get one of the platforms that are working (we'll tell you which one) and then write a single test (disable/delete all the other ones, please do this in a new branch since we will throw this branch away) that just passes and see if we can get that to reliably work in CI.

**Comment by artemjackson** [comment]
@yaronyg There is a PR #1020 that confirms that CI works well.
