### ISSUE TITLE
Create script for setting correct #import statement in JXcoreExtension.m

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#1021]
At this moment in JXcoreExtension.m we have hardcoded import 
`#import "ThaliTest-swift.h"`
It makes impossible to use this library with other projects. Therefore we need to have during install a script that will edit JXcoreExtension.m and will add appropriate import according iOS Product name.

**Comment by yaronyg** [comment]
The plan is to change the installation process a bit to change jxcore extension file with app name.

**Comment by dersim-davaod** [comment]
There is a plugin with which help get app name from cordova.
Will try to use today.
