### ISSUE TITLE
Investigate where we need JXcore for install

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1023]
Now that JXcore isn't officially supported we want to minimize our dependency on it. So we are looking to remove it everywhere from our desktop environment except for running the desktop smoke tests.

**Comment by yaronyg** [comment]
We have PR thaliproject/Thali_CordovaPlugin#1025 for this

**Comment by larryonoff** [comment]
btw, as soon as this issue ready we'll be able using ES6 in the items that wasn't used on devices, i.e. installer, coordination server.

**Comment by yaronyg** [comment]
In fact that is why I've already started to use ES6 features for the validation code.

**Comment by larryonoff** [comment]
This's what I also doing in install environment script.

**Comment by larryonoff** [comment]
Created PR thaliproject/Thali_CordovaPlugin#1092 from `vNext` with the update of the code that isn't in base branch for thaliproject/Thali_CordovaPlugin#1025.
