### ISSUE TITLE
Add validation environment phase into build.sh

### ISSUE THREAD

**Issue by larryonoff** [thaliproject/Thali_CordovaPlugin#1028]
The script should validate which versions of which software we are running. This would include:
1. node 6.3.1
2. npm 3.10.3
2. Homerew
3. wget
4. OpenSSL
2. Jxcore 0.3.1.2
3. Android SDK
1.1. Android SDK Tools 23.1, 22.2, 21.2, 20.2, 19.4, 18.3, 16.5
1.2. Android Support Repository 25
1.3. Android support Library 23.1.1
1.4 Google Repository 24
4. Xcode 7.3.1
5. Version of macOS we are running
6. Python 2.7.10
8. Cordova 6.1.0
9. JDK 1.7.0.79
7. Github
5. etc. ?

We should be able to run the script on our own machines to make sure we are configured correctly and this script should run at the start of each build and cause the build to fail if it doesn't validate. That way any changes to CI will require a PR and thus be visible.

Our goals are:
1. To have a script that setups up the CI environment from scratch so CI is reproducible
2. To have a script that is run before every build that confirms the local environment is setup as expected

**Comment by larryonoff** [comment]
Started implementation in branch `vNext_ilya_1028`.

**Comment by yaronyg** [comment]
See if we can install brew, Xcode, Android-SDK, etc. cleanly in a new VM just to set up the CI environment programmatically. Also make sure at run time we validate the versions of our dependent software and delete the .jx and .node-gyp directories before a build.

**Comment by yaronyg** [comment]
http://riccardotramma.com/2016/05/install-os-x-on-virtualbox-on-os-x/ - This had all the instructions I needed to successfully set up El Capitain as a VirtualBox VM

**Comment by larryonoff** [comment]
I didn't find any ways to install Xcode and Xcode Command Line Tools via command line. There're should be some user actions in UI. Probably there're some options, but not the easy one. We don't have time for it. So we have to bundle Xcode and Xcode Command Line Tools. And I think that it's fine.

**Comment by yaronyg** [comment]
@larryonoff I hope what you mean by 'bundle' is that we will check if they are there and if not we will throw an error but we won't provide a way to automatically install them.

**Comment by yaronyg** [comment]
To Do:
- [ ] Break the validate file into two pieces. One that exports the validation config object and the validation function
- [ ] A second file that calls the first file and exits from the process badly if something goes wrong, this is what we will use in setupDesktop and setupTests. But we need the other file so @larryonoff's install functions can read our config without triggering a validation run

**Comment by larryonoff** [comment]
@yaronyg 

> I hope what you mean by 'bundle' is that we will check if they are there and if not we will throw an error but we won't provide a way to automatically install them.

Exactly. We put some stuff in the image and check if it has proper versions. If not -> error.

**Comment by larryonoff** [comment]
@yaronyg why we need `wget` ?

**Comment by yaronyg** [comment]
Per our conversation today on stand up, we use it in CI and we are both too lazy to get rid of it. :)

**Comment by yaronyg** [comment]
- [ ] Android isn't building so clearly I'm not setting up the paths correctly for Brew installed Android, need to fix this
- [ ] Need to add a check that the number of items in commandsAndResults is the same as
versions so we don't accidentally forget something

**Comment by yaronyg** [comment]
@larryonoff please see the two previous work items. I had two calls today and didn't have time to finish everything up. But please check out the new versions variable. It should make the job of finding the right version for each thing much easier.

**Comment by larryonoff** [comment]
btw. why node version not `6.5.0` (if it's stable) or `6.4.*`.

**Comment by larryonoff** [comment]
We also need to add `swiftlint` tool, because it's needed to validate iOS during pre-build phase.

**Comment by yaronyg** [comment]
Node - So I had to go to 6x because 4x doesn't work with PouchDB's build environment for some strange reason (apparently the PouchDB folks mostly run 5x). So if we are on 6x we might as well go with 6.6.0.

ANDROID_HOME - Agreed, I'll fix

git - No, we should check versions. Things can and do break and act differently.

swiftlint - I'll add it

**Comment by larryonoff** [comment]
> Node - So I had to go to 6x because 4x doesn't work with PouchDB's build environment for some strange reason (apparently the PouchDB folks mostly run 5x). So if we are on 6x we might as well go with 6.6.0.

yes-yes. I meant node6, but 6.6.0, not 6.3.1.

> git - No, we should check versions. Things can and do break and act differently.

What about using version range, but not specific version. Because I on my machine for example I use the latest one, when Xcode Console Tools has bundled not the latest one.

**Comment by yaronyg** [comment]
The simpler the logic the less likely we are to blow everything to little pieces. BTW, how would the Xcode console tools show up anyway during the validation? We are just going to validate whatever is in the environment which should be what you have installed, right?

**Comment by larryonoff** [comment]
I asked Google how to validate that Xcode command lite tools installed, so there's a discussing on http://stackoverflow.com/questions/15371925/how-to-check-if-command-line-tools-is-installed. As I understand there isn't a strict way to do it. So I think we can stick with the steps below for now.
1. `xcode-select -p` to verify that Xcode installed
2. `xcodebuild -version` to verify that command lite tools. I'm not sure that this valid approach, but I believe it should work.
