### ISSUE TITLE
Fix the `vNext_yarong_417_812` branch to pass in CI.

### ISSUE THREAD

**Issue by artemjackson** [thaliproject/Thali_CordovaPlugin#1031]
The branch `vNext_yarong_417_812` should be a start point for any other new branches.
But now it fails in CI. So the branch must be fixed and pass CI.

**Comment by artemjackson** [comment]
All test pass locally on mocked `Mobile`, but on CI with real `Mobile` some of tests failed.

The 'superbranch' brought new test files:
`testLocalSeqManager.js`
`testLocalSeqManagerCoordinated.js`
`testNativeMethod.js`
`testPouchDBGenerator.js`
`testThaliManager.js`
`testThaliManagerCoordinated.js`
`testThaliPullReplicationFromNotification.js`
`testThaliPullReplicationFromNotificationCoordinated.js`
`testThaliReplicationPeerAction.js`
`testThaliReplicationPeerActionCoordinated.js`
and big changes were made in
`testThaliPeerPoolInterface.js`
`testthaliPeerPoolDefault.js`

So I'm going to exclude some of 'bad' new files to see how will CI work.

**Comment by artemjackson** [comment]
Well, the `testLocalSeqManager.js` is broken for sure. It works on the `Mobile` mock but does not on a real `Mobile`.
Proofs:
Seach for the `doImmediateSeqUpdate - create new seq doc` in the CI [log].(https://github.com/ThaliTester/TestResults/blob/846186378976bee_Returned_setImmediate_workaround_artemjackson/thali01_motorola-Nexus%206.md)

See #1029.

**Comment by artemjackson** [comment]
Well, we can say for sure that
`testLocalSeqManager.js`
`testLocalSeqManagerCoordinated.js`
`testThaliManager.js`
`testThaliManagerCoordinated.js`
`testThaliPullReplicationFromNotificationCoordinated.js`
are broken.

See #1029 for more details.

**Comment by artemjackson** [comment]
It's horrible... The [log](https://github.com/ThaliTester/TestResults/blob/846186378976bee_Returned_setImmediate_workaround_artemjackson/test_log.md) shows that there is an issue with tests.
So I installed Android Studio to run test locally on Android devices because it takes an eternity to build and run tests on CI.

And I got unpredictable result: tests passed. 

I can't say that CI has 'bad' devices, because these test fail on iOS devices locally.
Probably we need to disable the 'bad' test and get CI working and then fix tests one-by-one.

**Comment by artemjackson** [comment]
Oh, cool
The second tests run failed. Wunderful, at least we know that something is broken.
I got an error
```
09-14 10:43:52.449 30276-30328/com.test.thalitest I/jxcore-log: # 133. Make sure docs replicate
09-14 10:43:54.538 30276-30328/com.test.thalitest I/jxcore-log: DEBUG thaliReplicationPeerAction: Replication resumed
09-14 10:43:55.089 30276-30328/com.test.thalitest I/jxcore-log: DEBUG localSeqManager: Got an error trying to update seq {"onPut":true}
09-14 10:43:55.090 30276-30328/com.test.thalitest I/jxcore-log: DEBUG thaliReplicationPeerAction: Got error in update, waiting for main loop to detect and handle -   Stop Called
09-14 10:43:57.254 30276-30328/com.test.thalitest I/jxcore-log: not ok 528 failed with Error: response code was 404
09-14 10:43:57.254 30276-30328/com.test.thalitest I/jxcore-log:   ---
09-14 10:43:57.254 30276-30328/com.test.thalitest I/jxcore-log:     operator: fail
09-14 10:43:57.254 30276-30328/com.test.thalitest I/jxcore-log:   ...
09-14 10:43:57.288 30276-30328/com.test.thalitest I/jxcore-log: # teardown
```
So my offer about disabling some 'bad' test is still stands.

**Comment by yaronyg** [comment]
We agreed that what we will do is:
1. Disable all problematic tests for now
2. Submit a PR to vNext_yarong_417_812 that passed in CI
3. Then submit a PR from vNext_yarong_417_812 to vNext and get passing in CI
4. Then go back and fix each test one by one in vNext
5. Once all tests are passing on WiFi then we will go to master from vNext

**Comment by yaronyg** [comment]
We'll revisit this when we have Android WiFi only mode in some kind of decent shape.
