### ISSUE TITLE
Provide a new server and thali tape to new super branch.

### ISSUE THREAD

**Issue by andrew-aladev** [thaliproject/Thali_CordovaPlugin#1034]

**Comment by yaronyg** [comment]
#1007 is for @artemjackson but we'll then create a new PR with the old one to super branch for formal review. Should be ready today.

**Comment by andrew-aladev** [comment]
Artem provided me with comments about 1-st pull request. I am fixing it.

**Comment by yaronyg** [comment]
PR should reach me today.
