### ISSUE TITLE
`testLocalSeqManager` fails on some devices

### ISSUE THREAD

**Issue by artemjackson** [thaliproject/Thali_CordovaPlugin#1035]
This issue comes from #1031.

There are 7 Android device in CI. When running coordination tests 4 of them crashes on `_doImmediateSeqUpdate - create new seq doc` test. There is the same crash on local tests run with 3 iOS devices. So probably something wrong with `testLocalSeqManager.js` or  `localSeqManager.js` implementation or even native layer.

We need to investigate and fix it

See the [log](https://github.com/ThaliTester/TestResults/blob/846186378976bee_Returned_setImmediate_workaround_artemjackson/test_log.md) for more details.

**Comment by yaronyg** [comment]
This is now thaliproject/Thali_CordovaPlugin#1091
