### ISSUE TITLE
Run tests on Andrew's new test server

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1036]

**Comment by evabishchevich** [comment]
There is the issues that devices don't connect to TestServer. I hope we'll fix it today and tomorrow I'll continue working on thaliproject/Thali_CordovaPlugin#1037  and thaliproject/Thali_CordovaPlugin#1022

**Comment by yaronyg** [comment]
This should be fixed today after the call.

**Comment by evabishchevich** [comment]
There is a problem that files in the same directory can't see each other. we get 

``` ERROR thaliTape: uncaught exception, error: 'Error: Cannot find module './CoordinatedClient'', stack: 'Error: Cannot find module './CoordinatedClient'
                                                                    at $w._oldRes@module.js:802:9
                                                                    at $w._resolveFilename@module.js:1771:1
                                                                    at @/data/data/com.test.thalitest/files/www/jxcore/lib/CoordinatedTape.js:14:1
                                                                    at $w.prototype._compile@module.js:621:8
                                                                    at $w._extensions[".js"]@module.js:651:1
                                                                    at $w.prototype.load@module.js:442:1'
```
while running the app. 
These files presented into a builded apk but on device files/www/jxcore folder is epmty. This folder was empty in previous versions also so it's default behaviour. 

I'm going to investigate what cordova makes with assets during building process.

**Comment by yaronyg** [comment]
This is blocked on the require issue, thaliproject/Thali_CordovaPlugin#1039
