### ISSUE TITLE
Fix tests in thaliMobileNative

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1037]
There are 4 tests in thaliMobileNative that starts with '#startUpdateAdvertisingAndListening'. There is the following situation:
1. 1st peer connects to 2nd peer
2. They successfully communicate.
3. 1st peer goes to teardown.
4. 3rd peer tries to connect to 1st peer and has no success.

There are 2 main problems: 
1. Problem with teardown which should be already fixed in Andrew's new test server.
2. It's enough for success to communicate only with one peer.

**Comment by yaronyg** [comment]
#1 as mentioned is fixed and #2 is not a bug, that was an intentional part of the test design. We don't always need to test with all peers.
