### ISSUE TITLE
Test for endless loops

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#105]
The endless loop we ran into in the iOS code would have been detected if we had a test where we connect to a peer, send data back and forth, disconnect and then try to connect again to the exact same peer. So we need to add that to the node.js level tests to prevent regressions.

**Comment by yaronyg** [comment]
This should get into story 0.0

**Comment by tobybrad** [comment]
Need a bit more detail please.

**Comment by yaronyg** [comment]
This was a test that we had agreed on adding way back when due to an early iOS bug. 

The test was:
Step 1 - Connect to peer X
Step 2 - Transfer some data
Step 3 - Disconnect from peer X
Step 4 - Re-connect to peer X (and no other peer)
Step 5 - Send some data

We had a test that just did steps 1-3 and so we thought everything was fine. But then it turned out that if we had instead run steps 1-5 we would have found that bug. Since this pattern should be very common amongst our users this seemed like a good thing to test for.

**Comment by tobybrad** [comment]
So.. test I added in cle_fixes  to ThaliNativeLayer basically covers this scenario. I think we're good.
