### ISSUE TITLE
Can we run wifi only tests on iOS on the simulator?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1050]

**Comment by dersim-davaod** [comment]
First of all, yes, we can run multiple simulators together.
To do this we need to add some minor changes to the project.

Also I found out that we have to change the code used by updateNetworkStatus function (I've created [a new issue](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1056)).

And now I'm going to build and run wifi only tests on multiple simulators.

**Comment by dersim-davaod** [comment]
So I tried to run coordinated tests on simulator. Looks like everything works.

To run WiFi only tests on the simulator please go through following steps:
1. First of all we have to install Thali app on simulators. If you want to run tests on 2 simulators, you must preload app into all simulators (for example iPhone 5s and iPhone 6).
2. Then we have to start all simulators on macOS.
    * In Terminal run `cd /Applications/Xcode.app/Contents/Developer/Applications`
    * Then run `open -n Simulator.app`
    * Wait until simulator loads and starts.
    * Run `open -n Simulator.app` one more time to run another instance of simulator app
    * You'll get a warning message with text `Unable to boot device in current state: Booted`. Just click `OK`, then goto Hardware -> Device and select device on which you installed Thali app earlier
    * If you need more simulators just repeat 2 previous steps
3. Run Thali application on each simulator you opened.
4. Run coordinated tests like `jx ./index.js "{\"devices\":{\"android\":0,\"ios\":2}}"`

**Comment by yaronyg** [comment]
The answer is yes! We can!
