### ISSUE TITLE
We should be able to accept the 'CI' test switch and use it to make all tests pass

### ISSUE THREAD

**Issue by larryonoff** [thaliproject/Thali_CordovaPlugin#1055]
The work item is that we want to run a CI smoke test that just tells us that CI can build, deploy and 'hello world' the devices so we know that CI is functional. After discussing this we agreed that the simplest way to do this is to set up the CI infrastructure that @mlesnic is putting together in thaliproject/CI#74 and when the switch is being used have the install script for iOS replace the contents of all the test files with NOOP. We should maintain exactly one file with an actual test in it. The rest should just return. Again the point is just to show that CI works.

**Comment by larryonoff** [comment]
We can just replace contents with empty contents of files with test that we don't need. @mlesnic could you please try it.

**Comment by yaronyg** [comment]
Just replacing the file contents will take 3 days? But one way or another we HAVE to do this. We have way too many problems with CI and we need a known good solid test we can run and be sure it will tell us if CI is happy or not. Otherwise everyone is just going to blame CI for everything.

**Comment by larryonoff** [comment]
'3 days' were before we decided to replace contents of files. This estimation was for list of tests in JSON.
