### ISSUE TITLE
updateNetworkStatus function can't be run on iOS simulator

### ISSUE THREAD

**Issue by dersim-davaod** [thaliproject/Thali_CordovaPlugin#1056]
At the moment our implementation of NetworkReachability uses hardware-specific details.
Also we can not use Bluetooth on simulator via CoreBluetooth/BluetoothManager framework.
So we need to handle this situation when application is running on simulator.

**Comment by dersim-davaod** [comment]
Fix is implemented in private branch.

**Comment by yaronyg** [comment]
@dersim-davaod Any reason not to check this in? It will help the node folks when they need to investigate a failing node test on iOS since they don't have iOS devices.

**Comment by dersim-davaod** [comment]
The main reason why I didn't do that is lack of time due to #881 and #1029.
I will do this within one day.
