### ISSUE TITLE
Create setupThaliTestIds.js and configure setUpTests.sh to call it

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1070]
See thaliproject/Thali_CordovaPlugin#1066 for context

Please create setupThaliTestIds.js in thali/install and have it go over to ThaliTest (fail out with process.exit(-1) if you can't find ThaliTest as a sibling to the current directory) and:

 * Edit thaliConfig.json using a regex to replace existing SSDP_NT value with a randomly generated string (use npm randomstring) of the same size. This is fine because this edited file is in ThaliTest and not the repo clone.
 * Edit ConnectionHelper.java (also with a regex) to replace service ID with a newly generated GUID and the manufactuer ID with a random number between 1100 and 65534.
 * Edit JXcoreExtension.m (make sure we do this AFTER the point where setUpTests replaces the default version of JXcoreExtension.m) to replace the serviceType with a same sized random string.

Remember, all the previous is happening inside of ThaliTest, not the clone of the repo.

Now please go to setUpTests.sh and add a call to 'node setupThaliTestIds.js' at the end of the Install_Thali function.

**Comment by andrew-aladev** [comment]
I am working on this issue. I will finish it today. I've received all required information from ios and android land.

**Comment by yaronyg** [comment]
Please target this at vNext and if possible where there are install infrastructure changes between vNext and vNext_yarong_417_812 please migrate those install changes from vNext_yarong_417_812 back to vNext.

**Comment by andrew-aladev** [comment]
We should use ponyfills instead of polyfiils.
