### ISSUE TITLE
Please change tests to use random SSDP_NT when we are running on desktop

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1072]
Please see thaliproject/Thali_CordovaPlugin#1066 for context

### Requirements:

When we run 'jx npm test' or 'jx npm run test-meta' we have to make sure that we use a randomly generated SSDP_NT value that will override the value from thaliConfig.js. We want to make sure however that the randomly generated value isn't put into thaliConfig.js since the test is run in our repo clone and we could accidentally check it in!

When we run 'jx npm run test-coordinated' on desktop (meaning inside of the repo clone) we need the node processes spawned by runCoordinatedTests.js to all have the same randomly generated SSDP_NT value or they won't find each other. To make things more complex if we are running both iOS and Android tests (e.g. when @artemjackson fixes thaliproject/Thali_CordovaPlugin#902) simultaneously then all the node processes using the iOS mock layer have to have the same randomly generated SSDP_NT value and all the node processes using the Android mock layer have to also all have the same SSDP_NT value but a different one than the iOS processes so the tests don't interact.

### Ways to meet the requirements:

For 'jx npm test' and 'jx npm run test-meta' I suspect the original instructions in this bug probably made the most sense, that is, edit runTests.js to:
* Check to see if we are running under the Thali_CordovaPlugin directory, if so then require thaliConfig.js, replace the value of SSDP_NT in memory with a new randomly generated string (use npm randomstring) of the same size as the current string.
* If we aren't under Thali_CordovaPlugin then loadFile should just require(filePath) and be done. But if we are under Thali_CordovaPlugin then use proxyquire with @global in the form proxyquire(filePath, { 'thaliConfig': { thaliConfig, '@global': true }}) so that we will replace thaliConfig in all files all the way down the line with our updated one.

But this won't work for 'jx npm run test-coordinated' because it would result in all the spawned Node processes having different SSDP_NT values and so not finding each other. I can see two ways to fix this:

* Pass an argument to UnitTest_app.js - We could have runCoordinatedTests, when it calls spawn in spawnTestInstance pass in an argument with the SSDP_NT value that the spawned instance is to use. This would be passed to UnitTest_app.js who would then have to pass it to runTests.js who would then use it. We could then have @artemjackson fix thaliproject/Thali_CordovaPlugin#902 by teaching runCoordinatedTests how to pass one SSDP_NT value to Android mock images and a different one to the iOS mock images.
* Introduce a thaliConfigOveride.json file - This would be a file that we would put into .gitignore. The file would have to have two sections in its json value, iOS and Android. We would then put in the SSDP_NT values for iOS and a different for Android in the appropriate sections and we would then test runTests.js to read in the file and use it to override thaliConfig.js based on what platform it is. If we go this route then we should obviously make 'jx npm test' and 'jx npm run test-meta' work the same way. Which is the main advantage of this approach. We have one file that won't ever be checked in that handles everything.

### Which do you prefer?

Personally I like passing the argument. It just seems simpler and it doesn't create any artifacts we could ever check in. But that's just my two cents. Pick which ever one you want and please implement! Or do you have a third option?

**Comment by andrew-aladev** [comment]
I am working on this issue now.

**Comment by andrew-aladev** [comment]
We can modify `thaliConfig` to use `process.env.SSDP_NT || defaultValue`. Our `runTests.js` will create random `SSDP_NT` if `process.env.SSDP_NT` is undefined. Our `runCoordinatedTests` can provide a fixed `SSDP_NT` for spawn process.

**Comment by andrew-aladev** [comment]
After this task we need to update `SSDP_NT` [replacer](https://github.com/thaliproject/Thali_CordovaPlugin/pull/1115) a bit. It should replace only `defaultValue`.

**Comment by yaronyg** [comment]
Works for me! Environment variables it is.

**Comment by andrew-aladev** [comment]
I am still working on this issue and merging pull requests.
