### ISSUE TITLE
Update to latest JXCore Cordova Plugin

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#108]
We have a new release - https://github.com/jxcore/jxcore-cordova-release and we need to update to it.

**Comment by yaronyg** [comment]
@tobybrad do we want to do this now or wait until after 0.0.1? I'm tempting to wait but if we run into any issues then JXcore can't help us until we upgrade to the latests and greatest. Thoughts?

**Comment by obastemur** [comment]
Upgrade doesn't require any update on source code level.

**Comment by tobybrad** [comment]
@yaronyg Do it for 0.0.1. This fixes a leak iirc. Not a major change, but a useful one.

**Comment by yaronyg** [comment]
It shall be done.

**Comment by obastemur** [comment]
BTW; although 0.0.5 is not stable yet, better target that version for configuration free ios9 compatibility + fix for some Samsung devices.

**Comment by obastemur** [comment]
By saying `not stable`, There are some core changes but no significant issue is expected.

**Comment by yaronyg** [comment]
We need to do it again for Cordova 0.0.7 - the main feature is that you can now turn off WiFi on Android from Node.js

**Comment by yaronyg** [comment]
I believe @tobybrad is already working on this.

**Comment by tobybrad** [comment]
https://github.com/thaliproject/Thali_CordovaPlugin/blob/cle_fixes/thali/install/install.js#L274
