### ISSUE TITLE
"test repeat write 1" wifi only mode test fails on iOS, but works on Android.

### ISSUE THREAD

**Issue by dersim-davaod** [thaliproject/Thali_CordovaPlugin#1082]
You can find more information about wifi only mode testing on iOS [here](https://zube.io/projects/3188/cards/176636606)

**Comment by yaronyg** [comment]
Once thaliproject/Thali_CordovaPlugin#1064 is checked into vNext_yarong_417_812 then please re-run this test and confirm it still fails on iOS in wifi only mode. Then please assign this bug to @enricogior.

**Comment by larryonoff** [comment]
It's the highest priority now.

**Comment by dersim-davaod** [comment]
Test still fails with fixed socket hangup error from #1138, but as Andrew said we have another issue (see #1138 for more details).

**Comment by yaronyg** [comment]
This is now thaliproject/Thali_CordovaPlugin#1151
