### ISSUE TITLE
Application doesn't start after build on iPhones 6 in CI

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#1087]
According thaliproject/CI#74 , creating CI smoke tests, I wrote a script that runs only one simple node test, one android and one (or two) tests on iOS. On iOS, the script erases the content of test files that are other than 'SimpleTestCase'. But, when I ran it in CI, I get a log saying that application could not be launched. As I am unable currently to deploy to iOS devices locally, could you please try to reproduce or just build and deploy from my branch vNext_mlesnic_CI_74_1 locally? That would tell us if it is CI fault or it is related to something else. You can look for test logs in PR thaliproject/Thali_CordovaPlugin#1030

**Comment by yaronyg** [comment]
@larryonoff this is really important so if you can just quickly test it that would be great.

**Comment by mlesnic** [comment]
It looks like this was only one time, I ran this tests twice later and it passed.
