### ISSUE TITLE
Merge the android work into vNext_yarong_417_812

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1089]
No more split branches. It's time to collect the work you have done and move it to vNext_yarong_417_812. Once we have your code and Andrew's test server checked in we will then do a merge with vNext.

**Comment by yaronyg** [comment]
@evabishchevich I assume this is blocked on thaliproject/Thali_CordovaPlugin#1039?

**Comment by yaronyg** [comment]
This is wifi only.

**Comment by evabishchevich** [comment]
PR thaliproject/Thali_CordovaPlugin#1183
