### ISSUE TITLE
Completion callback called twice in SocketRelay.swift

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1090]
In SocketRelay.swift in the function createSocket we can call completion twice. Once after the self?.handleDidReceive and again inside of addToDiscardQueue. That would result in two call backs to node which isn't right. We need to fix this.

**Comment by yaronyg** [comment]
Finished implementation and working on unit tests.

**Comment by baydet** [comment]
got blocket with thaliproject/Thali_CordovaPlugin#1052 - interface of SocketRelay will be changed. Therefore fixing this issue now will have no sense in future.
