### ISSUE TITLE
Random "Error: socket hang up -1" failure in coordinated tests on desktop

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1114]
Excerpt from a [build log](https://github.com/ThaliTester/TestResults/tree/861478344380252__898_Updates_to_thaliWifiInfrastructure_chapko/)
```
2016-09-21 16:52:48 - ERROR TestsProcess: 'uncaught promise rejection, error: 'Error: socket hang up -1', stack: 'Error: socket hang up -1
    at createHangUpError (http.js:1101:15)
    at CleartextStream.socketCloseListener (http.js:1150:23)
    at CleartextStream.emit (events.js:98:20)
    at tls.js:644:10
    at process._tickCallback (node.js:917:13)''
```

**Comment by yaronyg** [comment]
@chapko have you updated to the very latest vNext_yarong_417_812 with @andrew-aladev's new test server? I'm guessing not because that stack looks awful small.

**Comment by chapko** [comment]
@yaronyg you are right, I got this error twice - once locally and once on CI, and both times it was with an old test server. This bug might be fixed by Andrew's update, but there is a [bug](https://github.com/ThaliTester/TestResults/blob/861478345ecb88c__898_Updates_to_thaliWifiInfrastructure_chapko/test_log.md) in a new test server and I can't use it right now. As far as I know @andrew-aladev is aware about this bug.

**Comment by yaronyg** [comment]
@chapko Do you know if @andrew-aladev has file an issue for that bug? If not can you please ask him to.

**Comment by andrew-aladev** [comment]
Yes, [issue](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1078).

In order to fix this issue we can copy `bv_tests` into `fit_tests` and try to remove tests from `fit_tests` one by one.

**Comment by chapko** [comment]
Closing in favor of #1138
