### ISSUE TITLE
Please remove prototyping on system objects, it isn't safe in ARM

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1123]
This is for the polyfills. We'll need to switch to using dedicated functions instead of polyfills. Yes, this sucks.

The background is that we have found that JXcore on ARM gets into a weird state if you modify the prototype of an array object. We are still investigating but for now we need to make forward progress so we will have to avoid doing this ourselves.

**Comment by andrew-aladev** [comment]
Artem said that there is a special name for such functions: ponyfills. We can include ponyfills like [array-from](https://www.npmjs.com/package/array-from)

**Comment by andrew-aladev** [comment]
I've broken CI by using 'js-polyfills' by the way. We have a [log](https://github.com/ThaliTester/TestResults/blob/86214450fcb5eda_Replacer_for_hardcoded_ids_andrew-aladev/build.md).

**Comment by yaronyg** [comment]
@enricogior it makes sense that js-polyfills (a project from NPM) would break us since it takes polyfilling to a whole new level. But the fact that it broke on the desktop is awesome because this means you can now easily investigate what the heck is going on.

**Comment by yaronyg** [comment]
Oh and @andrew-aladev just to be clear, we should still go to ponyfill. We will hopefully get this fixed at some point but not today so ponyfill it is.
