### ISSUE TITLE
Not a supported operation on multiconnect for android needs to return on the multiconnect method

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1130]
I forgot if I ever sent you a note that we change the definition of multiconnect just a tiny bit so that now if someone calls multiConnect on Android they will get an immediate unsupported error instead of having to wait for the async callback. This should make your life much easier. Please refer to the spec for the actual strings to use.

**Comment by evabishchevich** [comment]
Do you mean multiConnectResolved under callback?
