### ISSUE TITLE
Please don't fire a network changed event when startBroadcasting is called

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#114]
Right now the iOS code fires off a network changed event when stopBroadcasting is called. That isn't the intended semantics.

**Comment by tobybrad** [comment]
no it doesn't. Did you mean startBroadcasting ?

**Comment by yaronyg** [comment]
Yup. My bad for assuming I knew what the problem was rather than actually checking.
