### ISSUE TITLE
Test WifiOnly test from superbranch on 3 Android devices

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1143]

**Comment by evabishchevich** [comment]
'Make sure docs replicate' failed 2 times
https://gist.github.com/evabishchevich/878e2a23950a22791639f44c0e9945a1
'Action fails because of a bad hostname.' failed 1 time
https://gist.github.com/evabishchevich/9cff989bf1a69284ea8167901808604e

**Comment by yaronyg** [comment]
@evabishchevich Please disable both tests and file bugs for both for us to investigate.

**Comment by evabishchevich** [comment]
'Action fails because of a bad hostname.' failed 2/5 today.

**Comment by evabishchevich** [comment]
Created thaliproject/Thali_CordovaPlugin#1152 and thaliproject/Thali_CordovaPlugin#1153

**Comment by evabishchevich** [comment]
Created thaliproject/Thali_CordovaPlugin#1161
