### ISSUE TITLE
Test WifiOnly test from superbranch (vNext_yarong_417_812) on 3 iOS devices

### ISSUE THREAD

**Issue by dersim-davaod** [thaliproject/Thali_CordovaPlugin#1151]

**Comment by dersim-davaod** [comment]
For unknown reasons devices can't connect to server.
We enabled logs on devices (it was disabled after merges in `vNext_yarong_417_812`) so now we can see logs and we're going to investigate this issue.

**Comment by dersim-davaod** [comment]
#1158 issue was created.
Now Artem is trying to update the code to run tests.

**Comment by dersim-davaod** [comment]
So finally we are able to run tests.
Test `test repeat write 1` from `testThaliManagerCoordinated.js` fails reliably on iOS but not Android in WiFi only mode.
Log is [here](https://gist.github.com/dersim-davaod/33755e7cb885521aa6c4379064cbdcdb).

**Comment by enricogior** [comment]
Test log using vNext_yarong_417_812 updated at the time of this post.
[iOS_test_log.txt](https://github.com/thaliproject/Thali_CordovaPlugin/files/496038/iOS_test_log.txt)

**Comment by yaronyg** [comment]
@enricogior This is basically the issue we wanted you to investigate. Why does it seem like at some point the TCP connections just stop working on iOS?

**Comment by yaronyg** [comment]
Please work on this when thaliproject/Thali_CordovaPlugin#1228 is done so we don't have to investigate what are possibly spurious errors.
