### ISSUE TITLE
Test 'Action fails because of a bad hostname.' fails on Android in WIFI mode

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1152]

**Comment by evabishchevich** [comment]
https://gist.github.com/evabishchevich/9cff989bf1a69284ea8167901808604e

**Comment by evabishchevich** [comment]
https://gist.github.com/evabishchevich/af73830958713dbe598255b43261992e

branch : vNext_yarong_417_812_848, commit 082d05c
mode: WIFI

Merged after Artem's fix on thaliproject/Thali_CordovaPlugin#1167

**Comment by chapko** [comment]
@evabishchevich It should be fixed in #1180
Please, try `vNext_yarong_417_812_chapko_1059` branch
