### ISSUE TITLE
Test 'Make sure docs replicate' fails on Android in WIFI mode

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1153]

**Comment by evabishchevich** [comment]
https://gist.github.com/evabishchevich/878e2a23950a22791639f44c0e9945a1

**Comment by evabishchevich** [comment]
https://gist.github.com/evabishchevich/5f68947e1cbb8c55c7f5ed5813906177
branch : vNext_yarong_417_812_848, commit 082d05c
mode: WIFI

**Comment by yaronyg** [comment]
Isn't reproducing
