### ISSUE TITLE
Test 'Call of onCheckpointReached handler on a single db change' failed on Android in WIFI mode

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1161]

**Comment by evabishchevich** [comment]
https://gist.github.com/evabishchevich/1ba4f3c36d693a920d2728c442173df9

**Comment by evabishchevich** [comment]
# Call of onCheckpointReached handler on a single db change
09-27 13:32:09.119 2534-2589/com.test.thalitest I/jxcore-log: not ok 88 OpenError: IO error: pouchdb-uuid:0.7643237374662415/LOCK: No such file or directory
09-27 13:32:09.120 2534-2589/com.test.thalitest I/jxcore-log:   ---
09-27 13:32:09.120 2534-2589/com.test.thalitest I/jxcore-log:     operator: fail
09-27 13:32:09.120 2534-2589/com.test.thalitest I/jxcore-log:   ...
09-27 13:32:09.123 2534-2589/com.test.thalitest I/jxcore-log: 2016-09-27 10:32:09 - ERROR TestsProcess: 'uncaught promise rejection, error: 'TypeError: info is undefined', stack: 'Changes.prototype.doChanges/<@/data/data/com.test.thalitest/files/www/jxcore/node_modules/pouchdb/lib/index.js:1541:7
                                                              unwrap/<@/data/data/com.test.thalitest/files/www/jxcore/node_modules/lie/lib/index.js:88:21
                                                              nextTick@/data/data/com.test.thalitest/files/www/jxcore/node_modules/immediate/lib/index.js:61:7
                                                              $0a@node.js:924:1
                                                              ''

**Comment by artemjackson** [comment]
@evabishchevich Please try locally with `vNext_yarong_417_812_artemjackson_1161_1178`
