### ISSUE TITLE
Test 'test repeat write 2' failed on Android

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1165]
https://gist.github.com/evabishchevich/d3745bb9597404d8d6d8bddc34efa526

**Comment by evabishchevich** [comment]
The same for 'test write'

**Comment by evabishchevich** [comment]
Are that logs valid for 'test write'? Look like there are some errors
https://gist.github.com/evabishchevich/0eb2b80cd08b204b8257787074f1ea10

branch : vNext_yarong_417_812_848, commit 082d05c
mode: WIFI

Merged after Artem's fix on thaliproject/Thali_CordovaPlugin#1167

**Comment by yaronyg** [comment]
@artemjackson I suspect these are actually related to the bug you fixed about us storing things in random places in Android. If you look at 'test repeat write 1' and 'test repeat write 2' you will see that we just require PouchDB and call new PouchDB(DB_NAME) which means if we run the tests on the same device twice then KABOOM. These have to be changed to use the PouchDB utils, get a randomly generated directory, etc.

**Comment by artemjackson** [comment]
@yaronyg Suspectiction is wrong. `PouchDB` has right directory, see [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_417_812/test/www/jxcore/bv_tests/testThaliManagerCoordinated.js#L30-L33).

**Comment by evabishchevich** [comment]
https://gist.github.com/evabishchevich/7af1643baddc17a5753e62afa7687b40

**Comment by evabishchevich** [comment]
@artemjackson I ran it with your changes from artemjackson_1165
https://gist.github.com/evabishchevich/e6b3142baf4d4567bfb7f64954d2231b

**Comment by artemjackson** [comment]
@yaronyg It's approved by @vasilevskayaem that `PouchDB` creates and writes to randomly generated directory. So the `[conflict: Document update conflict]` error doesn't relate to directories creation process.

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/6a4dcbace4c1b28a2da98778e1ea46a5

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/0fa43ac530ffc783833a4096aab0cfb1

**Comment by yaronyg** [comment]
This fails but it's really hard to repo

**Comment by artemjackson** [comment]
@yaronyg @andrew-aladev I found out why we couldn't get more them 10 node instances passed: `thaliSendNotificationBasedOnReplication` has a limit of the peers that should be notified. See [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_417_812_artemjackson_1165/thali/NextGeneration/replication/thaliSendNotificationBasedOnReplication.js#L93) for details.

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/b9aa02d1ff89aa6e88e98041a9506565 tested on master branch with "jxcore-cordova-url": "http://jxcore.azureedge.net/jxcore-cordova/0.1.4-v8/release/io.jxcore.node.jx" in package json

**Comment by artemjackson** [comment]
@yaronyg @andrew-aladev, @vasilevskayaem and I got an interesting result:
If run the test on 3 local Android devices with `MAXIMUM_NUMBER_OF_PEERS_TO_NOTIFY` limit set to 2 then the test passes 5 times in a row.

**Comment by artemjackson** [comment]
I have an assumption that we should check Thali replication algorithm. I'm working on it now.

**Comment by artemjackson** [comment]
> If run the test on 3 local Android devices with MAXIMUM_NUMBER_OF_PEERS_TO_NOTIFY limit set to 2 then the test passes 5 times in a row.

But didn't pass on CI.
