### ISSUE TITLE
Why does thaliMobile.getMethodByNetworkType have a networktype argument?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1166]
We don't use the argument adn given how target works it doesn't seem like we need it. But all the calls we have to it pass in networkType.

The only reason I can think for it to be there is if it was intended as a validation check to make sure that the target is appropriate given the networktype.

Can you please clarify and either finish the code or remove the argument?

**Comment by artemjackson** [comment]
@yaronyg I agreed with you. It's a heritage of refactoring
It's fixed in #1175
