### ISSUE TITLE
Is WiFi only mode in tests actually testing WiFi Only mode?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1167]
@artemjackson - although this bug belongs to Andrew I'd appreciate it if you would look at it as well just to give commentary since you did the original work here and thus have context I lack.

@larryonoff / @enricogior  - You two will need to pay close attention to this one because if I'm right then our wifi only tests haven't been testing wifi. They have also used native layer. Although as I explain below that would seem kinda odd so I'm hoping I'm missing something.

To control the mode that tests run in we are supposed to set a variable called networkTypes in UnitTest_App.js. This is then used to set a variable global.NETWORK_TYPE which the tests are supposed to examine while running.

But right now global.NETWORK_TYPE is only checked in exactly three places, testThaliMobileNative, testThaliMobileNativeWrapper and testThaliWifiInfrastructure. Which means all the other test files are ignoring it, right? Specifically, thaliMobile takes an argument to start that sets its network type. If not provided that argument defaults to 'both'.

So that means that all the testing we are doing for higher level functionality aren't honoring NETWORK_TYPE and are trying to use both? The reason for the question mark is that if this were the case then I would assume that @evabishchevich would have seen native traffic in the logs when he did WiFi only testing. I also would have expected that @dersim-davaod and @baydet would have seen all sorts of issues when they ran WiFi only tests in iOS.

So I'm confused. If I'm reading the code right, we aren't actually testing in WiFi only mode any of the higher level stuff at all! So am I confused?

If I'm not confused then we need to fix this asap. The fix I would propose is:
- [ ] Make all three start arguments to ThaliMobile mandatory. We should throw an exception if we don't get 3 arguments. This will immediately flush out who is calling ThaliMobile without setting network type.
- [ ] In some cases (I'm thinking about pretty much all the tests in testThaliMobile) the actual arguments beyond router don't matter. So in that case just put in a bogus value for pskIdToSecret but please put in the global.NETWORK_TYPE value for networkType just to be safe.
- [ ] Fix all the other tests that directly or indirectly call thaliMobile to make sure they properly pass in global.NETWORK_TYPE.It looks like this is mostly testThaliMobile, testThaliMobileNotification and testUtils whose startServerInfrastructure is used in various places.
- [ ] Please add tests to testThaliMobile that actually verify that we properly honor networkType (just checking that the member variable is properly set after calling start is fine)
- [ ] Please implement thaliproject/Thali_CordovaPlugin#1009 and update testThaliManager both to test that we properly honor the argument (e.g. we pass it to thaliMobile, proxyquire is fine for this) and to update the tests to properly use the new argument. We also will need to update testThaliManagerCoordinated.

**Comment by artemjackson** [comment]
@yaronyg It's a fail. Hotfix is #1176
