### ISSUE TITLE
Please drive all Android WiFi Tests to pass

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1169]
@evabishchevich / @vasilevskayaem Please pick one of you to own this bug and the other to own thaliproject/Thali_CordovaPlugin#1170.

Whomever gets this bug needs to make sure that thaliproject/Thali_CordovaPlugin#1167 and thaliproject/Thali_CordovaPlugin#1089 are both resolved.

Once they are resolved then you should be able to take vNext_yarong_417_812 and run the WiFi only tests in Minsk on 3 Android devices (try to pick all the same device if you can) and report which tests are failing here.

Then please start investigating the failing tests to figure out what's going wrong.

**Comment by evabishchevich** [comment]
Provided logs for thaliproject/Thali_CordovaPlugin#1182, thaliproject/Thali_CordovaPlugin#1161, thaliproject/Thali_CordovaPlugin#1153, thaliproject/Thali_CordovaPlugin#1152

**Comment by yaronyg** [comment]
All tests passed with new test framework!
