### ISSUE TITLE
Please drive all Android Native Tests to pass

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1170]
@evabishchevich / @vasilevskayaem Please pick one of you to own this bug and the other to own thaliproject/Thali_CordovaPlugin#1169.

Whomever gets this bug needs to make sure that thaliproject/Thali_CordovaPlugin#1167 and thaliproject/Thali_CordovaPlugin#1089 are both resolved.

Once they are resolved then please take vNext_yarong_417_812 and go to test/www/jxcore/UnitTest_app.js and set networkTypes to [ThaliMobile.networkTypes.NATIVE] and then run all the tests in Minsk on 3 Android devices (try to pick all the same device if you can) and report which tests are failing here.

Personally I'm 100% fine with just continuing the work @evabishchevich already started in terms of testing testThaliMobileNative.js and testThaliMobileNativeWrapper.js since those two tests are guaranteed to only run native no matter what networkTypes is set to. So it's fine to just keep focusing on issues in those tests and then worry about the rest of the stack when we have those two files under control.

**Comment by vasilevskayaem** [comment]
test write - only bluetooth, appears sometimes https://gist.github.com/vasilevskayaem/eed80ecdf14ffa5651c4f12cf38b5b5a

test repeat write 1  - only bluetooth,appears sometimes

test repeat write 2 -  only bluetooth, appears sometimes

Get error when trying to double connect to a peer - only bluetooth, appears sometimes
https://gist.github.com/vasilevskayaem/4da9fb84b77bb2cce85663e5fb0e860b

Coordinated seq test - both wifi,bluetooth, appears sometimes

Can connect to a remote peer - bluetooth, appears sometimes
https://gist.github.com/vasilevskayaem/239e64a048c8f2382bd90a38f0a852b3

Get error when trying to double connect to a peer - bluetooth, appears sometimes
https://gist.github.com/vasilevskayaem/c1819a15b562eaa53c89dd795c4c3787

Can shift large amounts of data - bluetooth, appears sometimes 
https://gist.github.com/vasilevskayaem/11c1be95ae9adf6cc036124aff183a9c

#startUpdateAdvertisingAndListening - ending remote peers connection kills the local connection - bluetooth,always
https://gist.github.com/vasilevskayaem/34aef1c7565e291c25dc4d7451245e79

#startUpdateAdvertisingAndListening - destroying remote peers connection - bluetooth, always
https://gist.github.com/vasilevskayaem/b0297678ec062126fc280b29d8f3bf9a

#startUpdateAdvertisingAndListening - destroying the local connection kills the connection to the remote peer - bluetooth always
https://gist.github.com/vasilevskayaem/3cc93cc73949eed16ea0b80e78d1ca10

Test updating advertising and parallel data transfer -  bluetooth, sometimes 
https://gist.github.com/vasilevskayaem/1a003099206eb3426ed921f202facea0

initial peer discovery - bluetooth , sometimes
https://gist.github.com/vasilevskayaem/2c6614b86d20a372dfaa894fb0de8cfd

update peer discovery - bluetooth, sometimes
https://gist.github.com/vasilevskayaem/dbe150a5e2f865f650a51f18da5ce820

**Comment by yaronyg** [comment]
Priority 1 - testThaliMobileNative.js
Priority 2 - testThaliMobileNativeWrapper.js
After those two are working everything else should behave

**Comment by yaronyg** [comment]
Closing in favor of thaliproject/Thali_CordovaPlugin#1291
