### ISSUE TITLE
Merge vNext into vNext_yarong_417_812 and then merge vNext_yarong_417_812 into master

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1173]

**Comment by yaronyg** [comment]
Merged vNext and vNext_yarong_417_812 to create the new iOS branch.

Asked @larryonoff if he sees any issues with us pushing existing vNext_yarong_417_812 directly to master. I don't but I also don't want to break anything and we can wait another day so it's worth asking just to make sure I'm not missing something.

**Comment by larryonoff** [comment]
@yaronyg I don't see any issues here. I asked the team, they also don't. So I've created PR thaliproject/Thali_CordovaPlugin#1209 that merges `vNext_yarong_417_812` into `master`.

**Comment by larryonoff** [comment]
@yaronyg. @baydet just found that `vNext` and `vNext_yarong_417_812` merged with wrong `vNext` version, not the latest.

**Comment by baydet** [comment]
![Alt Text](https://media.giphy.com/media/JwNPAckJDiPsI/giphy.gif)
