### ISSUE TITLE
Does Hiqo have the ability to run the iOS devices on an isolated network?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1174]
We need to run the iOS tests so they can run both with the ability to see each other over WiFi and without the ability to see each other over WiFi (but with the ability to see the coordination server). Is there a router in Hiqo's office's configured to enable these two modes of behavior?

**Comment by larryonoff** [comment]
@yaronyg our infrastructure allows us creating both of these cases. As soon as it's needed we'll setup it.
