### ISSUE TITLE
Upgrade socket.io-client with the latest version

### ISSUE THREAD

**Issue by andrew-aladev** [thaliproject/Thali_CordovaPlugin#1179]
@enricogior said that we have some problems with running `bufferutil` on `jx`. The only reason for us to use `bufferutil` is `socket.io-client 1.3.7`. I've upgraded `socket.io` to version `1.4.8` without problems. But any newer version of `socket.io-client` don't want to work with our current test server. 

We can upgrade `socket.io-client` to any version `>= 1.4.0` and `bufferutil` will disappear.

**Comment by yaronyg** [comment]
I'm confused, didn't you say that if we upgarde socket.io-client higher than 1.3.7 then socket.io-client stops working with our server? In any case it would certainly be very good to get rid of bufferutil. Please proceed as appropriate.

**Comment by andrew-aladev** [comment]
Stackovereflow [here](http://stackoverflow.com/questions/37407977/socket-io-websocket-error-enoent/39750110#39750110)

**Comment by andrew-aladev** [comment]
Fixed
