### ISSUE TITLE
Problem with #1154 hotfix

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1189]
In thaliproject/Thali_CordovaPlugin#1154 we put in handles in CoordinatedClient.js for connect_timeout, connect_Error, reconnect_refused and reconnect_error. But those handlers are _connect and _reconnect which both assume that we have a successful connection. So we are effectively silently eating errors from socket.io. Which means the connections have failed, we don't recognize that and we will silently hang. That can't be right.

I looked up some of the errors [here](http://socket.io/docs/client-api/#) and  they don't seem to match. So we need to check that we are looking for the right errors and when we get an error we need to properly fail. 'reconnect_failed' looks particularly important because that one seems to mean "I'm done" which means that failure is certain. It would at least be good to have the client log reflect that even though (by definition) the server isn't going to see it.

**Comment by artemjackson** [comment]
Already fixed in #1194
