### ISSUE TITLE
We need a global switch to turn off long stacks in bluebird

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1190]
When we run tests on devices using long stacks we are changing our performance and general behavior. A lot of extra code gets included that can cause failures and Bluebird itself says " Long stack traces imply a substantial performance penalty, around 4-5x for throughput and 0.5x for latency."

So the bottom line is that when we use long stacks we aren't testing the way that devices will run in production. So we really need some kind of global switch to control if we use long stacks and that switch should be off by default.

**Comment by artemjackson** [comment]
Closed in favour of #1197
