### ISSUE TITLE
Break Android code into constants for all Cordova methods and events

### ISSUE THREAD

**Issue by mpodwysocki** [thaliproject/Thali_CordovaPlugin#12]
The method names and events should be broken into its own module for the following:
## Methods ##
- `StartBroadcasting`
- `StopBroadcasting`
- `Connect`
- `Disconnect`

## Events ##
- `peerActivityChanged`
- `networkChanged`

**Comment by yaronyg** [comment]
Technically Jukka has done this work. We know it's not fully compliant but those will be bug fixes that will come out of your tests.
