### ISSUE TITLE
Is multiConnectResolved idempotent?

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#1210]
Currently it is the possible scenario when `multiConnectResolved` is called from AppContext multiple times for the same syncValue. So is it method idempotent or should we track these calls?

Is there is any reason to be this function not idempotent?

**Comment by yaronyg** [comment]
Every call to multiConnect MUST have a unique value for syncValue.

**Comment by baydet** [comment]
will be fixed in thaliproject/Thali_CordovaPlugin#1199
