### ISSUE TITLE
Please change the test runner to run each test in its own child process of JXcore

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1228]
The way we run tests right now we load all the tests at the start which is a huge number of files and is stressing JXcore way beyond what it would have to deal with during run time. So we need to change how we run tests so that we run each test in its own JXcore instance. So we would probably take runTests and instead of having it load each test file into the environment, instead we would have it spawn a JXcore child process and have it run the test, exit, clean up and then create a new child process for the next test. The obvious question is how do we make the coordination server work properly? It depends on getting a test count which comes from reading all of the files but that should be easy to fix. .Only will also be tricky but let that be a lower priority feature.

**Comment by artemjackson** [comment]
@andrew-aladev take a look on #993 it can be used as a start point for an implementation.

**Comment by yaronyg** [comment]
He started down the path of implementing the child process but we ran into a serious problem that appears to be because of socket.io and so now he has to work on that. We probably need to get rid of socket.io. But first we are going to take a test that fails with a known socket.io problem on Android, get that to repro with SM on desktop and if it does then try to run the test with a hacked up TCP only replacement for socket.io and if that works then we should get rid of socket.io. 

We think, btw, that the problem with socket.io is that it uses a ton of polyfills which we know make JXcore unhappy with SM. We are now looking at nssocket.

**Comment by yaronyg** [comment]
BTW, see thaliproject/Thali_CordovaPlugin#1231 for details on socket.io problem.

**Comment by larryonoff** [comment]
Link issue that verifies usage `spawn` / `exec` on iOS thaliproject/Thali_CordovaPlugin#1258

**Comment by andrew-aladev** [comment]
I am going to finish spawn processes tests, some coordinated test fails, I will fix them.

**Comment by andrew-aladev** [comment]
It is done. I hadn't create a pull request, because it breaks ios land.

**Comment by yaronyg** [comment]
Please submit to master. We'll figure out how to get iOS to work again as part of thaliproject/Thali_CordovaPlugin#1261

**Comment by vasilevskayaem** [comment]
wi-fi tests on Android passed
