### ISSUE TITLE
Test Native fails OutgoingSocketThreadTest

### ISSUE THREAD

**Issue by vasilevskayaem** [thaliproject/Thali_CordovaPlugin#1229]
https://raw.githubusercontent.com/ThaliTester/TestResults/87465790cb99449_Android_tests_from_vNext_evabishchevich/thali05_Huawei-Nexus%206P.md

**Comment by yaronyg** [comment]
The problem is that the test isn't hardened so if the write gets a random socket failure (which on Bluetooth is a given) then the test will fail because it doesn't know how to handle it. We should put in retry logic but it isn't a priority right now.
