### ISSUE TITLE
#startUpdateAdvertisingAndListening - ending remote peers connection kills the local connection'' and 'destroying remote peers connection kills the local connection'

### ISSUE THREAD

**Issue by vasilevskayaem** [thaliproject/Thali_CordovaPlugin#1231]
# startUpdateAdvertisingAndListening - ending remote peers connection kills the local connection - bluetooth,always
# startUpdateAdvertisingAndListening - destroying remote peers connection - bluetooth, always
# startUpdateAdvertisingAndListening - destroying the local connection kills the connection to the remote peer - bluetooth always

https://gist.github.com/vasilevskayaem/540ab73a14d79438b728db7e64ecdc33

I changed var RETRIES = 20  in startAndGetConnection ( android/assets/www/jxcore/bv_tests/testThaliMobileNative.js ) . Before devices sometimes disconnected 'Socket to device name: 'samsung-SM-G930F' disconnected, reason: 'client namespace disconnect'', but after my change I also get "ERROR TestServerProcess: 'got 'SIGINT', terminating'"

**Comment by andrew-aladev** [comment]
Maybe `socket.io-client` failed with `jxcore`. We can remove `socket.io` from project.

**Comment by andrew-aladev** [comment]
I am working on this issue now.

**Comment by andrew-aladev** [comment]
I've implemented a workaround. The code is bad, this shouldn't be a part of master branch. We want to check whether removing `socket.io-client` will fix mobile problems.

**Comment by vasilevskayaem** [comment]
get error log https://gist.github.com/vasilevskayaem/5a35926761fd822a8b085a8538a77c49

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/671d2bef726b23a30fdaa906be0d74b2

**Comment by andrew-aladev** [comment]
We are working on 'can connect to remote' tests.

**Comment by andrew-aladev** [comment]
This is related with thaliproject/Thali_CordovaPlugin#1374
