### ISSUE TITLE
gradle.properties needs to be deleted after every compilation

### ISSUE THREAD

**Issue by czyzm** [thaliproject/Thali_CordovaPlugin#1235]
When I install thali plugin in app and run cordova compile android all works ok. But running cordova compile android for the second time fails with error: Failed to update the gradle.properties file!

This is a file that is created in cordova plugin. After every compile I need to remove it to compile again.

**Comment by larryonoff** [comment]
Started working on it in PR thaliproject/Thali_CordovaPlugin#1238

**Comment by larryonoff** [comment]
@czyzm the issue should be fixed in PR thaliproject/Thali_CordovaPlugin#1238. Please check as soon as you have time.
