### ISSUE TITLE
Why aren't we passing in quitSignal?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1240]
If you look [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/bb27aa30907d5ef6c1d7bcbeda966df9751afa3d/test/www/jxcore/bv_tests/testThaliMobileNative.js#L225) you will see that when we recursively call connectToPeer we don't pass in the quitSignal object. I can imagine that causing us grief during teardown. Is this a simple bug or am I missing something?

**Comment by andrew-aladev** [comment]
Yes, we should pass `quitSignal` to this function.

**Comment by yaronyg** [comment]
Note to self: Submit this fix to master.

**Comment by yaronyg** [comment]
Fixed in thaliproject/Thali_CordovaPlugin#1248
