### ISSUE TITLE
Please see if the task API works in iOS

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1262]
Per thaliproject/Thali_CordovaPlugin#1261 we need to use the task API in iOS. But is it even working? Please check out https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-tasks.markdown

**Comment by baydet** [comment]
I've run this code
```
var task = {
  define: function () {
  },
  logic: function (param) {
    console.log("We are in a sub-instance now. Argument value is:", param);
    return "ok";
  }
};

var callback = function (err, result) {
  if(err) throw err;
  console.log(result);
};


var i = 0;
for (i = 0; i < 100; i++) {
    jxcore.tasks.addTask(task, {str: "hello"}, callback);
}
console.log(jxcore.tasks.jobCount());
```

and received these logs
https://gist.github.com/baydet/be1bcfece89a117b4f1346b44e3fffce

**Comment by yaronyg** [comment]
@enricogior @andrew-aladev It looks like the task API works on iOS so once we have finished thaliproject/Thali_CordovaPlugin#1228 (which looks to be done) then we can talk about how we want to implement a variant that uses the task API on iOS.
