### ISSUE TITLE
If during tests with Android and connect we have a failure we lose the port

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1270]
If we lose the port and call connect again we will get already connected and never get the port back. We have to maintain the port itself.

**Comment by yaronyg** [comment]
So let's be very clear on the scenario.

1. We have called connectToPeerPromise and it successfully returned. Because if it didn't successfully return then we never got a connection.
2. From there we will call clientSuccessConnect who will call connectToListenerSendMessageGetResponseLength. What's interesting is that *all* paths from that function call result in the connection to the native layer being closed either via destroy() or end(). This applies to both success and failure.

So the point is that even if we have a failed connection on Android, it won't matter because we will tear down the TCP link to the native layer which will cause us to tear down the bluetooth socket which means the next connect request should get a new port.

So there is no need to remember the port at all.

Am I missing something?

**Comment by andrew-aladev** [comment]
Yes, this is related with a new test in `vNext_aaladev_1242`. 

```
ClientRound._connectToPeer = function (peer) {
  var data = {};
  data.promise = new Promise(function (resolve, reject) {
    data.resolve = resolve;
    data.reject  = reject;

    Mobile('connect').callNative(peer.peerIdentifier, ... });
  }
  return data;
}
```

`ActiveConnections` can `reject` this promise with timeout.
