### ISSUE TITLE
update native code to pass testThaliMobileNativeiOS

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#1280]
blocked on thaliproject/Thali_CordovaPlugin#1199

**Comment by yaronyg** [comment]
testThaliMobileNativeiOS tests are passing!

**Comment by baydet** [comment]
blocked on thaliproject/Thali_CordovaPlugin#1199

**Comment by yaronyg** [comment]
Why are you blocked? Why can't you grab Dersim's PR and put it in a temporary branch and test from there?

**Comment by baydet** [comment]
because I'm doing all the testing on iOS branch. But Dersim's PR was based initially on vNext branch. He rebased these changes on iOS almost before the call

**Comment by baydet** [comment]
After I'll manage with this PR from hell (what is P0 for us now) I'll switch back to testing

**Comment by baydet** [comment]
closed in favor thaliproject/Thali_CordovaPlugin#1301
