### ISSUE TITLE
Figure out the latency for mobile calls on Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1283]
Test:

1. Make a connect to another device
2. Make 100 serial calls to connect to the same device. Each one should fail with an 'already connected' error.
3. For each of the 100 serial calls record the latency from when the call was made until the callback was returned. Please add to this bug the list of the 100 results and then calculate the average, median and standard deviation of the results.

We need to know how bad pounding the native API really is.

**Comment by vasilevskayaem** [comment]
fails with strange timeout 
https://gist.github.com/vasilevskayaem/7bd612c47aa3c1de09d7e0cf8b334de7

but I set up 100 minutes timeout on test

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/a6e6a321fa9664f034372b2034db94a0 each time test fails with not ok 12 we received error on first connection, error: 'Error: Already connect(ing/ed)', id: '08:21:EF:82:2A:96-8' and starts again and again

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/825058b4cda8dafbd2d7d682eb7c7022

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/bf2f51b7061e07a9fe24b77c24cb6d3c

**Comment by andrew-aladev** [comment]
We have a results https://gist.githubusercontent.com/vasilevskayaem/bf2f51b7061e07a9fe24b77c24cb6d3c/raw/966fe672338f80ecfe1e985320a3cf280f1387a2/gistfile1.txt

We have
```
total attempts count: 101, latency for id: '24:00:BA:F9:9A:9F-68', average: 116.867 ms, median: 1.973 ms, standard deviation: 1153.158
```
