### ISSUE TITLE
Measure runtime latency cost from peerAvailabilityEvents from Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1284]
Right now we haven't implemented batching logic so Android will pretty much pummel Node with peerAvailabilityEvents, often just repeating the same information over and over again. We need to run tests to help us understand the cost.

We can set up a setImmediate loop where we record system time just before we call setImmediate and then we record system time right after setImmediate calls us. This is how much time we spent handling events. So what we can do is on Android we can register a peerAvailabilityChanged handler that just does something silly like increments a counter. We can then run the setImmediate loop (which is just calling itself, setImmediate doesn't build a stack so we don't have to worry about stack exhaustion) that runs for say 10 seconds. Each time we run we record how many milliseconds were lost to events. At the end of the 10 seconds we output how much of the 10 seconds we spent handling events.

Test 1 - In node, on Android, with all the Mobile interfaces set to stop run this test say 10 times and see how much time we spent in between setImmediate calls. This is our base line.

Test 2 - In node, on Android, with listening for advertisements turned on and with a registered handler in node for peerAvailabilityChanged and with a device advertising run the same test 10 times. The peerAvailabiityChanged handler should do something cheap like increment a counter, just so it does something (I don't know if Node is smart enough to optimize away a handler that can't do anything). Run this 10 times. Please publish the two sets of 10 results in this bug.

This will tell us just how expensive Android's behavior for pushing endless peerAvailabiityChanged events at us really is.

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/222ec4683ef02475785a84ba7e653a6d

10-13 16:44:53.385 22043-22210/com.test.thalitest I/jxcore-log: 2016-10-13 13:44:53 - INFO testPeerAvailabilityOverhead: 'result overhead 9.165074034'
10-13 16:44:53.385 22043-22210/com.test.thalitest I/jxcore-log: 2016-10-13 13:44:53 - INFO testPeerAvailabilityOverhead: 'diff 0.12228895099999981'

**Comment by andrew-aladev** [comment]
We have about 0.12 seconds overhead. But we have a big deviation with our overhead calculation. I've received about +-0.1 seconds deviation. So I think 'peerAvailabilityChanged' is not heavy for us.

**Comment by andrew-aladev** [comment]
`INFO testPeerAvailabilityOverhead: 'start overhead 9.042785083'`

**Comment by andrew-aladev** [comment]
https://github.com/thaliproject/Thali_CordovaPlugin/commit/a9ae6eb91605a62577a934e0e406cacbe26cfd5f

**Comment by andrew-aladev** [comment]
Closing in favor of thaliproject/Thali_CordovaPlugin_BtLibrary#86
