### ISSUE TITLE
check reconecting problem https://github.com/czyzm/ThaliTestApp

### ISSUE THREAD

**Issue by vasilevskayaem** [thaliproject/Thali_CordovaPlugin#1287]

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/6997f4c9ee70de933ef606764a306a6e 
https://gist.github.com/vasilevskayaem/e001b801c0ac3837f2dc9b3c78522b50

Sometimes I see that devices have strange mac ids (the same "My bluetooth address is BC:75:74:3A:BC:B7" ) . And sometime appears 'Got err   Could not establish TCP connection'. Probably this error can cause peer reconnect another phone

**Comment by yaronyg** [comment]
1. Please re-run the tests and see if initialize is in fact getting called three times.
2. Then close this bug there is no issue

**Comment by vasilevskayaem** [comment]
it was something strange with logs, because we never call BluetoothManager: initialize separately, before we call bind(), but there aren't here logs from bind method. I restarted android studio and cant reproduce such logs anymore
