### ISSUE TITLE
Please figure out if either the Samsung S7 or the nexus 6p need to use manufacturer ID for BLE

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1290]
Are they using Manufacturer ID or can they successfully use service type?

**Comment by vasilevskayaem** [comment]
for both devices I see in logs that both advertisement types are supported, so Samsung S7 and the nexus 6p can use Manufacturer ID and service type.

https://gist.github.com/vasilevskayaem/b505428fe7421622e441091f44cf5905

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/7aa19da71f0683d5af9f52e0985de60c

Here is sample of peerAdvertise that was generated for two Nexus and Samsung, so It seems that Service data is used.
