### ISSUE TITLE
Measuring battery consumption on Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1294]
# Setup

Please follow the instructions at https://developer.android.com/studio/profile/battery-historian.html to use Batterystats and install Battery Historian.
# Tests

Test 1 - Disconnect the test phone from power and make sure that it is not running any Thali related apps of any kind. Make sure they are disabled or even better, uninstalled. This is going to be the battery consumption baseline for the phone so it's important that it accurately reflect the phone's battery consumption when not running Thali. Please let the phone sit there doing nothing for 10 minutes. Then use Batterystats/Battery Historian to see what % of the phone's battery was consumed.

Test 2 - Use the test app that @andrew-aladev will write in thaliproject/Thali_CordovaPlugin#1292. By default the app should do nothing. It shouldn't turn on any radios. It shouldn't run any code. It should just load Thali and then sit there doing nothing interesting. Please let the phone sit there for 10 minutes. Then measure it's battery consumption.

Test 3 - Use the test app but now set the radio type to wifi, call Listen_Only and make sure there are no other instances of the test app running on any device. We want to see what the battery draw is when we are listening but not receiving anything. Same as before, let it run 10 minutes and then measure battery consumption.

Test 4 - Radio Type - Wifi, Mode - Advertise_Only

Test 5 - Radio Type - Native, Mode - Listen_Only

Test 6 - Radio Type - Native, Mode - Advertise_Only

Test 7 - Radio Type - Both, Mode - Advertise_Only

Test 8 - Radio Type - Both, Mode - Listen_Only

For these next tests we are going to use two phones, phone A and B. Both are running the test app in the configuration given below. We ONLY measure battery consumption on phone A.

Test 9 - Phone A - Wifi - Listen_Only, Phone B - Wifi - Advertise_Only

Test 10 - Phone A - Native - Listen_Only, Phone B - Native - Advertise_Only

Test 11 - Phone A - Both - Listen_Only, Phone B - Both - Advertise_Only

Test 12 - Phone A - Wifi - Both, Phone B - Wifi - Both

Test 13 - Phone A - Native - Both, Phone B - Native - Both

Test 14 - Phone A - Both - Both, Phone B - Both - Both

Now you are probably thinking to yourself "Is he nuts? This is going to take me 140 minutes or nearly 3 hours of manual testing! That's awful!" And you are right. In theory we could automate this testing in a couple of different ways. The easiest way would be to write an extension to the test app running on both phones that would automatically switch mode ever X minutes. So, for example, while phone A is running through tests 1 - 8, which should take 80 minutes, phone B can just do nothing. Then at minute 80 it can switch into the configuration for test 9.

The question is - how much battery data will you get for 140 minutes? I suspect it might be enough to cause problems downloading it or the data might even be lost as the logs try to keep themselves from getting too big. Play around and see what works.

Also if you have 140 minutes of data can you pull out the battery consumption from each 10 minute segment using the battery historian?

Another approach would be to write a shell script that pulls the battery data after each test before resetting it. You could put in say a 1 or 2 minute delay between each test to give the shell script time to pull out the data and record it.

Use your imagination. This is an obviously automatable situation.
# Output

I need you to save the HTML output from each test so I can see it. There is a lot of data there beyond just the battery draw. It shows how often the device woke up the cpu, how often the radios are on, etc. We need to review that data to understand why the battery draw is what it is.

**Comment by vasilevskayaem** [comment]
checked for devices without app: for Nexus 6p discharge rate is less than 1% per hours, for S7 from 1 to 2 % per our. Checked our app with coordination server : Nexus ±3% per hour, S7 6-7% per hour. But coordination server recharge battery as well. So I will wait thaliproject/Thali_CordovaPlugin#1292. I think 10 min is enough for calculation.

**Comment by yaronyg** [comment]
BTW @vasilevskayaem the most important tests are 1-8. Let's get those done before we move on to 9-14.

**Comment by yaronyg** [comment]
@vasilevskayaem Please first prioritize among tests 1-8 the native tests first (e.g. BLE tests, Native mode)

**Comment by vasilevskayaem** [comment]
Test N# | Discharge rate per hour on S7
------------ | -------------
1 | 0.76-0.92%  wi-fi and bt off
2 nothing | will retest soon
3 wifi, Listen_Only | 2.97%
4 Wifi, Advertise_Only | 3.59%
5 native, Listen_Only | 4.79%
6 native, Advertise_Only | 5.99%
7 both, Advertise_Only | 8.56%
8 both, Listen_Only | 7.49%
9 Phone A - Wifi - Listen_Only, Phone B - Wifi - Advertise_Only | 19.97% !!!!! will retest it
10 Phone A - Native - Listen_Only, Phone B - Native - Advertise_Only | 19.97!!!!
11 Phone A - Both - Listen_Only, Phone B - Both - Advertise_Only | 29.96%!!!!!
12 Phone A - Wifi - Both, Phone B - Wifi - Both | 3.52%
13 Phone A - Native - Both, Phone B - Native - Both | 4.28%
14 Phone A - Both - Both, Phone B - Both - Both | 4.79% 

12-14 test results not right, because test app doesn't work correctly https://gist.github.com/vasilevskayaem/8a5ca7df59c91963cff6f32c5be0b0f1

**Comment by vasilevskayaem** [comment]
https://drive.google.com/open?id=0B3Zint8ZY0O8dlU2QUZCU2ZFSkE

**Comment by yaronyg** [comment]
It's worth at least re-running test 5 with scanning for manufacturer ID disabled to see if that reduces consumption. Also while the test is running please look at CPU usage to see if we are eating any CPU. Ideally during test 5 the CPUs should be able to shut down because we shouldn't find anything that requires the BLE hardware to notify the CPUs.

**Comment by yaronyg** [comment]
Are we asking for the permission in Android to exempt ourselves from doze and standby mode? (See thaliproject/Thali_CordovaPlugin#413 for context). We need the tests to run with screen off.

**Comment by vasilevskayaem** [comment]
Yes, native listening and advertisement are working. I just add some logs to verify it.

**Comment by yaronyg** [comment]
1. We really need the screen lock numbers for all the tests.
2. We need to see if there is anyway to do BLE scanning without having the hardware notify the CPU of empty results! Please play with setReportDelay to see how that affects battery life.

**Comment by vasilevskayaem** [comment]
run Test 10 with 

delay 500 (default) - 3.31%
delay 1000 - 2.85%
delay 1500 - 2.73%
delay 2000 - 2.58%

**Comment by yaronyg** [comment]
Please re-run test 10 with delay set to 0. Please run test 5 with delay set to 0. Then please re-run just those two tests on the Nexus 6P to see if it has the same behavior as the Samsung.

**Comment by vasilevskayaem** [comment]
checked for Nexus we have the same behaviour. If reportDelay = 0 app notify onScan result is called only if we found peer, if reportDelay>0 onBatchScanResult is called every reportDelay period.

**Comment by vasilevskayaem** [comment]
test 5 with reportDelay = 0 -- 1.19%
test 10 with reportDelay = 0 -- 2.08%

**Comment by vasilevskayaem** [comment]
fully charged phone: 

10 test with delay = 0 -- 1.88%
10 test with delay = 2000 -- 2.44%
