### ISSUE TITLE
Create ID changer utility for test app

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1295]
This is a command line script based on the code you wrote for thaliTest that lets someone change the SSDP_NT value, service type/manufacturer ID for Android and service type for iOS for the test app. That way someone can run the script on their local instance of the test app and it won't interfere with other people running the test app.

**Comment by andrew-aladev** [comment]
I've implemented this replacer as a plugin for our cordova application. It will be executed before build. So any new build will have a new SSDP values.
