### ISSUE TITLE
Update NSStreams management logic to avoid stopping NSInputStream receive data

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#1297]
in thaliproject/Thali_CordovaPlugin#1286 we can have a situation when in NSOutputStream will be written data more than 4k. What may be cause of losing data on NSInputStream side

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Streams/Articles/WritingOutputStreams.html#//apple_ref/doc/uid/20002274-BAJCABBC

We should update native iOS code to avoid these situations

**Comment by dersim-davaod** [comment]
PR #1312 is out.
