### ISSUE TITLE
Break iOS code into constants for all Cordova methods and events

### ISSUE THREAD

**Issue by mpodwysocki** [thaliproject/Thali_CordovaPlugin#13]
The method names and events should be broken into its own module for the following.  This is for @softwarenerd but will be moved to David Douglas once he is working on the code actively.

## Methods ##
- `StartBroadcasting`
- `StopBroadcasting`
- `Connect`
- `Disconnect`

## Events ##
- `peerActivityChanged`
- `networkChanged`

**Comment by tobybrad** [comment]
I assume we mean move the api surface to jxCoreExtensions.m

**Comment by yaronyg** [comment]
Is this finished?
