### ISSUE TITLE
Avoid usage of GCD with NSStreams

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#1300]
In thaliproject/Thali_CordovaPlugin#1286 (https://github.com/thaliproject/Thali_CordovaPlugin/pull/1286#issuecomment-253193142) in VirtualSocket.swift we're combining usage of GCD and NSThread+NSRunLoop. This logic could lead us to the situation when NSThread under gcd will be paused by gcd when our NSStream task is not finished yet.

**Comment by dersim-davaod** [comment]
The fix is implemented in origin/iOS_dersim_1300
Since it based on changes from #1312, I think the PR will be created when #1312 is merged.
