### ISSUE TITLE
What happens to wifi advertising if we aren't connected to a wifi endpoint?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1302]
Setup:
Start Thali, turn on advertising, make sure the phone is NOT connected to a wifi endpoint. What errors do we get in the log? How does our SSDP stack handle this? Does it fail? Does it keep retrying even though there is nobody listening since we aren't on Wifi?

**Comment by andrew-aladev** [comment]
I am implementing a new app.js that will show this behaviour.

**Comment by andrew-aladev** [comment]
We have a guard in `thali/NextGeneration/thaliWifiInfrastructure.js:515` so we will receive a rejection from `thali/NextGeneration/thaliWifiInfrastructure.js:246` and our call `thaliWifiInfrastructure.startUpdateAdvertisingAndListening()` will be rejected.

I will comment this guard and test again.

**Comment by yaronyg** [comment]
Per our conversation let's leave the guard and then we can just call the new Wifi api @vasilevskayaem wrote to turn off wifi and see what happens in the ADB logs.

**Comment by yaronyg** [comment]
So my previous comment is wrong. The whole point of this test is to see what happens if Wifi is on but is not connected to anything. So the wifi API we got from @vasilevskayaem won't help as it only turns wifi on and off. What we need is a manual test where we turn the test on with wifi running and then only later do we manually keep wifi on but kick the phone off any access point.

**Comment by andrew-aladev** [comment]
10-17 18:28:15.644 23380 23427 I jxcore-log: 2016-10-17 15:28:15 - ERROR TestsProcess: 'uncaught promise rejection, error: 'AssertionError: Attempting to clear a non-existing interval', stack: 'notEqual@assert.js:144:1
10-17 18:28:15.644 23380 23427 I jxcore-log: SsdpServer.prototype._stopAdLoop@/data/data/com.test.thalitest/files/www/jxcore/node_modules/node-ssdp/lib/server.js:95:3
10-17 18:28:15.644 23380 23427 I jxcore-log: SsdpServer.prototype.stop@/data/data/com.test.thalitest/files/www/jxcore/node_modules/node-ssdp/lib/server.js:75:3''

**Comment by andrew-aladev** [comment]
I've found that `testUtils.toggleWiFi` is not reliable.

**Comment by andrew-aladev** [comment]
I've commented the line `assert.notEqual(this._adLoopInterval, null, 'Attempting to clear a non-existing interval')` and both clients succeeded with test.

**Comment by yaronyg** [comment]
Andrew wants to put in some debug into the SSDP library so we can understand it and then we will close this bug in favor of thaliproject/Thali_CordovaPlugin#1345

**Comment by andrew-aladev** [comment]
We need to stub logs with `console`

```
    ['trace', 'debug', 'info', 'warn', 'error', 'fatal'].forEach(function (level) {
      stubs[level] = function () { 
        console.log.apply(console.log, arguments);
      }
    })
```
