### ISSUE TITLE
Do we fire an event from Android if we gain/lose access to WiFi?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1303]
We should fire a network changed event anytime Wifi's status changes, that includes, a change in SSID as well as going from having a connected endpoint to not having a connected endpoint. Do we actually do that?

We should probably have a native test for this (honestly it should be node based but we are tight on resources right now) and that probably means some ability to turn off wifi so we can test that we properly notify node when wifi goes away and comes back.

**Comment by vasilevskayaem** [comment]
We fires network changed events in org.thaliproject.p2p.btconnectorlib.internal.wifi.WifiDirectManager 
org.thaliproject.p2p.btconnectorlib.internal.wifi.WifiDirectManager#WifiStateListener

and also there are connectivity tests in ConnectivityMonitorTest.class.

And I see in logs that thaliMobileNativeWrapper.js receive events 'networkChanged: {"bluetoothLowEnergy":"on","bluetooth":"on","wifi":"off","cellular":"doNotCare"}'

**Comment by yaronyg** [comment]
Please make sure we return BSSID as defined in thaliMobileNative.js for networkChanged and please also add to that structure a field called 'SSID' where you also return the SSID. Any time the BSSID or SSID changes we need to fire a new networkChanged event.

**Comment by vasilevskayaem** [comment]
https://github.com/thaliproject/Thali_CordovaPlugin/pull/1320
