### ISSUE TITLE
FAILURE: Build failed with an exception. - thaliartifactory.cloudapp.net not  found

### ISSUE THREAD

**Issue by udlive** [thaliproject/Thali_CordovaPlugin#131]
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':Android:compile'.
> Could not resolve com.msopentech.thali:ThaliUtilitiesUniversal:null.
  Required by:
      thali-addressbook-master:Android:unspecified
   > java.lang.NullPointerException (no error message)
   > Could not GET 'http://thaliartifactory.cloudapp.net/artifactory/libs-snapsh
ot/com/msopentech/thali/ThaliUtilitiesUniversal/null/ThaliUtilitiesUniversal-nul
l.pom'.
      > thaliartifactory.cloudapp.net
   > Could not GET 'http://thaliartifactory.cloudapp.net/artifactory/libs-releas
e/com/msopentech/thali/ThaliUtilitiesUniversal/null/ThaliUtilitiesUniversal-null
.pom'.
      > thaliartifactory.cloudapp.net

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Am building the Address-book sample on Windows, and it fails  due to:
thaliartifactory.cloudapp.net -- not found
I checked and found its down.

Kindly help me link this libs
Thank you

**Comment by yaronyg** [comment]
I apologize but that address-book app is from an ancient and now abandoned code base. I just updated the readme to make it clear that it isn't active anymore. If you want to try out Thali grab two iPhones or two Android phones and head over to https://github.com/thaliproject/postcardapp
