### ISSUE TITLE
Implement new WiFi functionality in Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1317]
Implement the functionality in thaliproject/Thali_CordovaPlugin#1315. That is, returning SSID and enabling Wifi to turn on and off.

**Comment by evabishchevich** [comment]
Need changes thaliproject/Thali_CordovaPlugin#1316 to check it

**Comment by yaronyg** [comment]
@evabishchevich Isn't this done?

**Comment by evabishchevich** [comment]
@yaronyg It's done. Need to merge and test with thaliproject/Thali_CordovaPlugin#1368

**Comment by evabishchevich** [comment]
PR thaliproject/Thali_CordovaPlugin#1547
