### ISSUE TITLE
Implement new Wifi functionality for iOS

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1318]
This is to implement the new functionality in #1315. According to http://stackoverflow.com/questions/31555640/how-to-get-wifi-ssid-in-ios9-after-captivenetwork-is-depracted-and-calls-for-wif (look at the second answer) it seems like the old capitve network APIs are working so in theory we should be able to just grab the SSID and BSSID as required in 1315.

Also when the interface to change Wifi's state is called you just need to make sure you return the specified error.

**Comment by dersim-davaod** [comment]
PR #1324 is out.
