### ISSUE TITLE
Test if we are losing events sent from Android to node

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1327]
Apparently we have had a problem where Android would send peerAvailabilityChanged events to node but node didn't appear to ever receive the event. Our solution to this problem was to beat node into an unconscious bloody pulp with events in order to make sure it got them. No, that isn't the right solution.

So what we need to do is to write a simple test where Android fires a fixed number of events at Node and Node counts how many events it receives and fires off a log when it hits the expected number.

So the Android code should check for a call to registerToNative for peerAvailabilityChanged and once it gets that call then it should start firing the events. And that way we guarantee there are no race conditions.

If it fails then send this bug and code to @enricogior. If it passes then disable the code that was preventing us from sending repeated events about the same peer ID and generation. Then please confirm that we are no longer pummeling node. And then please re-run all the Native and Both mode tests on 3 Android devices locally and put the results into bug thaliproject/Thali_CordovaPlugin#1291

**Comment by larryonoff** [comment]
@yaronyg see some details about our work for this issue below.

@andrew-aladev and @vasilevskayaem tested the case, i.e. Android fired 1000 `peerAvailabilityChanged` events per 1 millisecond. As result 1000 events were send and 1000 events were received.

We assume that the current testing scenario is too simple. We need better simulate real Thali logic, i.e. when `peerAvailabilityChanged` event received attempt connecting to the peer. I think we already have test for the similar case.

**Comment by vasilevskayaem** [comment]
recommented generation check logic and get next results

fails 

check latest peer discovery https://gist.github.com/vasilevskayaem/72c76636da74871513665d526f8cf4f1

wifi peer is marked unavailable if announcements stop

Test updating advertising and parallel data transfer

Test write

initial peer discovery

update peer discovery 1

**Comment by yaronyg** [comment]
Handing this off to @evabishchevich to see which failures he can blame on Android and which he can blame on Node. :) @evabishchevich feel free to either use @vasilevskayaem's logs or to re-run the tests yourself just so you know everything about the history of those logs.

**Comment by yaronyg** [comment]
Closing in favor of thaliproject/Thali_CordovaPlugin#1291
