### ISSUE TITLE
jx npm run test-coordinated doesn't return error when tests fail

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1350]

**Comment by yaronyg** [comment]
When we use 'jx npm run test-coordinated' on desktop to run tests and if one or more tests fail the system just happily prints out the results (e.g. the number of passed and failed tests) and then continues. It doesn't return an error so the build.sh script doesn't stop on the error and we pass builds that have failing tests! Please fix!

**Comment by larryonoff** [comment]
@yaronyg we're unable to reproduce this issue. We tried just failing some test or throwing exception in some test, in both cases `build.sh` stops it's work.

**Comment by yaronyg** [comment]
The cause of the failures was that we had effectively a timer that ran long after the original test completed and when that timer ran it would call t.end() from the completed test. This would trigger a 'not ok' error from Tape who recognized that we were calling t.end() twice (the first time when the test successfully completed and the second time due to the timer that wasn't stopped when the test ended). This even resulted in some tests failing (which ever random test happened to be running when the timer went off) and returning failure to the coordinator but build.sh didn't exit.

The reason for this is that we apparently only fail build.sh if we catch the failure while the test is running. But in this scenario it doesn't cause an exception or other error but we do see that the failed test count is greater than 0.

So it looks like we need to put in a final check that if the failed count is greater than 0 that we return a failed result.

**Comment by yaronyg** [comment]
I just got this when running tests on the iOS branch:

```

not ok 646 test exited without ending
  ---
    operator: fail
  ...

not ok 647 test exited without ending
  ---
    operator: fail
  ...

not ok 648 test exited without ending
  ---
    operator: fail

  ...

not ok 649 test exited without ending
  ---
    operator: fail
  ...

not ok 650 test exited without ending
  ---
    operator: fail
  ...

not ok 651 test exited without ending
  ---
    operator: fail
  ...

not ok 652 test exited without ending

  ---
    operator: fail
  ...

not ok 653 test exited without ending
  ---
    operator: fail

  ...

not ok 654 test exited without ending
  ---
    operator: fail
  ...

not ok 655 test exited without ending

  ---
    operator: fail
  ...

not ok 656 test exited without ending
  ---
    operator: fail
  ...


1..656
# tests 656
# pass  78

# fail  578



Exit code: 1. Exit signal: null
Running in macOS
```

In other words, we had 578 failed tests and a 1 exit code but the script wasn't sent a failure!

**Comment by yaronyg** [comment]
Here's another fun one that 'passed' build.sh

ok 88 should be equal
ok 89 should be equal

ok 88 should be equal
ok 89 should be equal
ok 90 should be equal
ok 91 should be equal

ok 90 should be equal
ok 91 should be equal
ok 92 should be equal
ok 93 should be equal

ok 91 should be equal
ok 92 should be equal
ok 93 should be equal

ok 92 should be equal
ok 93 should be equal

dyld: lazy symbol binding failed: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /Users/yarongoland/Desktop/depots/Thali_CordovaPlugin/test/www/jxcore/node_modules/leveldown/build/Release/leveldown.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /Users/yarongoland/Desktop/depots/Thali_CordovaPlugin/test/www/jxcore/node_modules/leveldown/build/Release/leveldown.node
  Expected in: dynamic lookup


dyld: lazy symbol binding failed: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /Users/yarongoland/Desktop/depots/Thali_CordovaPlugin/test/www/jxcore/node_modules/leveldown/build/Release/leveldown.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /Users/yarongoland/Desktop/depots/Thali_CordovaPlugin/test/www/jxcore/node_modules/leveldown/build/Release/leveldown.node
  Expected in: dynamic lookup


dyld: lazy symbol binding failed: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /Users/yarongoland/Desktop/depots/Thali_CordovaPlugin/test/www/jxcore/node_modules/leveldown/build/Release/leveldown.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /Users/yarongoland/Desktop/depots/Thali_CordovaPlugin/test/www/jxcore/node_modules/leveldown/build/Release/leveldown.node
  Expected in: dynamic lookup


Exit code: null. Exit signal: SIGTRAP
Exit code: null. Exit signal: SIGTRAP
Exit code: null. Exit signal: SIGTRAP
