### ISSUE TITLE
Need to investigate the implications of BLE power mode for battery consumption

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1362]
How does our power consumption change when we change the BLE power levels. Go write an item with details.

**Comment by vasilevskayaem** [comment]
in table discharge rate per hour

BLE Scan Mode | test with empty scan result | test with one more advertising phone
------------ | ------------- | ------------- 
SCAN_MODE_LOW_LATENCY | 2.79%| 3.25%
SCAN_MODE_BALANCED | 2.60% |3.04%
SCAN_MODE_LOW_POWER |2.07% |2.75%
SCAN_MODE_OPPORTUNISTIC|1.10% |

SCAN_MODE_OPPORTUNISTIC not appropriate for us, with this settings app doesn't call onScanResult or onBatchScanResult methods

**Comment by yaronyg** [comment]
The key point is that SCAN_MODE_OPPORTUNISTIC with reportDelay != 0 is a waste of time. From what we can see we NEVER get a notification at all. So if we use SCAN_MODE_OPPORTUNISTIC we MUST use reportDelay = 0.
