### ISSUE TITLE
Test "#startUpdateAdvertisingAndListening - ending remote peers connection kills the local connection" failed and 'destroy remote peers connection kills the local connection'

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1374]
Mode : NATIVE
branch : master_1327
commit : 5fa2c6495ef7af136bd528d89f9516f5a0b5a023

Logs
6p - https://gist.github.com/evabishchevich/eb32c7f410234e544d0b716769458f24
6p - https://gist.github.com/evabishchevich/4ee45c3866cb212ac7799207071b5d12
s7 - https://gist.github.com/evabishchevich/ab71e4b7f553522488090500f818a5de

**Comment by evabishchevich** [comment]
server
https://gist.github.com/evabishchevich/1502652e436a4d864ec68610d9d0e68a

**Comment by evabishchevich** [comment]
We try to reconnect after closing connection in https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/test/www/jxcore/bv_tests/testThaliMobileNative.js#L830.
It was written to be sure that the port is really free, not just we stopped listen on that port.
We have only 1 try to connect but we can got some errors which are not connected with the fact that port isn't free. It can be just Bluetooth issue. So, there is two possible ways to solve it:
1. Increase count of reconnections
2. Think about the fact that it can be enough just to release listener and not to do 2nd connect at all

**Comment by evabishchevich** [comment]
https://gist.github.com/evabishchevich/ec887e0589fe336637bbdf7c83f97efa

**Comment by evabishchevich** [comment]
After supposed fix for thaliproject/Thali_CordovaPlugin_BtLibrary#90 
6p - https://gist.github.com/evabishchevich/583340043148f4f647ff4a4d867908c2
6p - https://gist.github.com/evabishchevich/8d063370ded3847fdf571d3584851373
s7 - https://gist.github.com/evabishchevich/e043f9dae362726d2218738f32443e2c
server - https://gist.github.com/evabishchevich/e321c9f8c53037e9d952c8da6949ce57

**Comment by evabishchevich** [comment]
6p - https://gist.github.com/evabishchevich/3009e85e86e4b5c1a6d1f3497053ba8b
6p - https://gist.github.com/evabishchevich/f7233c228cde76eb975c2639797e089b
s7 - https://gist.github.com/evabishchevich/5903316af5699a82e1aa254bb12ce693

server - https://gist.github.com/evabishchevich/9ac29acf9c36671b53de86f752743df8

**Comment by evabishchevich** [comment]
After unsubscribing from peerAvailabilityChanged event
6p - https://gist.github.com/evabishchevich/08e7b710afc47029ada5120263ee1631
6p - https://gist.github.com/evabishchevich/0b340370d4c394c286a51adc1ad57eda
s7 - https://gist.github.com/evabishchevich/1294ce10a386b03572fbf24bf89caa60
server - https://gist.github.com/evabishchevich/65303ea5c1b95707710d56ed3c982e5a

**Comment by evabishchevich** [comment]
6p - https://gist.github.com/evabishchevich/b37af2dd0b8903fb67e396bcc2065ae2
6p - https://gist.github.com/evabishchevich/db592e3579952f6d0bb22132379ff783
s7 - https://gist.github.com/evabishchevich/db592e3579952f6d0bb22132379ff783
server - https://gist.github.com/evabishchevich/2c8b6f9db85575717e6de97cfb925458

**Comment by evabishchevich** [comment]
Looks like it connected with thaliproject/Thali_CordovaPlugin#1377 . We have to fix our behaviour with trying to connect to the same  peer but with different "state" byte. It should be fixed in ios branch where we separated address and generation

**Comment by yaronyg** [comment]
All the native discovery tests are just broken. They are based on the assumption that zombies don't exist but they do and on both iOS and Android. So we need to really rethink these tests.

**Comment by andrew-aladev** [comment]
I've fixed our tests. But we have about 2% chance to receive a test timeout if bluetooth will go to sleep. This is related with issue that @evabishchevich is working on.
