### ISSUE TITLE
WiFi based mock is not reliable

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1403]
WiFi based native mock has several issues when running tests in **NATIVE** mode.
1. "can get data from all participants" test fails randomly (and it looks like it have never failed on devices) - [logs](https://gist.githubusercontent.com/chapko/b26291a411421b6dfac5646dedb4754c/raw/bfdbdebcf06610284cf2f2f8ba4f1099470f1994/can%2520get%2520data%2520from%2520all%2520participants.log)
2. It tends to run into recursive reconnects and either stops after some timeout or never stops. Easy reproducible with 'test write' tests - [logs (first 2000 of 922000+ lines)](https://gist.githubusercontent.com/chapko/b26291a411421b6dfac5646dedb4754c/raw/b32986362af65a5477bb86490149a1d725f2cb0f/test%2520write.log)

Tested on `master` branch, commits 487aa107707b05849ad07779e6154051161664d0 and 09583e3cc16629b2f4c3fa453e6877514680c593

**Comment by chapko** [comment]
Some interesting error messages on desktop

```
2016-10-21 16:11:35 - DEBUG thaliReplicationPeerAction: 'Got error on replication -  500 140281374451520:error:1408E0F4:SSL routines:SSL3_GET_MESSAGE:unexpected message:../deps/openssl/openssl/ssl/s3_both.c:477:
'

2016-10-21 16:11:35 - ERROR testUtils: 'Got an err -  Error: 140281374451520:error:1408E0F4:SSL routines:SSL3_GET_MESSAGE:unexpected message:../deps/openssl/openssl/ssl/s3_both.c:477:
'
```

jx v0.3.1.5 on Google V8 v3.14.5.9

**Comment by yaronyg** [comment]
@chapko The ssl error is on v8 which unfortunately means we can't rely on it. :( But the other errors need to be investigated. I'll try to look at this but right now I have to figure out what's going on with our native code on Android.

**Comment by yaronyg** [comment]
@chapko So the problem with 'can get data from all participants' isn't actually a bug in the mock.If anything it's a bug in the wifi based layer. The issue are the zombies we get from SSDP. I'm submitting a fix for that.

I'll need to investigate the second issue above.

**Comment by chapko** [comment]
@yaronyg yes you are right about 'can get data from all participants'. The problem is that the `NON_TCP_PEER_UNAVAILABILITY_THRESHOLD` is set to 500 via "proxyquired" thaliConfig. Advertising interval for ssdp is also set to 500. Now if we add network overhead it is possible to get next ssdp message only after let's say 505ms, while unavailability timeout will be fired after 501ms. That means we are going to get `peerAvailabilityChanged` event for the same peer twice during the test.

I have removed "proxyquired" thaliMobile in #1396 PR but for unrelated reason (see my comments there).

**Comment by vasilevskayaem** [comment]
results of test for data corruption

https://gist.github.com/vasilevskayaem/28d36fdf2e9729013da1f0c7671407d9
https://gist.github.com/vasilevskayaem/f99e0cfdb7e9f39c8aa2c1a6256f0148
https://gist.github.com/vasilevskayaem/f77e43063345912b9c2e6473df8858a1

**Comment by yaronyg** [comment]
@vasilevskayaem I really need raw logs!!! These logs are so filtered that I can't see what's going on at the Android level.Also I need the logs from the start of the test! I have hardened master_1403 so it should be able to handle zombies.
