### ISSUE TITLE
Replication stopped working on iOS WiFi mode

### ISSUE THREAD

**Issue by czyzm** [thaliproject/Thali_CordovaPlugin#1404]
I've played a lot with WiFi mode on iOS devices and it worked pretty fine. After some time after uninstalling and installing the same app (Stanton) again I am not able to run the Thali replication.
Here are the logs from 2 iOS devices:
https://gist.github.com/czyzm/a966377f15ae6e956ac3d21290dc3d54

Message from Thali54 sent at about 11:25:10 - not delivered to Thali56.

**Comment by larryonoff** [comment]
we assume that the issue has the same root as thaliproject/Thali_CordovaPlugin#1356

**Comment by yaronyg** [comment]
@czyzm The link above only appears to have the logs from one device. Where are the logs from the other device? In the log you gave us the messages at 11:25:10 came from the OTHER device. Messages from thaliManager prefixed with 'connected pskIdentity' are incoming, not outgoing messages. The log you shared shows that replication ended. But without seeing more of the log I can't see if replication started again.

Please update Stanton with the thaliPeerPoolOneAtATime.js file from master_1274_trivial and try to re-run the tests. That pool policy will both stop some of the worst behavior and it will provide some better logging on what actions are starting and stopping.

So please update, re-run and provide us with all the device logs and please let the logs run a few minutes past where the bad behavior occurred.

**Comment by czyzm** [comment]
@yaronyg There are logs from 2 devices (Thali54 and Thali56) and I am pretty sure that the message at 11:25:10 was sent from Thali54. I will repeat the test with new peer pool on Monday.

**Comment by czyzm** [comment]
I am not observing the issue any more right now.
I am using Thali_CordovaPlugin from master_1274_trivial (4962c39d13238748d4946fe04e1e2d90cffadc45) with merged installer fix from master_fix-install.
Closing issue.
