### ISSUE TITLE
On iOS changes done when Thali is OFF are not replicated after turning it ON

### ISSUE THREAD

**Issue by czyzm** [thaliproject/Thali_CordovaPlugin#1405]
We have following scenario on iOS:
1. Turn OFF Thali (stop ThaliManager).
2. Do some DB change.
3. Turn ON Thali (start ThaliManager).

The DB change is not replicated after turning Thali ON. However, when we do additional DB change when Thali is ON, this change and also the change done when Thali was OFF are correctly replicated.

Note that it doesn't happen on Android.

Unfortunately, I am not able to deliver logs now since I encountered other issue: #1404.

**Comment by larryonoff** [comment]
we assume that the issue has the same root as thaliproject/Thali_CordovaPlugin#1356

**Comment by czyzm** [comment]
I am not observing the issue any more right now.
I am using Thali_CordovaPlugin from master_1274_trivial (4962c39d13238748d4946fe04e1e2d90cffadc45) with merged installer fix from master_fix-install.
Closing issue.
