### ISSUE TITLE
Longevity testing

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1407]
We need to see how long we can run before we die. We need to do this with as few confounding factors as possible. So please go to https://github.com/czyzm/ThaliTestApp. But please use the thaliPeerPoolOneAtATime policy and set the phones to wifi only mode.

Test 1 - Please write a little bit of Node code to get each client to update itself automatically once a second for 1 minutes (e.g. 60 updates) and then to go completely quiet for 5 minutes and to then repeat. Each phone should check for the other phone's updates and if it doesn't get them within say 2 minutes of when expected then it should throw up some kind of alert. We want to keep the test running for at least 2 or 3 hours to see if we can run that long without any kind of issues.

The point of the active/non-active pattern is to emulate what happens when we use the phones for a demo. Put them down. Then grab them again.

Test 2 - If the previous test works out then we need to run the test again but this time turn Wifi off after say a minute into the 5 minute period and then turn it on at the end of the 5 minute period. This will test if we can start and restart authentication even when we lose wifi temporarily.

Test 3 - Now switch the phones to native only mode and return test 1.

Test 4 - Same as test 2 above but in native only mode and turn Bluetooth on and off. This is a much harsher test.

Test 5 - Same as test 1/3 except now we run in both mode.

Test 6 - Same as 2/4 except now we turn both wifi and Bluetooth on and off.

**Comment by andrew-aladev** [comment]
1-st test works perfect but only without `ThaliReplicationPeerAction.prototype._replicationTimer`

**Comment by andrew-aladev** [comment]
Today we've resolved that this test is not working because of limit of opened sockets. We are going to find the place where this sockets don't want to be closed.

**Comment by andrew-aladev** [comment]
If you want to run current app.js today, please do the following:

1. git clone Thali_CordovaPlugin branch master_yarong_1446-retries-fix
2. `cd Thali_CordovaPlugin && ./build.sh` (you can ignore tests)
3. git clone ThaliTestApp branch aaladev_1407
4. `cd ThaliTestApp && ./prepare.sh`

Than you can run our test on desktop. In this case you can do:

1. `cd ThaliTestApp/www/jxcore` on both machines.
1. copy `SSDP.js` from one machine into another.
2. run `jx runOnDesktop.js 1 wifi` (or `jx runOnDesktop.js 1 native`) on one machine.
3. run `jx runOnDesktop.js 2 wifi` (or `jx runOnDesktop.js 2 native`) on another.

You can run our test on mobile:

1. `cd ThaliTestApp`
2. use [this script](https://gist.github.com/andrew-aladev/5c23a79b273c3b3578a914abdd038060).

PS This is important for our test to clear latest application data. Our script does this.
