### ISSUE TITLE
Are we getting killed by Android?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1413]
In thaliproject/Thali_CordovaPlugin#1356 @andrew-aladev found in the logs:

...
DEBUG thaliManager: 'connected pskIdentity mdGBbQROMLxruFFD312U75hWHSVyZcNpbR6jr4JnO3I for path /db/testdb/_local/pIEo5gMc0PL3U21Hw5aHbw%3D%3D'
10-24 20:26:27.926  3473  4335 D GraphicsStats: Buffer count: 7
10-24 20:26:27.926  3473  4587 I WindowState: WIN DEATH: Window{2d2bf93 u0 d0 com.example.ThaliTestApp/com.example.ThaliTestApp.MainActivity}
10-24 20:26:27.926  3473  4107 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=122, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@d7ab383)

```

According to the powers that be WIN DEATH will kill our app completely. We need to understand why this happened and how we make sure it doesn't happen again if it's a problem.
```

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/49b2821ecdf7ff8dc945e6b76ccc878a

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/345e02dfb85e8ae74dd8f4e33012f793 can catch ANR only on native mode.

**Comment by evabishchevich** [comment]
stacktrace:
https://gist.github.com/evabishchevich/277be25ebcb76003e800c86f9372df5e
htc 10:
https://gist.github.com/evabishchevich/ae21e692cbdb56993ba73038f087a325

**Comment by evabishchevich** [comment]
Stacktrace:
https://gist.github.com/evabishchevich/faf6144439cda79f3c4dec41137178a1
Htc 10:
https://gist.github.com/evabishchevich/cba8784cd972303c525bd57775d55431

**Comment by evabishchevich** [comment]
We cal start on ConnectionHelper, inside that applySettings on BlePeerDiscoverer. In applySettings we call startAdvertiser. The system should notify us with onStartSucces when we've started advertisment. After that we call executeStartOperation -> updateBeaconAdExtra -> setBeaconAdExtra -> onAdvertiseScanSettingsChanged -> applySettings. In that applySettings we call startAdvertiser one more time and get lock on BlePeerDiscoverer. At the same time we get onStartSuccess on main thread, call setState() which get lock on BleAdvertiser. Inside setState we call onIsAdvertiserStartedChanged, updateState and wait for lock on BlePeerDiscoverer.  In our X thread we createAdvertiseData and want to call setAdvertiseData but waiting for the lock on BleAdvertiser

**Comment by evabishchevich** [comment]
NPE
https://gist.githubusercontent.com/evabishchevich/05eebe39cc6c7d18e9f9149c4845e68f/raw/cd02204c4dd3b2fa36407103f8f74bb901e7d502/gistfile1.txt

**Comment by evabishchevich** [comment]
CallbackContext is in org.apache.cordova, 
method sendPluginResult
https://gist.github.com/evabishchevich/4ce95cb685fd0b857eda65df9edf57d8

cordova 6.3.0

**Comment by evabishchevich** [comment]
https://gist.github.com/evabishchevich/c70d034b3923e406297a23cb3d197ce1

it fails on line 8

**Comment by chapko** [comment]
Coordinated tets log:

- [Nexus_6P (ENU7N15B26000497).log](https://gist.github.com/chapko/13944859b270d50ed39cbee7dd6fa00b/raw/ed5479a6ca2bfe23ea643d9756d2ab9921fe515f/Nexus_6P%2520(ENU7N15B26000497).log)
- [Nexus_6P (ENU7N16425000118).log](https://gist.github.com/chapko/13944859b270d50ed39cbee7dd6fa00b/raw/ed5479a6ca2bfe23ea643d9756d2ab9921fe515f/Nexus_6P%2520(ENU7N16425000118).log)
- [SM_G920F (02157df25c4c5739).log](https://gist.github.com/chapko/13944859b270d50ed39cbee7dd6fa00b/raw/ed5479a6ca2bfe23ea643d9756d2ab9921fe515f/SM_G920F%2520(02157df25c4c5739).log)

you can find `WIN DEATH` error in SM_G920F log

**Comment by yaronyg** [comment]
@enricogior - We are getting 139 seg faults. You can see this in the SM_G920F log above the following line:

10-31 18:10:21.501  3096  3096 I Zygote  : Process 17158 exited cleanly (139)

And yes we are process 17158. And yes we died with a seg fault. And no there doesn't seem to be any kind of stack. We just die. Instantly. We are seeing this quite often. @evabishchevich has a theory that this might have to do with a bug he has found in JXcore-Cordova where we sometimes get a null pointer exception, please see his comment above about 'it fails on line 8'. But that probably doesn't account for everything. What the heck is going on?

For now can you please figure out why JXcore's code for Cordova is ending up with a null pointer exception and please fix it?

**Comment by yaronyg** [comment]
@enricogior We have confirmed that this repo's on the S7s. So we have a serious crashing bug and no idea why. 

@chapko Can you please link the logs from the crashing S7s here.

**Comment by chapko** [comment]
S7 is SM_G930F:

- [Nexus_6P (ENU7N15B26000497).log](https://gist.github.com/chapko/719e5b7beab4e80e829547b44a91d3b2/raw/1b55309a065287262b3ac089936b19ab4e2cef22/Nexus_6P%2520(ENU7N15B26000497).log)
- [Nexus_6P (ENU7N16425000118).log](https://gist.github.com/chapko/719e5b7beab4e80e829547b44a91d3b2/raw/1b55309a065287262b3ac089936b19ab4e2cef22/Nexus_6P%2520(ENU7N16425000118).log)
- [server.log](https://gist.github.com/chapko/719e5b7beab4e80e829547b44a91d3b2/raw/1b55309a065287262b3ac089936b19ab4e2cef22/server.log)
- [SM_G930F (988667514534423146).log](https://gist.github.com/chapko/719e5b7beab4e80e829547b44a91d3b2/raw/1b55309a065287262b3ac089936b19ab4e2cef22/SM_G930F%2520(988667514534423146).log)

**Comment by yaronyg** [comment]
We had to change the signal handler which is not emitting a stack and when we remove the handler the crash goes away but it's not clear why.

**Comment by enricogior** [comment]
I can easily repro the issue using two Samsung phones and one Nexus. At a certain point the Nexus stops responding causing the two Samsung devices to raise a timeout error.
Right after the timeout error, jxcore receives a `signal 11` and exits causing the following `WIN DEATH` error.
When I use three Samsung devices, the test pass the critical point and the problem doesn't occur.

Next step: I removed, in jxcore, the signal handler for SIGSEGV and this is the result:
https://gist.github.com/enricogior/fb06de2defff03f3aeb2ab9934a290fc
same timeout error, but the ThaliTest app keeps running. 
If there was a SIGSEGV, the OS would have killed the app unless the app handled the SIGSEGV.
So that leaves us with two possibilities:
1) the SIGSEGV is caught and handled 'above' jxcore (i.e. jxcore-cordova, ThaliTest or Cordova itself).
2) the SIGSEGV was not raised by the OS and the jxcore signal handler is catching something generated by another application component such as libuv or SM.

So far I haven't been able to produce a call stack when the signal is caught by jxcore since the function that I use to do the stack unwind returns an empty stack.

**Comment by enricogior** [comment]
The SIGSEGV handler has been removed.
The code is currently in the 0.3.1.6 branch, I'll send the PR when all the validations for the new jxcoer/jxco-corova release are passed.
