### ISSUE TITLE
Swiftlint error in merging master into iOS branch

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1414]
When I try to merge master into iOS branch I'm getting a swiftlint error but the command line doesn't say what it is. I can't keep chewing on this today so I need y'all to investigate.

**Comment by yaronyg** [comment]
Note that I had everything passing as expected but the iOS build in the branch iOS_yarong_failed_merge

**Comment by baydet** [comment]
fix submitted thaliproject/Thali_CordovaPlugin#1419
