### ISSUE TITLE
Bluetooth battery tests

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1418]
Goal: We have two flavors of Bluetooth usage pattern. One flavor is beacon retrieval. In this flavor we make a connection, pull 1k-4k of data and close the connection. The other flavor is replication. Outside of chat applications this usually involves moving at least 100k - 1 meg of data. We want to understand if there is any meaningful battery consumption difference between them.

Test 1 - Beacon Test - Open a Bluetooth connection, move 1 K, close the Bluetooth connection, repeat. Keep doing this until we eat 1% of battery. Ideally advertising and listening (e.g. BLE) will be off as will wifi. So it's fine to hardcode the Bluetooth mac.

Test 2 - Replication Test - Same as above but move 1 meg of data.

**Comment by vasilevskayaem** [comment]
tested

on samsung 7

test | discharge rate 100->99% | discharge rate 99->98%
------------ | ------------- | -------------
move 1K | 4.13% | 4.61%
move 1M | 3.86% | 4.43 %

**Comment by yaronyg** [comment]
@vasilevskayaem When the table says 4.13% does it mean "If we moved 1K non-stop for an hour then we would eat 4.13% of the battery"?

**Comment by vasilevskayaem** [comment]
@yaronyg yes, but as you can see it can little bit be changed when we move from 100 to 99 and from 99 to 98
