### ISSUE TITLE
Cordova Run doesn't work on Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#143]
We need to figure out why cordova run won't work with us on Android

**Comment by obastemur** [comment]
Any error log ?

**Comment by yaronyg** [comment]
Nope. No error log. We turned on verbose logging and it produced nothing from Cordova. We will be investigating this in a bit. This bug was just to make sure we didn't forget.

**Comment by yaronyg** [comment]
Need to assign to Ville once he is hooked to our GitHub account

**Comment by yaronyg** [comment]
This is 3 days for Ville because he has to get used to using Stanton, figure out how we work with it and then figure out how to debug Cordova.
