### ISSUE TITLE
Why is the Bintray link not working?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1445]
When I try to build from master I get:

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find org.thaliproject.p2p.btconnectorlib:btconnectorlib2:0.3.5-alpha3.
     Searched in the following locations:
         https://repo1.maven.org/maven2/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.pom
         https://repo1.maven.org/maven2/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.aar
         https://jcenter.bintray.com/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.pom
         https://jcenter.bintray.com/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.aar
         file:/Users/yarongoland/.m2/repository/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.pom
         file:/Users/yarongoland/.m2/repository/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.aar
         https://bintray.com/artifact/download/thali/Thali/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.pom
         https://bintray.com/artifact/download/thali/Thali/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.aar
         file:/usr/local/Cellar/android-sdk/24.4.1_1/extras/android/m2repository/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.pom
         file:/usr/local/Cellar/android-sdk/24.4.1_1/extras/android/m2repository/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.aar
     Required by:
         :android:unspecified

I checked the build log in CI from the checkin that moved us to alpha3 and it clearly shows a successful download - https://raw.githubusercontent.com/ThaliTester/TestResults/912009767357579_Updated_BtLib_version_evabishchevich/build.md, search for btconnectorlib and you will find a download for https://bintray.com/artifact/download/thali/Thali/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.pom and another for https://bintray.com/artifact/download/thali/Thali/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.aar

But when I try those links myself they fail with a 404. And yes, I filed an issue with Bintray.

As a work around I copied the pom and aar from https://bintray.com/thali/Thali/btconnectorlib2/0.3.5-alpha3#files directly into ~/.m2/repository/org/thlaiproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.(pom | aar) but that didn't work for some reason I genuinely don't understand.

Why isn't bintray behaving itself?

**Comment by vasilevskayaem** [comment]
fixed wrong pom and aar file locations in bintray

https://bintray.com/artifact/download/thali/Thali/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.pom
   https://bintray.com/artifact/download/thali/Thali/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/btconnectorlib2-0.3.5-alpha3.aar
