### ISSUE TITLE
Proxyquire is dangerous!

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1447]
It's the end of the day, which is an awful time to file a bug. But I ran into something so strange that my brain isn't able to wrap it's head around it.

Head over to the master branch and jump into thaliMobile.js and shove in something like 'logger.error('THIS LINE SHOULD EXIST ONCE')' anywhere after you include logger.

Now run say the non-coordinated tests (because it's easier) and notice that you see that line twice.

One presumes the first time thaliMobile is loaded is at line 46 of runTests.js when we get the networkTypes.

The second time one presumes is on line 78 of runTests.js when we load testThaliMobile.js. (Look at the log for the non-coordinated tests and see where the 'THIS LINE SHOULD EXIST ONCE' prints out)

The problem appears to be proxyquire. If I remove proxyquire from testThaliMobile.js and instead just use a normal require then I don't get the two lines.

The reason this matters is that testThaliMobile.js does some static things like registering for events on thaliMobileNativeWrapper. So if 'thaliMobile.js' is executed twice then those static events occur twice! And I can see that this is actually happening. So we need to yank Proxyquire. :(

**Comment by chapko** [comment]
This is the exact reason I removed proxyquire in #1396. However besides producing very confusing logs it does not create any harm. But I absolutely agree to get rid of proxyquire where possible.

The more important problem is:
> ~~test~~ThaliMobile.js does some static things like registering for events on thaliMobileNativeWrapper

I believe we are not interested in these events in stopped state, so it makes sense to subscribe to them only in the `start` method.

**Comment by chapko** [comment]
I checked how many instances of every module we require during tests. Then I looked if modules, that have been require more than once, contain any side effect. The full results (:white_large_square: - file ignored, :white_check_mark: - no side effect, :x: - side effects):

- :white_large_square: mux/createNativeListener.js: 1
- :white_large_square: mux/createPeerListener.js: 1
- :white_check_mark: mux/thaliTcpServersManager.js: 2
- :white_large_square: notification/thaliNotificationAction.js: 1
- :white_large_square: notification/thaliNotificationBeacons.js: 1
- :white_large_square: notification/thaliNotificationClient.js: 1
- :white_check_mark: notification/thaliNotificationServer.js: 12
- :white_large_square: notification/thaliPeerDictionary.js: 1
- :white_large_square: notification/thaliPskMapCache.js: 1
- :white_large_square: replication/localSeqManager.js: 1
- :white_check_mark: replication/thaliPullReplicationFromNotification.js: 2
- :white_large_square: replication/thaliReplicationPeerAction.js: 1
- :white_check_mark: replication/thaliSendNotificationBasedOnReplication.js: 15
- :white_large_square: replication/utilities.js: 1
- :white_large_square: security/hkdf.js: 1
- :white_large_square: thaliPeerPool/thaliPeerAction.js: 1
- :white_large_square: thaliPeerPool/thaliPeerPoolDefault.js: 1
- :white_large_square: thaliPeerPool/thaliPeerPoolInterface.js: 1
- :white_large_square: utils/common.js: 1
- :white_large_square: utils/platform.js: 1
- :white_large_square: utils/pouchDBCheckpointsPlugin.js: 1
- :white_large_square: utils/pouchDBGenerator.js: 1
- :white_large_square: makeIntoCloseAllServer.js: 1
- :white_large_square: promiseQueue.js: 1
- :white_large_square: thaliConfig.js: 1
- :white_check_mark: thaliManager.js: 2
- :x: thaliMobile.js: 2-3 (2 for simple and 3 for coordinated)
- :white_large_square: thaliMobileNativeWrapper.js: 1
- :white_check_mark: thaliWifiInfrastructure.js: 2

Only thaliMobile may cause any problems by subscribing to initial events and I have already remove its proxyquired version from thaliMobile in  #1396.
