### ISSUE TITLE
Replication fails if we use attachments

### ISSUE THREAD

**Issue by czyzm** [thaliproject/Thali_CordovaPlugin#1449]
Not sure if this is Thali-related issue but want to put all information in one place.

Issue: When there is a change in DB on device A that contains attachments (not inline), the replication started on device B fails with error:
`thaliReplicationPeerAction: 'Got error on replication -  401 batch processing terminated with error'`
After that, no replication is done on device B. Changes from device B are still replicated to device A.

The issue has been reproduced using ThaliTestApp with following scenario:
1. Start ThaliTestApp on device A and on device B.
2. On both devices press "WiFi".
3. On device A press "Init Thali 1".
4. On device B press "Init Thali 2".
5. On both devices press "Start Thali".
6. On device A press "Add data" - data is replicated to device B.
7. On device B press "Add data" - data is replicated to device A.
8. On device A press "Add attachment" - data is not replicated any more. In logs of device B we can see the `401` error.
9. On device B press "Add attachment" - data is not replicated any more. In logs of device A we can see the `401` error.

Here are the logs:
[DeviceA](https://gist.github.com/czyzm/d2d76cce512ddc28272ad8437540ce91)
[DeviceB](https://gist.github.com/czyzm/d4a295e98698fd355ffb3698f3b5de25)

I tried to reproduce the same issue without Thali but was not able. I used simple script for that available here:
https://github.com/czyzm/Replication

**Comment by larryonoff** [comment]
@czyzm what is the size of file ?

**Comment by andrew-aladev** [comment]
Please use `process.env.DEBUG = "thalisalti:acl";` at the top of the `app.js` and you will see a good log from salti.

**Comment by yaronyg** [comment]
@andrew-aladev We need confirmation from Rockwell that they understand the issue and the fix before we close this bug. Thanks!

**Comment by czyzm** [comment]
Does it mean that the ThaliManager ACL i allowing just to have attachments with id "attachment"?
In Stanton we have multiple attachments assigned to single incident doc. Each attachment has its unique id ("attachment<unique_id>"). How can we handle this? I may miss something, @yaronyg @andrew-aladev can you clarify?

**Comment by andrew-aladev** [comment]
@czyzm, Ok, we will change salti to support both `docId` and `attachmentId`.

**Comment by larryonoff** [comment]
The issue was created, see thaliproject/Thali_CordovaPlugin#1460
