### ISSUE TITLE
migrate to swift 3

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#1462]

**Comment by baydet** [comment]
results in iOS_swift3_migration branch

**Comment by baydet** [comment]
@dersim-davaod, @yaronyg, @drinkius  swift 3 code is here

**Comment by baydet** [comment]
there is a separate notification for @larryonoff :)

**Comment by larryonoff** [comment]
Thanks! are going to create PR ?

**Comment by baydet** [comment]
@larryonoff, I think it will have sense only after we officially declare that we support iOS 10. Or do you want this PR just not to forget about this changes?

**Comment by larryonoff** [comment]
@baydet you're right. not to forget and start reviewing.
