### ISSUE TITLE
CI build fails

### ISSUE THREAD

**Issue by dersim-davaod** [thaliproject/Thali_CordovaPlugin#1463]
See example of log [here](https://github.com/ThaliTester/TestResults/blob/8962479653c8680_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/build.md).

**Comment by larryonoff** [comment]
We've found the following lines provided log:

```
Plugins: 

cordova-plugin-whitelist,ssdp-replacer-hook

Error retrieving Android platform information: 
Android SDK is not set up properly. Make sure that the Android SDK 'tools' and 'platform-tools' directories are in the PATH variable. 

Error: android: Command failed with exit code ENOENT
```

So we checked the PATH variable, as result it doesn't contain 'tools' folder in PATH variable that is mentioned in the error. I think we should try adding this variable into PATH, the value should be '/Users/thali/Library/Android/sdk/tools'.

**Comment by larryonoff** [comment]
We've found misspell of `app.js` in setUpTests.sh. So created PR thaliproject/Thali_CordovaPlugin#1465 with fix.

**Comment by larryonoff** [comment]
thaliproject/Thali_CordovaPlugin#1465 didn't fix the issue. So we need to update / fix CI first as I mentioned above.

@jareksl @mlesnic @czyzm please also run `rvm get head` before creating the new VM snapshot.
