### ISSUE TITLE
CI can't build

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1472]
Look at the logs in https://github.com/thaliproject/Thali_CordovaPlugin/pull/1471. 
Looks like CI doesn't have enough permissions for git.

**Comment by larryonoff** [comment]
@mlesnic @czyzm  Please check [article](http://stackoverflow.com/questions/1115854/how-to-resolve-error-bad-index-fatal-index-file-corrupt-when-using-git) for the repo in VM or just execute the following commands for snapshot.
```
rm -f .git/index
git reset
git remote prune origin
```
