### ISSUE TITLE
Pass to coordination server the number of active devices

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#148]
Just because we ask for X devices due to various problems there might only be Y devices available. So we need the CI framework to pass in to the coordination server the number of actual devices.

**Comment by obastemur** [comment]
Details are available from https://github.com/thaliproject/TestDummy 

I will update TestDummy repo (not today) with a sample ping-pong application (server and phones) Once the server receives the call from each phone, the test finishes.

**Comment by yaronyg** [comment]
Please integrate this into the coordination server. Remember that we now have to pass the actual number of devices to each of the individual devices as well.

**Comment by yaronyg** [comment]
This is two days mostly because Matt has never used the CI environment before.

**Comment by yaronyg** [comment]
Jukka, not Matt, did this. Jukka needs to test this and then we can close.

**Comment by yaronyg** [comment]
This isn't done yet because we aren't passing the numbers to the devices.

**Comment by DrJukka** [comment]
done according to spec. Count only used if honourCount is set to true.
