### ISSUE TITLE
The first sync takes quite long

### ISSUE THREAD

**Issue by larryonoff** [thaliproject/Thali_CordovaPlugin#1499]
## Summary

When data is added (e.g. chat message) the replication takes quite long (20-30 seconds). It seems that it is some kind of "startup" issue because adding data in 3 seconds interval replicates immediately but always the first replication after some inactivity period takes really long.

The issue can be reproduced on [ThaliTestApp](https://github.com/thaliproject/ThaliTestApp) (now in branch aaladev_1407).

## Environment

- Android
- Native mode

**Comment by larryonoff** [comment]
@andrew-aladev please take a quick look at this issue (1-2 hours).

**Comment by czyzm** [comment]
This issue can be seen in ThaliTestApp (b86048b82a9696db50826315afdd7b94d271b6ac) using Thali_CordovaPlugin from master (4159bd2f9d0eafbb82180b7c3be9ffdb5498bbdc). Just use native mode.

Issue is that sometimes that data replication takes really long time. I assume the replication itself is not started for some period of time.

Here are the logs from 2 S7 devices using ThaliTestApp:
[S7_1](https://gist.github.com/czyzm/9937e9f9dcd088a52c8f9d32ab37c247) 
[S7_2](https://gist.github.com/czyzm/d07b450815754e9e04ca913c17c8c34a) - from this device I am sending data

On S7_2 I am adding data at about 13:23:50 - this gets to the S7_1 quite fast (couple of seconds).
Next on S7_2 I am adding another data at about 13:24:03. Now it took about 25 seconds to get to S7_2.

**Comment by andrew-aladev** [comment]
Could not reproduce it today with nexus. It may be fixed yesterday.
