### ISSUE TITLE
Improve tests in TCPListener.swift and TCPClient.swift.

### ISSUE THREAD

**Issue by dersim-davaod** [thaliproject/Thali_CordovaPlugin#1503]
We can have error:
`XCTAssertNil failed: "ConnectionFailed" -  in file: Optional("/Users/thali/Github/ThaliTest/plugins/org.thaliproject.p2p/lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/TCPListenerTests.swift"), line: 341`

This is because of fail during attempt of creating listener socket.
To prevent such errors we can increase number of attempts from 1 to 5-10.

**Comment by asuhodolov** [comment]
PR https://github.com/thaliproject/thali-ios/pull/4

**Comment by asuhodolov** [comment]
PR https://github.com/thaliproject/thali-ios/pull/4
