### ISSUE TITLE
incomingConnectionToPortNumberFailed is never called by native layer on Android

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1507]
We discussed this today with @squid48 and @evabishchevich and turns out Android never calls `incomingConnectionToPortNumberFailed` callback. It means [this code](https://github.com/thaliproject/Thali_CordovaPlugin/blob/2be44b36e95abb655ea27ec7b4996b0e451eec8a/thali/NextGeneration/thaliMobileNativeWrapper.js#L1015-L1046) never executes. Is it outdated code or just a bug in native layer?

**Comment by yaronyg** [comment]
This is a bug in the native code. If we try to connect to the node layer to relay a Bluetooth server socket and the call fails then Android needs to emit this event so that the node layer has some idea that something has gone horribly wrong with the express server.

**Comment by evabishchevich** [comment]
PR thaliproject/Thali_CordovaPlugin#1541
