### ISSUE TITLE
CI error: name node_win_onecore is not defined while evaluating condition 'node_win_onecore==1' in leveldown-mobile/deps/leveldb/leveldb.gyp while loading dependencies of binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by larryonoff** [thaliproject/Thali_CordovaPlugin#1509]
This's very often error on CI. We need to have some final solution for this. Because we're having this issue very often, so build doesn't work.

See the [logs](https://github.com/ThaliTester/TestResults/blob/93306024bd573e9_DONT_MERGE_-_enable_validate_build_environment_script_larryonoff/build.md).

**Comment by larryonoff** [comment]
@enricogior maybe you can provide some recommendation how to setup CI properly to fix this issue. But for now we only made hacky solutions.

**Comment by larryonoff** [comment]
I've found some details here Level/leveldown-mobile#11.

**Comment by enricogior** [comment]
@larryonoff 
the fix that you linked is not currently in the branch used by JXcore, and I guess it's not in the module downloaded by the build process in Thali.

**Comment by larryonoff** [comment]
As a temporary solution we have to add variable `'node_win_onecore': 'false'` in `common.gypi` for 

- ~/.node-gyp/__{NODE-VERSION}__/include/node/common.gypi
- ~/.node-gyp/jxb311/common.gypi

It looks that this should be done each time when `node` and `jxcore` updated.

**Comment by enricogior** [comment]
Assigning the issue to Ilya, he has found that the error was happening when trying to compile leveldown-mobile using node's npm instead of jxcore.

**Comment by larryonoff** [comment]
Fixed in PR thaliproject/Thali_CordovaPlugin#1523. Waiting for PR review.
