### ISSUE TITLE
ThaliNotificationClient is broken after introducing peer generations

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1510]
## The problem

`ThaliNotificationClient` uses `PeerDictionary` to store peer actions, and peer states. This dictionary maps peer identifiers to corresponding peer entries. Previously (when generations didn't exist) notification client was not able to get peerAvailabilityChanged event twice from thaliMobile for the same peer id. Now it is possible when generation or address changes.

The problematic scenario:
1. Notification client gets peerAvailabilityChanged event for peer *f00* with generation 0.
2. Notification client creates notification action (lets call it *0-generation-action*), adds new entry into pool dictionary, and enqueues this action.
3. Peer pool manager eventually starts *0-generation-action*.
4. Notification client gets peerAvailabilityChanged event for peer *f00* with generation 1.
5. Notification client overrides peer dictionary entry for peer *f00* and enqueues *1-generation-action*.
6. *0-generation-action* is resolved.

At this point old peerDictionary entry for generation 0 peer is lost, but notification client was listening to the *0-generation-action* resolution and expects peerDictionary to contain peer entry for the 0-generation peer, not the new one.

## Solutions

I see several possible solutions for this issue

### 1. Change peerDictionary key
Use compound key (peerId + generation) for `peerDictionary`. Basically it means we don't change logic at all and handle same peers with different generations as different peers. And everything works as before.

### 2. Kill old actions in favor of new ones
There is `killSuperseded` method that does exactly this:
> ```
> /**
> * Used primarily by peer pool managers who have decided to kill this
> * notification action for a particular peerID on a particular connection
> * type in favor of a newer one.
> * ...
> */
> ```

### 3. Delegate decision to the peer pool manager.
We can treat such situations as conflicts and just make peer pool manager resolve them. We can even use the 2nd solution as a default conflict resolution algorithm if peer pool manager does not provide its own implementation.

**Comment by yaronyg** [comment]
The design goal was 3. We would just create the notification actions as we get discovery and it's up to the peer pool manager to decide what it wants to do.

**Comment by chapko** [comment]
I've just found #1382 that addresses the same problem and also describes possible race conditions. So we are going to stick to the 1st solution and update peer dictionary.

I'm closing this issue in favor of the older one.
