### ISSUE TITLE
Get perf tests for Android running in CI

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#152]

**Comment by yaronyg** [comment]
This is about making sure that we can run on as many Android devices as are available

**Comment by yaronyg** [comment]
10/19 Update - Still can't get all devices to appear in CI. Tomorrow we probably need to put in something that just tries to capture who we can and then runs the test. We should ignore the number of devices we are passed.

**Comment by yaronyg** [comment]
10/21 - We have seen it working but CI is down right now for an upgrade, he will have to fix and try again.

**Comment by yaronyg** [comment]
10/22 - We are seeing intermittent errors, mostly on build. But Jukka needs to update his version of my branch to get the latest.

**Comment by DrJukka** [comment]
We appear to have an issue on Socket.io communications. See test: https://raw.githubusercontent.com/ThaliTester/TestResults/480372503b8de6a_Test_juksilve_DrJukka/test_log.md

Basically when client is disconnected it logs "CoordinatorConnector disconnect called", and from the logs it can be seen that with all devices getting the disconnected event while running a test are getting "error","data":{"type":"TransportError","description":503}}

**Comment by yaronyg** [comment]
10/26 - Blocked on #222

**Comment by yaronyg** [comment]
10/27 - The implementation of this is #223

**Comment by yaronyg** [comment]
10/28 - Back to being blocked on #222, we thought we had resolved it, we were wrong.

**Comment by yaronyg** [comment]
10/30 - Was blocked for 20 hours when CI wasn't working.

**Comment by yaronyg** [comment]
10/3 - Started to implement sharing the bluetooth addresses, randomizing the address list on a device and round robin the list until they all pass or the test ends. Did some smoke tests on 3 deices and now trying 6. Should get local values today.

**Comment by yaronyg** [comment]
10/4 - We found a bug where we are sending to the wrong socket when we reconnect, which makes us wonder how this test every passed anywhere but somehow it did. In any case we now believe we are talking to the right socket. We are running a test now to see if that fixes things.

**Comment by DrJukka** [comment]
The framework appears to work now. There's run that is reported as success by CI:https://github.com/ThaliTester/TestResults/blob/4860079788277ed_Story_001_juksilve_DrJukka/test_log.md
