### ISSUE TITLE
We need to understand MPCF behavior when we lose a peer

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1526]
Scenario:
Time 0 - Device A gets a notification from MPCF that Device B has been discovered
Time 1 - Device A attempts to create a MCSession with Device B and the attempt fails (because Device B suddenly disappeared)

Question:
What happens next? Especially what happens if at Time 2 Device B re-appears

Will the MPCF issue a peer unavailable notification in this scenario?
If the peer comes back advertising the exact same information (e.g. the MCNearbyServiceAdvertiser on Device B is still advertising the same MCPeerID/discoveryInfo/serviceType at time 2 as it was advertising at time 0) will MPCF issue a new peer found event?

We need you to actually simulate this scenario (I'm told that colanders act as reasonable Faraday cages you could use to make device B disappear right after it is discovered) and see exactly what the MPCF does. Once we know that we know what we need to do in Node land to manage it.

**Comment by yaronyg** [comment]
@dersim-davaod Please put in a write up of what you found and then please close this bug.

**Comment by dersim-davaod** [comment]
If `MCSession` fails due to disappearing remote peer, we're sending `peerAvailabilityChange` event.

But we're not sending `peerAvailabilityChange` event when `MCSession` failed on its own and browser did not lose the remote peer.
