### ISSUE TITLE
Change tests like "network changes emitted correctly", "network changes not emitted in started state" and "calls correct starts when network changes" in thaliMobileTest

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1530]
The logic we use to talk to the coordination server doesn't seem to handle the case where we turn off and then turn wifi back on. The reconnection logic doesn't figure out that wifi is back. So we have to fix that before we can run these tests.

**Comment by andrew-aladev** [comment]
We need to work around `ENETUNREACH` error. Our coordination client wants not to receive this error.

**Comment by vasilevskayaem** [comment]
https://gist.github.com/vasilevskayaem/a551cec8ee4771ca44e7e1622d3c9a50
