### ISSUE TITLE
Tests '#update - do we cancel timer properly on an immediate?' and '#update - test that we pick up new sequences while we wait' are failing

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1531]
CI logs: https://raw.githubusercontent.com/ThaliTester/TestResults/93780272836a139_Convert_space_indentation_in_the_project_and_clean_up_the_code_dersim-davaod/build.md

Test failed in native mode on android mock.

**Comment by chapko** [comment]
Right now this test almost always fails on iOS devices in every mode (WiFi and Native)

**Comment by chapko** [comment]
It looks like 1 second for `maximumUpdateInterval` is not enough for iOS devices. Setting it to larger value in the test makes it pass.

**Comment by chapko** [comment]
The same applies to the *'#update - test that we pick up new sequences while we wait'* test

**Comment by yaronyg** [comment]
If this test is failing in master on iOS wifi then we can fix it after we merge the iOS branch to master. But if it is not failing in master on iOS wifi then this is a blocker to moving iOS branch to master.

**Comment by chapko** [comment]
I reproduced this bug in `master` branch

**Comment by chapko** [comment]
I've adjusted timers in the tests to make them pass. Performance issue is discussed in #1618
