### ISSUE TITLE
Setup perf tests so we can run Android and iOS side by side in CI

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#154]
The work item here is that we now need the coordinator server manage iOS and Android device counts separately. So the server knows there are X android devices and Y iOS devices and each of the devices when it talks to the coordination server has to identify itself and the coordination server has to manage the X and Y counts separately.

**Comment by yaronyg** [comment]
We think this works but won't know for sure until the CI platform is running.

**Comment by yaronyg** [comment]
This has been implemented but hasn't been verified because CI don't work yet.

**Comment by yaronyg** [comment]
10/26 - The code exists but can't be confirmed until #222 is resolved.

**Comment by DrJukka** [comment]
re-formatted the index.js to be more compact & nicer code. Still unverified how these are working together though
