### ISSUE TITLE
Segmentation fault (SIGSEGV) while running desktop coordinated tests

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1543]
Happened on CI (jx v0.3.1.6).
Bot comment: [link](https://github.com/thaliproject/Thali_CordovaPlugin/pull/1505#issuecomment-261929915)
Commit: 4b202740bec64349f175fcfd1684ad7cbd7b0789
Log: [build.md](https://raw.githubusercontent.com/ThaliTester/TestResults/931424424b20274__897_implemented_1__3__4__5_tasks_squid48/build.md)

```
2016-11-21 12:56:05 - DEBUG UnitTestFramework: '#run: 'Do something and make sure we time out''

[32m2016-11-21 12:56:05 - DEBUG thaliReplicationPeerAction: 'Replication resumed'
[39m
[33m2016-11-21 12:56:05 - DEBUG thaliReplicationPeerAction: 'Replication resumed'
[39m
[36m2016-11-21 12:56:05 - DEBUG thaliReplicationPeerAction: 'Replication resumed'
[39m
[33mExit code: null. Exit signal: SIGSEGV[39m
2016-11-21 12:56:05 - INFO HttpServer: 'Socket to device name: 'eaacda55-280b-47b6-9547-2735bf956ada' disconnected, reason: 'transport close''
```

**Comment by evabishchevich** [comment]
More logs:
https://raw.githubusercontent.com/ThaliTester/TestResults/9124345447e35d1_added_logs_vasilevskayaem/build.md

**Comment by enricogior** [comment]
Recently we have fixed several crashing bugs in JXcore, we don't know if this crash was one of those, but we haven't seen crashing bugs running the desktop tests using the latest release. Closing the issue for now.
