### ISSUE TITLE
Confirm that we never 'undiscovery' a device on Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#155]
This is a hack until we switch from wi-fi direct to BLE on Android. Once we discover a device we will never see it go away in order to make demos work. We need a test to make sure this is working correctly.

**Comment by yaronyg** [comment]
Just do this as a one time manual test.

**Comment by DrJukka** [comment]
Confirmed.
I did create a quick test app which with I can see which devices are reported to be currently available.

Then I run the app with 6 devices, and then after devices had discovered others, I shut down 4 of the devices.

And checked after 1.5 hours that the two remaining devices still reported showed all 5 devices being available.
