### ISSUE TITLE
Test file transfer speed for Multipeer Connectivity framework in iOS

### ISSUE THREAD

**Issue by drinkius** [thaliproject/Thali_CordovaPlugin#1562]

**Comment by drinkius** [comment]
## Photos transfer

### Environment

- iPhone 6s - iOS 10.1.1 (Host)
- iPhone 5 - iOS 10.1.1 (Client)
- Unchanged version of [**iOS Selfie Share app**](https://github.com/adamgoth/ios-selfie-share)

### Results
Initial tests show disturbing results - data transfer with plain reliable data send methods works with considerable delays - cropped basic screenshots being send from a 6s device to a 5 one take around 7-15s time to appear on the receiver end over Bluetooth (with Wi-FI switched off completely). If Wi-Fi is turned on - it takes up to 17-30s for the image transfer (2s delay noticed only a couple of times, can't find any pattern to faster transfers). 

Need to investigate the reasons for speed drop for seemingly faster Wi-Fi channel

**Comment by yaronyg** [comment]
# Reproducibility

We need a native application that is stored in https://www.github/thaliproject that has this code so we can build and reproduce these tests at will.

# Discovery Latency

Each device in the test both starts advertising and starts listening. From the time we start listening measure how long it takes to find the other devices in the test. Publish an average of those 'first to discover' times.

These tests need to be run with 2, 3 and ideally 4 devices.

The tests need to be run in the following configurations:
1. Bluetooth On/Wifi On/All devices not connected to a Wifi Access Point
2. Bluetooth On/Wifi On/All devices connected to a Wifi Access Point
3. Bluetooth On/Wifi On/1/2 devices on a Wifi Access Point and 1/2 not

Note that we are not going to test the mixed Bluetooth On/Wifi Off or Bluetooth Off/Wifi On cases as for now we explicitly do not support that configuration. We require both to be on to work. This requirement is driven by our desire to reduce our support matrix.

# Bandwidth

There are several different flavors of bandwidth test we need.

## Max Simplex Speed
This test tells us what our maximum transfer bandwidth is in one direction.

In this test we have exactly two devices. One device will send a fixed amount of data to the other device. The data should be at least 1 meg worth. The receiving device will then send 1 byte to confirm when it has received all the data.

The actual logic is slightly tricky.

Logic for sending device:
1. Discover receiving device
2. Start timer
3. Send session invite
4. Open outgoing stream
5. Start sending data on outgoing stream
6. If the connection fails while sending the data, then recreate it. If the session fails while sending the data, then recreate it.
7. Receive incoming stream (which could have happened anytime after step 3). If the stream fails for any reason accept any new incoming streams.
8. Only once the confirmation byte is received on the incoming stream is the timer stopped and the result printed

Logic for receiving device:
1. Start advertising
2. Accept invite
3. Accept incoming stream and immediately open an outgoing stream to the other device
4. Accept data from incoming stream and count the number of bytes received.
5. If the incoming stream or even the whole session dies then just accept any subsequent invite or stream. But the byte counter shouldn't be reset. Once the new session/stream is received then the counter should just keep counting.
6. If the outgoing stream fails for any reason then recreate it. If the whole session fails then wait until a new session is created before recreating the output stream.
7. Once the target amount of data is received then send the success byte.

## Max Duplex Speed
Same as previous except each of the two devices is sending data to each other. So both devices are simultaneously a sender and receiver. Each one will publish its timer value as a sender. Publish both results.

## Multiparty Max Duplex Speed
Same as Max Duplex Speed Test but now run with 3 and 4 devices to see how perf is affected with multiple devices.

## Configurations for previous bandwidth tests
Same as with discovery latency. We need to run all the tests in the 3 configurations. So this means we would theoretically run (Max Simplex Speed + Max Duplex Speed(2, 3 & 4 devices))*3 configs = 12 tests.

No, we really don't have to run all of them. Use your best guesses as to which configurations have something useful to say.

# Latency
The point of these test is to find out 'time to first byte'. These tests are identical to the bandwidth test except we are sending and receiving exactly one byte. The point is to measure how long it takes in the 12 configurations discussed above to send an invite, get an accept, open a stream, send one byte, receive back a stream and receive back a byte.

The logic is that the receiver receives one byte and immediately responds with a byte.

**Comment by drinkius** [comment]
Created a repo for tests: [MPCF-Bandwidth-Test-App](https://github.com/thaliproject/MPCF-Bandwidth-Test-App)

**Comment by yaronyg** [comment]
This should be done by tomorrow and we can start testing.

**Comment by yaronyg** [comment]
Tests will start after the call.

**Comment by drinkius** [comment]
Faced problems with data streams yesterday, fixed now, all is OK, testing in progress

**Comment by yaronyg** [comment]
There is an error in the time calculations.

**Comment by drinkius** [comment]
## Bandwidth, 1 MB data, excluding connection & open stream time

### Environment

- iPhone 6s - iOS 10.1.1 (Host)
- iPhone 6s - iOS 10.1.1 (Client)
- [**MPCF Bandwidth Test App**](https://github.com/thaliproject/MPCF-Bandwidth-Test-App), commit 07c0447

### Results
In execution of this test I realised that the results are very dependent on the time when the actual sendData trigger happens, something under the hood of MPC framework seems to slow down the speed in the first seconds after the connection is established and after the stream is opened. If you wait a bit longer - the speed happens to increase, although I didn’t yet get persistent results yet.

#### WiFi - no Access Point; BT - on
Average speed: (0.476 + 0.656 + 1.258 + 1.030 + 2.509) / 5 = 1,1858 MB/s
#### WiFi - same Access Point; BT - on
Average speed: (1.454 + 1.437 + 2.190 + 1.521 + 1.194) / 5 = 1,5592 MB/s
#### WiFi - 1 device on AP, other - not; BT - on
Average speed: (1.081 + 2.897 + 1.417 + 1.090 + 1.191) / 5 = 1,5352 MB/s


#### A little extra: WiFi - off, BT - on
Average speed: (0.099 + 0.100 + 0.099 + 0.101 +  0.099) / 5 = 0,0996 MB/s

**Comment by drinkius** [comment]
Issues with opening second stream in parallel MCSession, tests will be performed after the fix, the rest of the functionality is ready

**Comment by dersim-davaod** [comment]
Fixed and updated Alex's code.
Starting testing.

**Comment by yaronyg** [comment]
Dersim will add his investigation results.

**Comment by dersim-davaod** [comment]
**Max simplex speed**
As above these results are for what happens after we have done discovery and connected. So this is the speed once we are all set up.

**Bluetooth On/Wifi On/All devices not connected to a Wifi Access Point**
WiFi - no Access Point; BT - on; 2 devices - 11.892 Mbits/s
WiFi - no Access Point; BT - on; 3 devices - 5.248 Mbits/s
WiFi - no Access Point; BT - on; 4 devices - 3.383 Mbits/s

**Bluetooth On/Wifi On/All devices connected to a Wifi Access Point**
WiFi - same Access Point; BT - on; 2 devices - 13.734 Mbits/s
WiFi - same Access Point; BT - on; 3 devices - 11.218 Mbits/s
WiFi - same Access Point; BT - on; 4 devices - 9.699 Mbits/s

**Bluetooth On/Wifi On/1/2 devices on a Wifi Access Point and 1/2 not**
WiFi - half of devices on the same AP; BT - on; 2 devices - 10.280 Mbits/s
WiFi - half of devices on the same AP; BT - on; 3 devices - 7.410 Mbits/s
WiFi - half of devices on the same AP; BT - on; 4 devices - 3.605 Mbits/s

**Comment by yaronyg** [comment]
@dersim-davaod This item isn't actually done. Check the top. Y'all just ran the first test. There are a bunch more.

**Comment by dersim-davaod** [comment]
**Max duplex speed**
As above these results are for what happens after we have done discovery and connected. So this is the speed once we are all set up.

**Bluetooth On/Wifi On/All devices not connected to a Wifi Access Point**
WiFi - no Access Point; BT - on; 2 devices - 8.555 Mbits/s
WiFi - no Access Point; BT - on; 3 devices - 5.190 Mbits/s
WiFi - no Access Point; BT - on; 4 devices - 4.683 Mbits/s

**Bluetooth On/Wifi On/All devices connected to a Wifi Access Point**
WiFi - same Access Point; BT - on; 2 devices - 11.274 Mbits/s
WiFi - same Access Point; BT - on; 3 devices - 11.818 Mbits/s
WiFi - same Access Point; BT - on; 4 devices - 8.368 Mbits/s

**Bluetooth On/Wifi On/1/2 devices on a Wifi Access Point and 1/2 not**
WiFi - half of devices on the same AP; BT - on; 2 devices - 13.185 Mbits/s
WiFi - half of devices on the same AP; BT - on; 3 devices - 4.274 Mbits/s
WiFi - half of devices on the same AP; BT - on; 4 devices - 3.035 Mbits/s



**Discovery Latency**

**Bluetooth On/Wifi On/All devices not connected to a Wifi Access Point**
WiFi - no Access Point; BT - on; 2 devices - 1.8s
WiFi - no Access Point; BT - on; 3 devices - 1.9s
WiFi - no Access Point; BT - on; 4 devices - 1.9s

**Bluetooth On/Wifi On/All devices connected to a Wifi Access Point**
WiFi - same Access Point; BT - on; 2 devices - 1.9s
WiFi - same Access Point; BT - on; 3 devices - 1.9s
WiFi - same Access Point; BT - on; 4 devices - 4.1s

**Bluetooth On/Wifi On/1/2 devices on a Wifi Access Point and 1/2 not**
WiFi - half of devices on the same AP; BT - on; 2 devices - 1.7s
WiFi - half of devices on the same AP; BT - on; 3 devices - 2.2s
WiFi - half of devices on the same AP; BT - on; 4 devices - 1.9s
