### ISSUE TITLE
Fix 4 native tests

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1572]
@chapko provided me with the following logs
https://gist.github.com/evabishchevich/5cd89abcd1cb08cd43ea292fa83a227d

**Comment by evabishchevich** [comment]
I've reproduced that once and can't reproduce for a long period of time

**Comment by evabishchevich** [comment]
PR thaliproject/Thali_CordovaPlugin#1576

**Comment by vasilevskayaem** [comment]
still fails on Nexus 6 https://gist.github.com/vasilevskayaem/7e2d6f5117e01130be7f5292d08ec254

**Comment by vasilevskayaem** [comment]
in BtLibrary DiscoveryManager set its BlePeerDiscoverer to null. But BlePeerDiscoverer has link to   DiscoveryManager (it's implement BlePeerDiscoveryListener). And sometimes BlePeerDiscoverer still continue sends callbacks to DiscoveryManager. So in app can exist zombie BlePeerDiscoverer witch continue to send wrong statuses to DiscoveryManager. 

Here I set to deleted BlePeerDiscoverer new fake BlePeerDiscoveryListener, that just writes in log messages that something strange happens. But in general better find out who calls methods on deleted BlePeerDiscoverer
