### ISSUE TITLE
testThaliManagerCoordinated/test write is not reliable, 'test repeat write 1', 'test repeat write 2'

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1596]
We aren't sure why and this is actually worrisome because this is a critical test

**Comment by yaronyg** [comment]
Write Test - These are logs from a failed run with two devices using Wifi and a slightly modified version of iOS branch I haven't committed yet but will provide the commit ID for.

Nexus 6 - https://gist.github.com/yaronyg/49d94abd4448e9bb2cff39f1745d7666
HTC One M9 - https://gist.github.com/yaronyg/08cb9b49b7cc866dfd114d9b37bb4ceb

**Comment by yaronyg** [comment]
HTC 9 - https://gist.github.com/yaronyg/d67e4a22b07662020f5f007b47b8e426
Nexus 6 - https://gist.github.com/yaronyg/fcce53ff519ef102fa482ad0c7b6c5a1
Test Server Log - https://gist.github.com/yaronyg/efd320ec60e715ad3d9426b090cbd2d4

This is, in a sense, a repeat of the previous test. The HTC successfully completed the test. The Nexus 6 did not. And again the Nexus 6 never got a single announcement from the HTC 9 over SSDP.

But now we have SSDP logging turned on. We can clearly see in the logs that the HTC 9 thinks it is advertising from all the nodeSSDPServerLogger entries which show the exact message it was advertising.

Both logs show that both the client and server successfully bound themselves. So now the question is - who's lying? Or... is this the router? Is it somehow blocking communication? @andrew-aladev in his test showed that if he ran against the Mac's built in wifi acting as a Wifi Access Point (with no security) then the tests always passed.

Just in case the logs aren't noise enough I'm going to turn back on tracing of incoming messages to see what that shows us.

**Comment by yaronyg** [comment]
HTC 9 - https://gist.github.com/yaronyg/5b0e035ede5b6521d079fb2009ae59d0
Nexus 6 - https://gist.github.com/yaronyg/8ba285fa598611bcd2aa3c9ca7b8f61c
Test Server Log - https://gist.github.com/yaronyg/21716477d3c30bfdcc49db245cdc28cb

Same story, HTC completes, Nexus 6 does not. The difference is that this time I have logging for all the events that the SSDP Client sees. Also note that I did get a bit impatient and kill the Nexus 6 logs before the final failure event but long after the test was hopelessly lost.

What's interesting about these logs is that we can see in both logs that the nodeSSDPClientLogger binds successfully. In fact this is advertised twice. Once with 'Socket bound' and a second time with 'SSDP listening'. Just make sure to check for instances issued by nodeSSDPClientLogger. The same, btw, applies on both devices for the nodeSSDPServerLogger. By every means we have we are bound twice to the SSDP UDP socket, once for client and once for server, on both devices.

What's interesting through is that on the HTC we can immediately see that the nodeSSDPClientLogger and the nodeSSDPServerLogger are receiving both the NOTIFY methods it emitted itself as well as the notify method emitted by the Nexus 6. But on the Nexus 6 we only see the NOTIFY that the Nexus 6 emitted, nothing from the HTC.

This seems seriously bizarre to me. It shows that we can emit on the Nexus 6 to UDP and that we can hear what we emit but we can't hear anything else. That is really unfortunate because it means that we can't test when we have a 'bad' UDP listener by checking if we don't hear our own broadcasts. It seems we'll hear our broadcasts no matter what. So now we have no hint what so ever that anything is wrong.

http://stackoverflow.com/questions/9363389/udp-broadcast-packets-not-received-in-sleep-mode/16208617#16208617 looks a lot like our problem. This is particularly possible since the HTC 9 is configured in developer options to stay awake and the Nexus 6 is not. So I enabled stay awake on the Nexus 6 and voila tests now reliably pass. So let's try the opposite approach, disable stay awake on both devices. I even manually turned off the screen on both devices. And sure enough. The tests fail. We have a winner!

We'll follow up in thaliproject/Thali_CordovaPlugin#1620 

But for now we should assume that test write behaves itself.

**Comment by yaronyg** [comment]
@andrew-aladev Please run all the tests in thaliManagerCoordinated.js (make sure they are all activated) on iOS branch on Android in Wifi and Native and Both modes with stay awake on and see if they pass. If they do then please close this bug.

**Comment by chapko** [comment]
Some older logs from android devices.

Native mode:
- [native-1.log](https://gist.github.com/chapko/63a13f8fabd7aefcf4a4480e8329f19b/raw/e4497aab74d20b436871dc0a71b56f3e281b3dc3/native-1.log)
- [native-2.log](https://gist.github.com/chapko/63a13f8fabd7aefcf4a4480e8329f19b/raw/e4497aab74d20b436871dc0a71b56f3e281b3dc3/native-2.log)
- [native-3.log](https://gist.github.com/chapko/63a13f8fabd7aefcf4a4480e8329f19b/raw/e4497aab74d20b436871dc0a71b56f3e281b3dc3/native-3.log)

WiFi mode:
- [wifi-1.log](https://gist.github.com/chapko/63a13f8fabd7aefcf4a4480e8329f19b/raw/e4497aab74d20b436871dc0a71b56f3e281b3dc3/wifi-1.log)
- [wifi-2.log](https://gist.github.com/chapko/63a13f8fabd7aefcf4a4480e8329f19b/raw/e4497aab74d20b436871dc0a71b56f3e281b3dc3/wifi-2.log)
- [wifi-3.log](https://gist.github.com/chapko/63a13f8fabd7aefcf4a4480e8329f19b/raw/e4497aab74d20b436871dc0a71b56f3e281b3dc3/wifi-3.log)

**Comment by andrew-aladev** [comment]
Today we've found that `js_ReportOverRecursed` warning can be improved.

**Comment by andrew-aladev** [comment]
Pouchdb is using `js-extend` for copying `request.js` [options](https://github.com/pouchdb/pouchdb/issues/6012). It looks like we can replace it with `Object.assign` without any problems.
