### ISSUE TITLE
Ignore files on android build

### ISSUE THREAD

**Issue by deefactorial** [thaliproject/Thali_CordovaPlugin#16]
In step 7 of android build to exclude *.gz from build use the ant.property aapt.ignore.assets

I think I set an environment variable for that I'll check later what that was.

**Comment by deefactorial** [comment]
```sh
export ANDROID_AAPT_IGNORE="*.gz"
```

**Comment by obastemur** [comment]
@deefactorial in which step you add this ? OFC, if you haven't defined it under bash_profile ?

**Comment by deefactorial** [comment]
I would simply add it as one of the steps to compile. your already asking them to set the environment variable `ANDROID_BUILD` to `grade` you could add it there. it needs to happen before you run `cordova build android`

**Comment by obastemur** [comment]
Thanks for the trick though. I don't know if I can alter it cross platform from JXcore. However, we brought an alternative solution with 'jx install' See https://github.com/jxcore/jxcore-cordova#how-to-install-node-modules 

Although it doesn't help with npm but just a cross platform way to making things automated.

**Comment by yaronyg** [comment]
Our instructions now are that we just pass in the ignore flag to JX when we call install.
