### ISSUE TITLE
What happened to our ability to turn bluetooth on and off in Android?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1600]
At one point we could turn bluetooth on and off but that seems to have gone missing from JXcoreExtension.java in iOS. What happened?

Once we figure out where the code went we need to fix 'test to coordinate connection cut' to work on Android.

**Comment by vasilevskayaem** [comment]
This method "ToggleBluetooth" are present in JXMobile.java class

**Comment by evabishchevich** [comment]
@yaronyg We haven't ever had this method in JXCoreExtension.java. Functionality for toggling bluetooth is in jxcore-cordova plugin. There is JXMobile.java file which is responsible for that functionality(https://github.com/thaliproject/jxcore-cordova/blob/master/src/android/java/io/jxcore/node/JXMobile.java#L88)

**Comment by evabishchevich** [comment]
@yaronyg Do you have any logs with the failure?

**Comment by vasilevskayaem** [comment]
Can't reproduce this bug on samsungs

**Comment by evabishchevich** [comment]
10/10, can't reproduce

**Comment by vasilevskayaem** [comment]
we've never call "ToggleBluetooth" this because of https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/test/www/jxcore/lib/testUtils.js#L33

**Comment by evabishchevich** [comment]
@vasilevskayaem We call that in iOS branch https://github.com/thaliproject/Thali_CordovaPlugin/blob/iOS/test/www/jxcore/lib/testUtils.js#L25

**Comment by evabishchevich** [comment]
@yaronyg Please, provide the logs with the failure or steps to reproduce. Katya and me couldn't reproduce this bug. Also I talked with @chapko and he haven't seen failures on this test

**Comment by yaronyg** [comment]
So the functionality is provided via Mobile in JXcore-Cordova, not in JXcoreExtension.java. That is fine.

**Comment by evabishchevich** [comment]
@yaronyg We tried to reproduce on ios branch , not ios_chapko_899-complete

**Comment by yaronyg** [comment]
This was built into JXcore. I forgot that so I went looking for it in our code and of course didn't find it.
