### ISSUE TITLE
Do we really need 'setWifiRadioState' method?

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1601]
This method was added by me in #1547 (issue #1317 ). We have practically the same method in jxcore-cordova called 'toggleWifi' (https://github.com/thaliproject/jxcore-cordova/blob/master/src/android/java/io/jxcore/node/JXMobile.java#L113). 
What was the reason for creating of this method? If 'toggleWifi' was just a stub my question is "Do we still need setWifiRadioState?".

**Comment by yaronyg** [comment]
Yes, this was a mistake. We should have used toggleWifi that is built into JXcore-Cordova instead of having written our own equivalent version. So we should rip out our version and use the one in JXcore-Cordova.

**Comment by vasilevskayaem** [comment]
https://github.com/thaliproject/Thali_CordovaPlugin/pull/1610 made pr, but it fails, @chapko could you please have a look?
