### ISSUE TITLE
What is the stuff on the end of the peer identifier in iOS?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#161]
I'm trying to run tests on identity exchange and I noticed something very odd. The peer identifiers that I'm getting back from iOS are not the ones I submitted!

For example, on phone #1 I submitted the following string whose value I confirmed by debugging into THEMultipeerClient.m and catching the value of peerIdentifier on line 62:
`peerIdentifier	__NSCFString *	@"Ije8unzruH58EMaR+ixb/A==;BOB"	0x0000000174441080`

But then, on phone 2, I stuck in a print statement in thalireplicationmanager.js to see what I'm getting back and it is:
`[{"peerIdentifier":"Ije8unzruH58EMaR+ixb/A==;BOB.hIcFPVPBnKo=","peerName":"(null)","peerAvailable":true}]`

Do you see that junk on the end after BOB? The .hIcFPVPBnKo=?

But it gets weirder. Phone #2 advertises itself as:
`peerIdentifier	__NSCFString *	@"qC1pQ7c5CyKa+IPIJ7ngAw==;BOB"	0x000000017425deb0`

But here is the list of peers I discovered on phone 1:
`Found peers: [{"peerIdentifier":"qC1pQ7c5CyKa+IPIJ7ngAw==;BOB.fOggLFlcs+4=","peerName":"(null)","peerAvailable":true}]
2015-10-13 19:50:49.092 ThaliTest[654:203608] jxcore: connect qC1pQ7c5CyKa+IPIJ7ngAw==;BOB.fOggLFlcs+4=
Found peers: [{"peerIdentifier":"qC1pQ7c5CyKa+IPIJ7ngAw==;BOB.sEW6dPsR+5g=","peerName":"(null)","peerAvailable":true}]
2015-10-13 19:50:49.103 ThaliTest[654:203608] jxcore: connect qC1pQ7c5CyKa+IPIJ7ngAw==;BOB.sEW6dPsR+5g=
Found peers: [{"peerIdentifier":"qC1pQ7c5CyKa+IPIJ7ngAw==;BOB.50jF3uYr+jc=","peerName":"(null)","peerAvailable":true}]
2015-10-13 19:50:49.111 ThaliTest[654:203608] jxcore: connect qC1pQ7c5CyKa+IPIJ7ngAw==;BOB.50jF3uYr+jc=
Found peers: [{"peerIdentifier":"qC1pQ7c5CyKa+IPIJ7ngAw==;BOB.YiK7jgY7iYw=","peerName":"(null)","peerAvailable":true}]
Found peers: [{"peerIdentifier":"qC1pQ7c5CyKa+IPIJ7ngAw==;BOB.fOggLFlcs+4=","peerName":"(null)","peerAvailable":true}]`

They all have the same base but different "." values appended to the end. What is that?

**Comment by yaronyg** [comment]
Note that I'm running these tests from my branch where I have merged in the changes from your branch. But presumably this would also occur in your branch? I have pushed my changes to my github repo (story_001_yarong) in case you want to look at this in context.

**Comment by yaronyg** [comment]
Need to propose a sane solution for how to differential instances between start and stop broadcasting to Toby.

**Comment by tobybrad** [comment]
As discussed the extra stuff on iOS is required to be able to differentiate between subsequent sessions of the same peerIdentifier. iOS leaves these hanging around for a long time so you can discover your previous selves. If you only keyed sessions on the most significant part of  peerIdentifier alone you'll collide live peer sessions with previous, moribund ones.

In any case.. I believe we established no changes were needed here.

**Comment by yaronyg** [comment]
This is a won't fix as these issues will go away when we switch to the notification framework. Not worth fixing now.
