### ISSUE TITLE
t.sync() fails on iOS devices

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1613]
*'Coordinated pull replication from notification test'* fails on iOS devices. It looks like `t.sync()` somehow disconnects devices from coordinated server.

**Comment by yaronyg** [comment]
Please test iOS wifi on master and see if the same problem shows up. If it does then this doesn't block us going to master from the iOS branch. If it doesn't then this does block us from moving iOS branch to master.

**Comment by chapko** [comment]
The same issue with the *'Coordinated replication action test'*. It uses `t.sync()` too.

**Comment by chapko** [comment]
I reproduced this bug in `master` branch.

**Comment by chapko** [comment]
Coordinated server expects sync content to be the same, but iOS apps have different paths on different devices:
```
unwrap/<@/private/var/containers/Bundle/Application/8D769F9C-61F1-4D62-AC92-E5BD5EE625FF/ThaliTest.app/www/jxcore/node_modules/lie/lib/index.js:88:21
unwrap/<@/private/var/mobile/Containers/Bundle/Application/CA0268D3-7932-4CDE-9C35-DF2BC92C15B9/ThaliTest.app/www/jxcore/node_modules/lie/lib/index.js:88:21
```
