### ISSUE TITLE
SIGABRT in JXcore.m

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#162]
We are tracking https://github.com/jxcore/jxcore/issues/601

**Comment by yaronyg** [comment]
We need to walk through our use of threads and figure out if we are ever doing callbacks to JXcore on JXcore's thread.

**Comment by tobybrad** [comment]
Discussing with Oz it seems this a threading issue within JXCore. It should be safe to call callEventCallback from *any* thread within the system, we're seeing a failure of this guarantee.

Fix is now here, added to v7 of jx core. Will require update and rebuild.
https://github.com/jxcore/jxcore-cordova/commit/5e4cfb175d37ec1331e701f044bb87d3f4c01817
