### ISSUE TITLE
UDP Broadcast stops working when Android's screen turns off

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1620]
It turns out that when Android turns off its screen it really likes to save power and one of the things it does is disable UDP broadcast support which is a problem since we use that support to enable discovery over Wifi. So this means that we can't actually discover devices over Wifi if the phone's screen is off.

https://groups.google.com/forum/?fromgroups=#!topic/android-platform/OpbSdp9FTmA discusses these issues and proposes a fairly nasty solution which is to grab a partial wake lock from the power manager when the screen goes off and then restart wifi. I talked with Paul about this and he said they did this because it was the only thing that worked semi-reliably. However he needed something that worked on old and new phones.

In theory the 'proper' way to handle this is https://developer.android.com/reference/android/net/wifi/WifiManager.WifiLock.html which has been around since API 1 but according to Paul doesn't work reliably on all devices.

https://developer.android.com/reference/android/net/wifi/WifiManager.MulticastLock.html looks even more perfect.

So the work items here are:
1. Write a simple native test to send a UDP broadcast and confirm that we don't receive it on the second device and make sure it works when the screen is on. 
2. Use the previous to confirm that in fact we can't receive UDP broadcasts from other devices while the screen is off (make sure the devices have settings -> developer options -> stay awake turned off)
3. Then test if the multicast lock will work to fix this.
4. If that fails then try the wifi lock.
5. If that fails then try the power manager plus wifi toggle trick

If you can think of any other approaches that don't requiring toggling wifi that would be very nice.

**Comment by evabishchevich** [comment]
@yarong Do you mean receive or not receive in 1st point (" that we **don't receive** it on the second device  and make sure it works when the screen is on")?

**Comment by evabishchevich** [comment]
We are not able to connect to group owner if its screen is off. I tried it with/without <uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE" /> and WifiManager.Multicast lock. But if we are already connected we are able to send multicast messages even without locks

**Comment by evabishchevich** [comment]
Tried with wifi locks, the same result

**Comment by yaronyg** [comment]
We should not investigate this in the context of WiFi Direct. Just a normal Wifi endpoint. So please ignore the previous tests for now. And also we need to understand if we can solve this and how that solution will work with doze and app stand by.

**Comment by yaronyg** [comment]
Can we receive broadcasts if we are listening for a specific address and not for 0.0.0.0? For example SSDP always runs on 239.255.255.250:1900.

**Comment by yaronyg** [comment]
1. Please put in the table of results
2. Please investigate the battery implications of the multicast lock, does it disappear on its own when we lose connection to a access point? If we are still on the access point and have a multicast lock what is the battery consumption?

**Comment by evabishchevich** [comment]
|  Device | S6 |  | HTC10 |  |
|  :------: | :------: | ------ | :------: | ------ |
|  Address | 239.255.255.250:1900 | 228.227.226.225:1900 | 239.255.255.250:1900 | **228.227.226.225:1900** |
|   |  |  |  |  |
|  No locks | Doesn't receive | Receives | Doesn't receive | Doesn't receive |
|  Multicast lock | Doesn't receive | Receives | Doesn't receive | Receives |
|  Multicast lock + Wifi lock | Doesn't receive | NO NEED TO TEST | Doesn't receive | NO NEED TO TEST |
|  Trick with toggling wifi | Receives with packet loss | NO NEED TO TEST | Receives with packet loss | NO NEED TO TEST |

**Comment by yaronyg** [comment]
For those trying to understand the table above what's going on is that we tested the standard SSDP multicast address 239.255.255.250 and found out that Android doesn't like that much when it goes into the background. So @evabishchevich decided to just pick some random, but not reserved, multicast address, he choose 228.227.226.225 and try that. And sure enough it behaved differently! So it seems that whatever Android devices are doing to block multicast when in the background only applies to 'well known' multicast addresses (which makes sense as those channels are likely to be quite noisy) but not to less well known ones. So we need to switch our address.

**Comment by yaronyg** [comment]
Question 1 - If we lose the network (SSID/BSSID) do we lose the lock?
Question 2 - Is the lock specific to the SSID or the BSSID?
Question 3 - If we temporarily lose the network and the network comes right back does the lock restore?

**Comment by yaronyg** [comment]
@evabishchevich When thinking through the API there are several choices depending on what we discover about the lock:

Choice 1 - Keep it locked! - We would have a Node API of the form lockAndroidWifiMulticast(). Once called it is up to Android to do whatever it takes to keep the multicast lock. So if the answer to question 1 is 'yes' then it would be up to the native layer to get a new lock when a new network shows up. We would also have an unlockAndroidWifiMulticast() call for when we don't need the lock anymore.
* Pro - It makes the node code simpler since it doesn't need to deal with retry and it makes the Android code simpler as it just focuses on keeping a lock and doesn't have to worry about sending events to Node.
* Con - It makes it more likely that we will keep locks when we don't really need them and it puts complexity in Android when we want it in Node because it's faster to develop there.

Choice 2 - Lock while you can - In this case we would also have the same APIs but if the lock is lost for any reason we would have to fire an event to tell node this and then Node would have to call lockAndroidWifiMulticast() again if they want a new lock.
* Pro - It makes the Android code simpler. It also makes it more likely we will lose a lock (since Node is forced to deal with lost locks) which means we are likely to eat less battery.
* Con - It makes the Android code more complex as now we need an event.

I suspect it will be more obvious which choice we make once we have the questions to the 3 questions in the previous comment.

**Comment by evabishchevich** [comment]
@yaronyg I'm done with PR thaliproject/Thali_CordovaPlugin#1646 . It's already merged in ios_1620

**Comment by yaronyg** [comment]
@evabishchevich Will run all the tests on iOS_1620 and make sure that his 3 Android devices do not have the developer mode switch to keep the device from going to sleep on and will make sure that the devices are screen locked and if they pass then we can submit iOS_1620 for code review. The new tests, btw, are in testThaliWifiInfrastructure.js lines 594 and 621.

**Comment by evabishchevich** [comment]
@yarong I tested on 3 devices. Tests passed

**Comment by yaronyg** [comment]
@evabishchevich When thaliproject/Thali_CordovaPlugin#1651 is submitted successfully to the iOS branch then please update iOS_1620 branch and submit it as a PR. Please set it to be reviewed by me (since I need to check your Android changes) and Chapko.

**Comment by evabishchevich** [comment]
PR #1661
