### ISSUE TITLE
Fix Android BLE Zombie Problem

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1629]
## The Problem
Thali uses BLE to advertise the presence of a Thali device. In that advertisement is a Bluetooth MAC address and a one byte generation counter. In theory we should get a nice stream of events where each event has a higher generation (accounting for roll over) than the previous one.

However we are getting repeated situations where we get BLE discovery announcements for the same BLE MAC + Bluetooth MAC in an impossible generation order. 

For example, we'll get Generation 0 and then 3 and then 2 and then 4 and so on. We also get repeated generations. For example, we'll get Generation 0 and then Generation 1 and then another Generation 0.

From the tests we have run the problem seems to be in Android itself. There is something screwy in the queue that discovery announcements are put into that causes them to come out in random orders and with repeats. We call these outdated announcements 'zombies'. Since we can't figure out how to fix the Zombies in Android, we have to deal with it.

## Why we care

In theory we really could ignore this problem. If we treat generations not as integers but rather as a 'I have new data' flag then having generations go backwards and forwards or repeat won't matter. At worst it will just create spurious flags saying "I have new data" when in fact the remote peer doesn't. In that case we will just waste a Bluetooth connection talking to a peer who doesn't actually have anything for us.

But even that isn't a minor issue. It is really expensive to create a Bluetooth connection and while we are doing that we are largely unavailable for replication with other peers and even BLE discovery goes wobbly because of contention for the 2.4 GHz antenna. So fake "I have new data" flags are actually kind of expensive.

So we are motivated to try and filter out zombies.

## How do we filter out zombies?

Ignoring roll over for just a second we can do some fairly simple things. For example, if our first discovery of a peer was on generation 0 and then 2 seconds later we get generation 4 we know something is wrong. The reason is that currently we only send generation updates no faster than once a second. So if we got generation 0 2 seconds ago and then get generation 4 we know something is very wrong.

Unfortunately there are three possibilities and there is no clear way to know which possibility it is:

Possibility 1 - The generation 0 was the 'real' value and generation 4 is a zombie from the very distant past (there would have to be a wrap around to account for it)

Possibility 2 - The generation 0 was the zombie and generation 4 is the real value.

Possibility 3 - Both values are zombies and we still haven't gotten the current real value yet

So in thinking about this problem we have two basic approaches.

Approach 1 - Limited Zombie Time Frame - If we know that Zombies couldn't be older than some reasonably small fixed value then we could reason in the face of Zombies. But we actually don't know how long a value could get stuck in the Bluetooth queue before it shakes lose and is sent to us.

Approach 2 - Unknown Zombie Time Frame - In this scenario we assume that a Zombie could be stuck in the Bluetooth queue for an unbounded time so we can't trust anything.

Now in thinking through this keep in mind that eventually we are going to switch to using a BLE GATT server and that will (as far as we know) make the Zombie issue go completely away. But until then we need to decide how to handle this mess.

### Unknown Zombie Time Frame

I generally like to make as few assumptions as possible so the first place I want to start with is the unknown zombie time frame. What can we do to handle Zombies if we never know if any value is a Zombie or not?

One possibility is that we introduce our one 1 second rate limiter. Right now Android will forward us notification updates as soon as it gets them. So if we get updates faster than 1 a second then we know that those announcements must be zombies because announcements are only sent out at the rate of 1/second. So we can put in a filter that ignores any peerAvailabilityChanged events from the Android native layer that arrive more frequently than once a second. 

The problem is that it's not clear how often zombies show up. If they all show up at once then this is a reasonable approach. But if they are going to trickle out then this will force us to create many unnecessary bluetooth connections which is bad. It really hurts our perf.

But what if we didn't use 1/second? What if we used say 1/5 seconds or 1 event every 10 seconds? This isn't as loony as it might sound. The main downside to this approach is that it might cause us to wait too long before doing an update but if we are in the background that isn't too bad. And if we are in the foreground and the app wants us to keep a replication going then it should just do that by extending the replication timeout rather than depending on notifications of changes and expensive bluetooth connection establishment.

#### Limited Zombie Time Frame

One suspects (but we have not proven) that the Zombie problem has a limit. That we aren't going to get Zombies from an hour ago if only because the queue that this data is stored in by Android (or the hardware) probably isn't that big. So what if there is a time limit to how old a Zombie could be? Let's call that limit L seconds.

In that case whenever we get a generation we know it could be 'off' by up to L seconds. In other words if L is say 60 seconds and we get a generation 0 then we know that the 'real' generation must be a value between 0 and 60 (remember that we already have logic that guarantees we won't publish generation updates to BLE faster than 1/second).

So once we get an advertisement with generation 0 we know:
* It MUST NOT be possible for us to immediately get a generation with 61-195 because if we do then L is wrong and we have problems. Note that this window will obviously shift as time passes.
* If we see future announcements with a generation less than our 'current value' (e.g. 0 + however many seconds have passed) then we can ignore it as a Zombie. Keep in mind roll over. This means that if 2 seconds pass and we get generation 199 then we can ignore this because even with the L error not enough time has passed for a roll over.
* If we see a generation higher than ours that is within the legal window (e.g. L + time that has passed + generation, account for roll over) then that is our new base and we have to jump to it.

In essence we create a ratchet. So long as L is >= to the real Zombie time limit we will only move forward and will be able to ignore a lot of (but not all of) the noise.

```
function canIgnoreNewGeneration(lastGeneration, newGeneration) {
   assert(newGeneration is integer and >= 0 and <= 255);
   timeSinceLastGeneration = Time in Seconds that have elapsed since the last generation value was received
   // So much time has passed that any generation is possibly real
   if (L + timeSinceLastGeneration >= 256) return false;
   leftBorder = lastGeneration + 1;
   rightBorder = (lastGeneration + L + timeSinceLastGeneration) mod 256;
   if (leftBorder < rightBorder) {
      return !(newGeneration >= leftBorder && newGeneration <= rightBorder);
   }
   return !(newGeneration >= leftBorder || newGeneration <= rightBorder);
}

if (canIgnoreNewGeneration(lastGeneration, newGeneration) == true) {
  return
}
```

## Fixing the generation counter

Android's behavior is a pain. We have to deal with Zombies. We have to deal with roll over. It makes life for those up the stack really hard. To simplify we need to not let the generation on the wire be sent up the stack from thaliMobile. Instead we should generate our own generation counter and every time we update the cached entry we should update that generation counter. It is the 'fake' generation counter that we should send up the stack. That way those up the stack only have to deal with a linearly increasing counter.

## The Plan

For no particularly good reason I'm picking the limited Zombie Time Frame approach. And while we are there we also need to fix the generation counter.

### thaliConfig
- [ ] Add a value 'ANDROID_ZOMBIE_TIME_IN_SECONDS' and set it to 60, this will be the L value mentioned in canIgnoreNewGeneration

### thaliMobile.handlePeer
- [ ] If we get peerAvailable === false on the Android platform then immediately call changedCachedPeerUnavailable(peer). It doesn't matter what generation is being sent because !peerAvailable is generated via a heuristic in Android land (we didn't hear any announcements from the peer for a minute) not as part of an explicit message like 'byebye' or an advertiser being shut down in iOS. So if it says a particular peerID is gone then that peerID is gone regardless of generation. Note that the iOS logic doesn't change. It should work exactly as it currently does.
- [ ] changed thaliMobile.handlePeer so that on Android if there is a cachedPeer and if peer.peerAvailable === true then we call something like canIgnoreNewGeneration(cachedPeer.generation, peer.Generation) and if it's false then we just return without taking any action since we assume we got a zombie. Don't even update peer.availableSince as this is a zombie. Basically, if canIgnoreNewGeneration is false then we should just pretend we never got called.
- [ ] On the Android platform we should generate our own generation counter in thaliMobile. So the first time we add an entry on Android for cachedPeer we MUST set a value 'fakeGeneration' to 0 and record it on the peer object so it will be placed into the cache by changeCachedPeerAvailable. And in peerStatus (the value we will emit as a peerAvailabilityChanged event) we have to set generation to peer.fakeGeneration. Note that this doesn't affect iOS or Wifi so those platforms must set generation to peer.generation.
- [ ] Any time we get a peerAvailablityChanged event on Android that has an existing cachedPeer entry then we have to add a peer.fakeGeneration = cachedPeer.fakeGeneration + 1;

**Comment by chapko** [comment]
@yaronyg the link below is a file with android logs I have collected during December that contains only `peerAvailabilityChanged` announcements from native layer. You can see that usually zombie appears ~50 ms earlier or later than real event. But also there are some weird cases like:
```
12-05 17:57:04.951 - [{"peerIdentifier":"BC:75:74:3A:BC:B7","generation":119,"peerAvailable":true}]
12-05 17:57:24.503 - [{"peerIdentifier":"BC:75:74:3A:BC:B7","generation":0,"peerAvailable":true}]
12-05 17:57:31.806 - [{"peerIdentifier":"BC:75:74:3A:BC:B7","generation":121,"peerAvailable":true}]
```

It looks like 0 generation is kind of special case. It often just appears instead of a real one.

### [generations.txt](https://gist.github.com/chapko/66813bf68e22e95632f955485061b03e/raw/1808a36d1094f8e8cd8db4c3157de4ea25ef5165/generations.txt)
