### ISSUE TITLE
Real generation in availability events sometimes replaced with 0 on Android devices

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1638]
From [this comment](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1629#issuecomment-266716274) to the thaliproject/Thali_CordovaPlugin#1629 issue.

Basically we have a case when native layer sends 0 generation instead of the real one to the node layer. For example:

```
12-05 17:57:04.951 - [{"peerIdentifier":"BC:75:74:3A:BC:B7","generation":119,"peerAvailable":true}]
12-05 17:57:24.503 - [{"peerIdentifier":"BC:75:74:3A:BC:B7","generation":0,"peerAvailable":true}]
12-05 17:57:31.806 - [{"peerIdentifier":"BC:75:74:3A:BC:B7","generation":121,"peerAvailable":true}]
```

For more examples see [generations.txt](https://gist.github.com/chapko/66813bf68e22e95632f955485061b03e) file

**Comment by yaronyg** [comment]
Let's make sure that if Bluetooth goes away that we clean up all objects. Same if we turn things off.

**Comment by evabishchevich** [comment]
PR thaliproject/Thali_CordovaPlugin#1677
