### ISSUE TITLE
Test if we have connection issues with iOS

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#164]
There is a possibility that if two iOS devices connect simultaneously to each other over both advertising and listening then there is a potential bug that will cause one of the connections to fail after around 2 minutes. We have to write a perf test to validate if this issue exists.

**Comment by yaronyg** [comment]
Note that we have never seen this.

**Comment by tobybrad** [comment]
This should naturally be covered by a long running perf test I believe.

**Comment by yaronyg** [comment]
Have you looked at the perf tests and convinced yourself that any of them will do the job?

**Comment by DrJukka** [comment]
We can add the test once we get the multiple out-going connections working. Basically then I can start connection out, and connect back to any connection that comes in and wait. Thus I would either have just two devices communication as a pair, or two pairs doing the same. Is there any other requirements, for example, do we need to exchange data while waiting ?

**Comment by yaronyg** [comment]
We will need to exchange data. So the set up would be: Device A connects to Device B, Device B then reciprocates by connecting to Device A and then they start moving as much data as humanly possible for as long as possible.
