### ISSUE TITLE
Have to fix the PouchDB js-extend bug

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1643]
https://github.com/pouchdb/pouchdb/issues/6012

**Comment by yaronyg** [comment]
Just to be clear this is blocking tests so we really need this fixed.

**Comment by yaronyg** [comment]
@andrew-aladev It looks like PouchDB has fixed this bug. Can you please confirm and if so please close both this bug and bug 6012 in PouchDB.

**Comment by andrew-aladev** [comment]
It looks like next release after 6.1.0 will have such fix. For now we can use link to current master.

**Comment by andrew-aladev** [comment]
I've provided a pull request for issue #1644.
