### ISSUE TITLE
Crash in test repeat write 2 teardown

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1687]
https://raw.githubusercontent.com/ThaliTester/TestResults/9937456522c40ea_Refactor_incoming_and_outgoing_socket_thread_tests_evabishchevich/build.md

find 
uncaught exception, error: 'AssertionError: entry exists

**Comment by chapko** [comment]
It looks like it happened at the "test repeat write 2 - teardown"

**Comment by andrew-aladev** [comment]
It looks possible for us to receive timeout from test server because BLE can sleep for about 30 seconds sometimes. We need to increase these timeouts.

**Comment by yaronyg** [comment]
@andrew-aladev If BLE is going to sleep then isn't this an Android and not a node issue?

**Comment by yaronyg** [comment]
So let's see if we can clear up a few things.

1. Andrew couldn't reproduce the assertion error
2. Separately, but for this test, Andrew found out that it looks like in some cases BLE appears to sleep. We don't get any peer notifications for 30 seconds which shouldn't happen.

But Andrew should be able to investigate the assertion error even without a repo so this bug should be about the assertion error and we will investigate the BLE issue in thaliproject/Thali_CordovaPlugin#1569
