### ISSUE TITLE
Radically simplify Thali Cordova Peer Communication API

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#17]
This issue is about proposed changes to https://github.com/thaliproject/Thali_CordovaPlugin/blob/story_0_matthewp/doc/api/replication.md to make it much simpler.

Proposal 1 - Remove "currentMachineIdentifier" argument from StartBroadcasting. We always have to broadcast our high bandwidth transport ID when we announce ourselves so the native code should just handle this for us. In other words Android should always advertise the Bluetooth UUID and iOS should always advertise the Multi-Peer PeerID.

Proposal 2 - Get rid of Disconnect. Instead specify explicitly that any time we kill the TCP connection to the TCP client bridge then that means we want to kill the connection to the remote peer. Yes, I know the perf on this is awful. We'll fix it later. But for now simplicity is a feature.

Proposal 3 - Get rid of GetDeviceName. We really and truly don't need it. For now the "deviceName" value passed into StartBroadcasting should be the user's actual name that they will pass in via the post card app and in the future we will be doing something completely different involving crypto magic.

Proposal 4 - Get rid of GetKeyValue and SetKeyValue. They were intended for advertising extra information using either BLE properties or mDNS but since we don't really support either at the moment there is no point in having APIs that don't do anything.

Proposal 5 - Get rid of MakeGUID. There is literally no reason for it to exist. We can generate GUIDs in Node.js. No reason to add another native binding.

Proposal 6 - Get rid of GetFreePort. I would actually argue that this method is actively harmful. The reason is that between the time that you check to see if the port is available and when you actually use it someone else could claim it. What someone should do is pass 0 into their listener on Node.js and it will automatically grab a free port. So this function does not need to exist at all.

@DrJukka and @deadlyfingers both need to review.

**Comment by DrJukka** [comment]
I actually can agree on all Proposals with any need for modifications.

Would though have question, on whether we should add a method for Node to retrieve the ‘high bandwidth transport ID’ ?

-jukka-

**Comment by yaronyg** [comment]
Per our phone conversation proposals 1, 3 - 6 are all adopted. However I sent out mail with a new proposal to keep Disconnect. I'll send more on that in a little bit once I figure out the framing issue.

Also, as we discussed on the call, we will eventually need an API for high bandwidth transport ID (or as I've been calling it, a peer ID) but we don't need it right now.

**Comment by DrJukka** [comment]
Changes done. Disconnect not changed yet.

**Comment by yaronyg** [comment]
Per our conversation on the call we will leave Disconnect. Since we are leaving Disconnect I would suggest that we just make it simple as follows.

Connect - Causes a P2P connection to be formed and TCP/IP listener starts listening. It will accept exactly one connection and refuse all further connection. If the TCP/IP connection is lost for any reason then the P2P connection should be torn down and immediately rebuilt. This is necessary to make sure we don't have framing issues. If, while still in connect state (e.g. disconnect has not been called), the P2P connection dies then the TCP/IP listener needs to kill its connection (if it has any) and immediately start trying to reconnect the P2P connection. While it's try to reconnect the P2P connection the TCP/IP listener should still accept a single incoming connection but its just going to hang until the P2P connection is back up and running. It would be useful to have some kind of event that fires when the P2P connection is lost just so that the Node.js code has some idea why its TCP/IP connection went away. But so long as disconnect is not called then the native code will keep trying to keep the P2P connection alive.

Disconnect - Once disconnect is actually called then we kill the TCP/IP listener and tear down the P2P connection. When this is all done then the callback on disconnect should be called.

Make sense?
