### ISSUE TITLE
Need to be able to pin binary dependencies in Thali

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#170]
When Thali is installed it will grab whatever bits are in master regardless of which version of Thali it is. That obviously breaks people when we update master. It breaks Postcard app for example. So we need to change our install script to pick the right binary not just what is in master.

**Comment by yaronyg** [comment]
Also, we need to create a release script for ourselves so that whenever we update the NPM number we correctly set the github location for the binaries as well as update the project.json files in 3 or 4 different places to use the new thali version number.

**Comment by yaronyg** [comment]
I believe you are trying to fix this now?

**Comment by vjrantal** [comment]
> I believe you are trying to fix this now?

That is right. I think I succeeded in this in the 2.0.4 release I made to https://www.npmjs.com/package/thali.

@yaronyg: Do you want this issue to be closed only after we have scripts that automate the steps needed?

**Comment by yaronyg** [comment]
Since we aren't using full bug discipline (in which case only the person who opened a bug can close it) I'm fine with us closing a bug once we have a PR submitted since any further issues will be resolved there.

**Comment by vjrantal** [comment]
@yaronyg: Sorry for not being clear what I meant.

The question was rather about the scope of this issue. The title says:

> Need to be able to pin binary dependencies in Thali

And this is now possible with manual work. However, this issue has a comment saying:

> Also, we need to create a release script for ourselves..

So the question is, is creating the script also in the scope of this issue and if yes, that work hasn't been done yet and this should be kept open.

**Comment by yaronyg** [comment]
Manual release processes fail. So I wanted some way for us to get prompted when we do a release for the branch/tag that the release should point at. So let's leave this open.

**Comment by vjrantal** [comment]
@yaronyg: I removed the New Infra -milestone, because I think we don't need to make that many releases between now and March. Fully scripting the release process isn't trivial, because it currently requires publishing a release from GitHub Web pages. Yes, this could also be scripted via GitHub APIs, but in my opinion, it isn't the most important thing to do right now.
