### ISSUE TITLE
Implement the Wifi infrastructure for vNext

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#171]
- [x] Test all the idempotent methods to make sure they really are idempotent.
- [x] Tests for all the events we are supposed to fire. (`wifiPeerAvailabilityChanged` was implemented in context of this issue and rest is under https://github.com/thaliproject/Thali_CordovaPlugin/issues/481)
- [x] Tests that when we stop advertising we actually issue a byebye.
- [x] Make sure when we change our USN that we both issue a byebye for the old USN and an alive for the new one.
- [x] Change "different USN after every invocation" test to use node-ssdp.
- [x] Test that after stopping, we don't get anymore advertisements and all open connections closed. (this is partly tested by the fact that the test runner exists cleanly, i.e., no open connections prevents a clean exit)
- [x] Implement the promise-queue.
- [x] Start using the SSDP NT value as specified.
- [x] Add node-ssdp API to remove USN and start using it.
- [x] Properly start the passed router object.
- [x] Start using winston logger.
- [x] Check that passed router object inherits from router (express does the checks when we use the router and we have a try-catch-handling for that).

**Comment by yaronyg** [comment]
10/29 - Just barely started on this, tomorrow should be full day on this.

**Comment by yaronyg** [comment]
10/30 - Started implementation. Lots of issues with the library. It has some fixable but fundamental issues about how they did things. The API they offer is synchronous but they are doing asynchronous things so it's a mess.

**Comment by vjrantal** [comment]
Working on it at https://github.com/thaliproject/Thali_CordovaPlugin/tree/story_03_vjrantal.

**Comment by yaronyg** [comment]
11/2 - He has pushed his current work to a branch. He has some issues with the SSDP library but those seem to be under control, so there is some work.

**Comment by yaronyg** [comment]
Please see https://github.com/thaliproject/Thali_CordovaPlugin/blob/story_001/thali/NextGeneration/thaliWifiInfrastructure.js

**Comment by yaronyg** [comment]
Also please check the version of the spec that is now in vNext - https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext/thali/NextGeneration/thaliWifiInfrastructure.js
