### ISSUE TITLE
Fix build process on iOS

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1733]
@jareksl provided me with following message during building process:
```
xcodebuild[95085:2498150] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7fd2d7026cb0>: Error Domain=IDEFoundationErrorDomain Code=1 "No 'teamID' specified and no team ID found in the archive" UserInfo={NSLocalizedDescription=No 'teamID' specified and no team ID found in the archive}

error: exportArchive: No 'teamID' specified and no team ID found in the archive
```

**Comment by dersim-davaod** [comment]
There was missing team ID in the settings of the generated Xcode project.

In the future try to check your dev certificates and provisioning profile. Then please check your team setting in the project.
Also try to build project directly via `xcodebuild` command (see last comments for more details: https://zube.io/thaliproject/thali_cordovaplugin/c/2501)
