### ISSUE TITLE
test "cannot call multiConnect with invalid syncValue" fails on iOS

### ISSUE THREAD

**Issue by dersim-davaod** [thaliproject/Thali_CordovaPlugin#1750]
This issue is related to thaliproject/Thali_CordovaPlugin#1749 issue.
Log from device is [here](https://gist.github.com/dersim-davaod/874579a0461f6af68d397873c1cb1f35).

**Comment by dersim-davaod** [comment]
@chapko, you can assign me to #1750 when you fix #1749. I'll run tests on devices.

**Comment by chapko** [comment]
Fix for #1749 is in the #1756 PR

**Comment by drinkius** [comment]
Issue is with ErrorType -> NSError type casting. Easily fixed in Swift 3 / iOS 10 with CustomNSError protocol. Waiting for Swift 3 migration to perform changes

**Comment by asuhodolov** [comment]
PR thaliproject/Thali_CordovaPlugin#1841
