### ISSUE TITLE
Fix "Can shift large amounts of data" test

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1761]

**Comment by chapko** [comment]
Branch: iOS_chapko_1761

Logs with native tests enabled: https://gist.github.com/chapko/f028d495856f9555643de9f5edb50ced
You can see that other devices do note receive anything

Logs with native tests disabled:
https://gist.github.com/chapko/f028d495856f9555643de9f5edb50ced
Looks like device receives more data than it sends. But also it could be a encoding/decoding issue on node side. I need to investigate it

**Comment by chapko** [comment]
> But also it could be a encoding/decoding issue on node side.

Yes, it is an issue on the node side, test text contains multibyte characters so length was not calculated properly. I've fixed the test in my branch.

**Comment by chapko** [comment]
Tested it today with to device (one runs on iOS 9 and another on iOS 10). On iOS 9 it always passes, on iOS 10 it alway hangs (tried 3 times)
