### ISSUE TITLE
Replace socket library in iOS

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1765]
We have 2 failed tests (#1761, #1764) because of the bugs in current socket library.

**Comment by dersim-davaod** [comment]
As previously described in #1759, we can use new socket framework to fix failing tests above.
It is [BlueSocket](https://github.com/IBM-Swift/BlueSocket) written in Swift.

**Comment by jareksl** [comment]
Not needed anymore as both failing tests pass. Fixed in ThaliCore by https://github.com/thaliproject/thali-ios/pull/10
