### ISSUE TITLE
Android returns incorrect error when Bluetooth is turned off

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1767]
From `startUpdateAdvertisingAndListening` and `startListeningForAdvertisements` docs:

| Error String | Description |
|-|-|
| No Native Non-TCP Support | There are no non-TCP radios on this platform. |
| **Radio Turned Off** | **The radio(s) needed for this method are not turned on.** |
| Unspecified Error with Radio infrastructure | Something went wrong with the radios. Check the logs. |
| Call Start! | The object is not in start state. |

But on android trying to call `Mobile('startListeningForAdvertisements')` returns different error:
```
  ---
    operator: equal
    expected:
      'Radio Turned Off'
    actual:
      'Failed to start the connection manager (Bluetooth connection listener)'
  ...
```

**Comment by evabishchevich** [comment]
PR #1769
