### ISSUE TITLE
Make sure to turn off radios for perf tests

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#177]
We need to make sure that when the perf tests are done that the radios are turned off. I have introduced a new function in story_001_yarong  in testUtils that handles this. But I'm not sure where all the places are to stick the off. I would suggest we need to structure the perf tests so that there is a well defined choke point where the code has to pass regardless of success or failure and then we can stick the off there.

**Comment by DrJukka** [comment]
Already done. I added a new command 'end' which will be turning off the radios, as well as its sending the end-comments into the logs.

**Comment by yaronyg** [comment]
Do you also handle this in the case that the tests fail for some reason? In other words do you have hooks into the process level uncaught exception and uncaught promise handlers?

**Comment by DrJukka** [comment]
I suppose would need to see that these do get added to the Disconnected, since that would prevent coordinator server on sending the 'end' command. Any other fail would simply timeout the current test.

**Comment by yaronyg** [comment]
Right but in all cases before the device 'finishes' (with an error or not) it MUST turn the radios off. E.g. this is the last action regardless of success or failure.

**Comment by DrJukka** [comment]
Currently, there are three places where the device 'finishes' and turns radios off:
- When it gets 'end' command indicating fully finished testing
- when it gets 'too_late' event, indicating that it did the connection attempt too late to join the testing
- when it gets 'disconnected' event indicating that communications to server was lost

I did add the hooks, and within the hooks the coordinator connection is closed, effectively causing turn off for radios

**Comment by yaronyg** [comment]
The thing is that chasing down such exit points is hopeless. Good design would have the test run inside of a container call and regardless of how the tests end the container call would exit and call the radio turn off. Anything else is just bug heaven.

**Comment by DrJukka** [comment]
Yep. Fixed this in a way that turning Radios off will happen only with Disconnected event. Other parts will simply call close() to coordinator, which eventually will cause disconnected event to fire.
