### ISSUE TITLE
'Can connect to remote peers' fails on iOS in native mode

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1778]
Devices receive more peer availability then they should. Running on 2 devices I got notifications from 2-3 devices
logs: https://gist.github.com/chapko/432f8704a016854112b45a56fe7804a7

**Comment by chapko** [comment]
Maybe it is related to the zombie issue (#1323)

**Comment by chapko** [comment]
I modified this test a bit, so it tries to connect to every peer it finds and if at least on connection is successful the test ends with success.

But then it failed with another error: 
```
not ok 178 listening port should not be 0
  ---
    operator: ok
    expected: true
    actual:   false
  ...
```
Logs: https://gist.github.com/chapko/7424a8e8a2a711e8713b7c7c1f707cb7

**Comment by drinkius** [comment]
Issue looked like a possible problem with two-way connection using MPC framework, created a separate test app with TaliCore & basic connection functionality. Connects work well in this setup&

Run additional tests with one test only and they pass, so the problem must be with advertiser or other state persistence across tests. Investigating further

**Comment by drinkius** [comment]
Pinned down the issue, it's connected to the way our native method **startUpdateAdvertisingAndListening** works, we create new peer as follows:

let newPeer = currentAdvertiser?.peer.nextGenerationPeer() ?? Peer()

However this means that between tests we preserve the Peer we are advertising with. It's advertiser is subsequently deleted, this the peer goes away and the other side can't connect to it, meaning we fail the test with a timeout. Consulting with Dersim on the best way to fix it

**Comment by drinkius** [comment]
Real problem is in MPCF: calling **stopAdvertisingPeer** seems to be working with delay, thus at the start of the test we can see the peer from previous advertiser. 

Adding a 5s delay for the test start fixes the issue

**Comment by drinkius** [comment]
Created a pull request. The timeout of 1s also worked in 3 consecutive tests, set 5s just in case to avoid test fails. 

Need to investigate the reasons why MPCF advertises the peer **after stopAdvertisingPeer()** is called
