### ISSUE TITLE
serverScript doesn't handle paths

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#178]
serverScript really wants to have the coordination server as a child off of '.' but we want it as a path.

**Comment by vjrantal** [comment]
I think I might have reproduced this in this build https://gist.github.com/ThaliTester/c3786ecdcb0ec493f071. In that one, I have the `serverScript` set like here https://github.com/thaliproject/TestDummy/blob/eab44d9aa1c0f467133288f16803b83501d18886/mobile_test.json#L14 and at least locally when I run the `build.sh` I have the `index.js` in that path at the end of the build process.

**Comment by yaronyg** [comment]
Yeah, @obastemur confirmed that there is a problem with the parsing logic for the serverScript path and that he would fix it.
