### ISSUE TITLE
Test iOS branch to be able to merge in master

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1780]
Android:
- [x] wifi @chapko 
- [x] both @chapko / me
- [x] native me

iOS:
- [x] wifi @chapko 
- [x] both @dersim-davaod 
- [x] native @dersim-davaod

**Comment by dersim-davaod** [comment]
On iOS in wifi mode we have failing tests:
[`test repeat write 1`](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1782)

**Comment by evabishchevich** [comment]
Android, native mode.
[Test results](https://gist.github.com/evabishchevich/666619cbc4e1f9d39ba46205fac30386)

There were some failed tests. First of them was
[startUpdateAdvertisingAndListening - ending remote peers connection kills the local connection](https://gist.github.com/evabishchevich/98bfc78d699ff1747faa53fadaabb012)
There is #1743 issue.
The second fail was  in [can do HTTP requests between peers](https://gist.github.com/evabishchevich/fc83ba2959281d47f2a4c57f1ba16976). It's connected with some strange behaviour of the cordova. The activity was [recreated](https://gist.github.com/evabishchevich/32a2ef9c4c38e47fbf1cd34945a10c4c) during testing. 
The third fail connected with #1592. @enricogior will provide the fix soon.

**Comment by evabishchevich** [comment]
Android, both mode:

Client to server request coordinated #1792

**Comment by chapko** [comment]
Android in BOTH mode and iOS in WIFI mode require #1794 PR

**Comment by chapko** [comment]
I've tested Android BOTH mode on Nexuses and Samsungs. Nexuses are passing fine, on Samsungs I had 2 failures: the first one because of native connections timeout (one device couldn't connect to another in 4 attempts and test failed with timeout error), the second one is #1743 issue mentioned above. All other tests are passing, so I'm marking Android BOTH as working here

**Comment by dersim-davaod** [comment]
I've ran tests in native mode with #1794 PR.
Unfortunately we still have failing test from `testThaliManagerCoordinated.js` (see [logs from device](https://gist.github.com/dersim-davaod/8c2039c4854d69cdcb12e1062e83e349)).

**Comment by evabishchevich** [comment]
Tested BOTH mode on Android with new jxcore. Everything is good.
