### ISSUE TITLE
CI needs to identify each commit related test instance for the same PR with its own ID

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#181]
When TestRoom reports status for test runs it doesn't distinguish between commits. So all the test runs for the same PR have the same ID. This makes it really difficult to file bugs and discuss issues with different commits. What we need is that each commit gets its own separate ID. So for example in my current PR each test run would report an ID of the form 4970403-X where X is a unique ID for the commit that caused that particular test run.

**Comment by obastemur** [comment]
done
