### ISSUE TITLE
Not all tests were actually run by CI - is that a bug or a feature?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#182]
If you look [here](https://github.com/thaliproject/TestDummy/pull/37) please look at the two entries from ThaliTester after checkin ed633ed. You will seea "PR is added to the queue" message and a "build process is completed" message.

But that is it. Then youw ill see commit bfa6326 which says it is added as 2. task. You will see a new build process (just as before). And only now will you see test failed.

In this case I submitted bfa6326 before ed633ed had actually completed. Is it a feature that we kill the in progress testing and replace it with the new commit on the same PR or do we have a bug?

What's frustrating is that without unique IDs I can't be sure if the "TEST 47970403 has failed" that is reported after bfa6326 belongs to bfa6326 or to ed633ed.

So was ed633ed abandoned or did some test not run?

If ed633ed really was abandoned then we need ThaliTester to report that. E.g. we should get a message "Test 47970403-ed633ed abandoned due to submission of test 47970403-bfa6326"

Please clarify.

**Comment by yaronyg** [comment]
The desired functionality is that if a second commit comes in the first commit is aborted. It's not clear that is what's actually happening, Oguz will take a look.

**Comment by obastemur** [comment]
There won't be any abort but each commit will be tested and labeled separately. (Fixed)
