### ISSUE TITLE
Coordination machine address is a mess in CI

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#183]
The install script we are using actually detects the local machine's address and configures it automatically. The script is finding the coordination server's address as 192.167.1.20 but according to the docs the address should be 192.168.1.150. Is the coordination server multi-homed?

**Comment by yaronyg** [comment]
BTW, we already worked around this by making it possible to just specify the IP address directly but it would be good to understand what is going on. Is the coordination server a separate machine than the build machine? Why are the IPs different?

**Comment by obastemur** [comment]
Surely build machine is not the coordination machine

**Comment by yaronyg** [comment]
No problem. I already put in the ability to let the CI script specify what IP address it wants used for the coordination server. I'll close this issue.
