### ISSUE TITLE
Put in a node.js redirect to handle arguments

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#185]
We have a script called setUpTests.sh that is called via the directory's package.json using the jx run command setupUnit and setupPerf. Those are really just calls to setUpTests.sh with command line arguments to control what file they will make into the app.js for the test project.

The problem is that when we do CI we need to pass in a second argument, which is the IP address for the coordination server. We can either do this by adding more scripts entries to the package.json or, the better way, is to pass in the IP address argument in the build.sh script for CI.

The problem is that when build.sh calls jx npm run setupUnit -- 192.167.1.150 the last argument (the IP address) doesn't survive the script call because it's a hard coded bash script call.

I tried to slip in a $1 to the script definition in the package.json but that didn't work.

My guess is that what we have to do is replace setupUnit and setupPerf from being calls to sh scripts to instead being a call to a node.js file which will get the arguments and then have that node.js file call the bash scripts.

Messy, but less messy than having a nake call to ./setUpTests in build.sh for CI.

**Comment by DrJukka** [comment]
BTW, as the IP address is static & known, would it be simpler just to have it written into the serveraddress.json file supplied with test js files ?

**Comment by yaronyg** [comment]
Figuring out what IP address to use should be part of the install scripts. And we should use the same install scripts for everything. So for us to just have a hard coded serveraddress.json file it means that we need to pass in a flag to the build scripts tell them not to overwrite the serveraddress.json file with the local machine's address (which is what we do automatically when running local tests). Well if we have to pass in that flag we can just as easily just pass in the IP address. And in either case we end up having to deal with this bug that there isn't a good way to pass in that second argument because of how the scripts are currently specified.
