### ISSUE TITLE
Can shift data via parallel connections fails on desktop

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1857]
Logs: https://gist.github.com/opetkevich/a2b4a563d697e74ccc982f8d61dc90d8
branch: master_petkevich_1845_node

**Comment by evabishchevich** [comment]
Logs: https://gist.github.com/evabishchevich/10c8ab03870f8af71b355f059b89a947
branch: master

**Comment by mlesnic** [comment]
Tested multiple times, seems to work pretty reliable.

**Comment by mlesnic** [comment]
Checked again and it fails. To investigate.

**Comment by mlesnic** [comment]
Fixed in master.
