### ISSUE TITLE
Why can't the devices connect to the coordination server or is the coordination server not running?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#186]
If you look at the [error log](https://gist.github.com/ThaliTester/41c72c4eb0039f0b85d7) you will see the text:

```
,I/jxcore-log( 4689): Turning radios to true
I/jxcore-log( 4689): 
,I/jxcore-log( 4689): toggleBluetooth - 
I/jxcore-log( 4689): 
,I/jxcore-log( 4689): toggleWiFi
```

This is generated by the function [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/story_001_yarong/test/www/jxcore/lib/testUtils.js#L9) which the text above shows that we called. So the Wi-Fi and Bluetooth radios should be on.

And as the log also shows we are trying to connect to 192.168.1.150 which is the address that we were given [here](https://github.com/thaliproject/TestDummy/blob/master/README.md)

So why isn't the connection going through?

Note that we are using port 3000.

**Comment by yaronyg** [comment]
I also realized that the logs don't show any output from the coordination server. Is it not running? We the config certainly calls for it. Shouldn't we have some output to tell us what is going on with the coordination server?

**Comment by obastemur** [comment]
https://github.com/thaliproject/TestDummy/blob/test_yarong/mobile_test.json 

There is no `TestServer` folder. So CI manager runs and exits without doing anything.

**Comment by obastemur** [comment]
CI will be reporting such issues from now on forward.
