### ISSUE TITLE
Tests to skip on Android

### ISSUE THREAD

**Issue by enricogior** [thaliproject/Thali_CordovaPlugin#1860]
On Android, the following two tests are failing, given they are iOS specific tests, they should be skipped when running ThaliTest on Android.

`Single coordinated request ios native`
https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/test/www/jxcore/bv_tests/testHttp.js#L153

`Multiple coordinated request ios native`
https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/test/www/jxcore/bv_tests/testHttp.js#L228

**Comment by mlesnic** [comment]
This tests should not be fired on Android devices at all, closing.
