### ISSUE TITLE
Make our tests properly report results to the CI environment

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#187]
If I'm reading [here](https://github.com/thaliproject/TestDummy/tree/test_yarong#basics-of-using-ci) correctly then the CI environment is monitoring each device's log output and decides if that device passed or failed based on looking for the magic strings put in the log by the `end` function defined at the link. 

In the case of the unit tests this means we need to go to thali-tape.js and [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/2fdfdaf711bc1fdb40ec604744e99d23a5b5bd03/test/www/jxcore/lib/thali-tape.js#L29) and [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/2fdfdaf711bc1fdb40ec604744e99d23a5b5bd03/test/www/jxcore/lib/thali-tape.js#L33) make sure we call `end(true)` (meaning yes, we failed). It also means going [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/2fdfdaf711bc1fdb40ec604744e99d23a5b5bd03/test/www/jxcore/UnitTest_app.js#L56) and making sure to call end with true if any tests failed otherwise calling it with false or null.

For perf tests I'm not sure where all the hooks go but remember you need the equivalent of the thali-tape exception and promise hooks to catch those in addition to having to catch whenever it is you know where all the tests are done.

**Comment by yaronyg** [comment]
10/26 - This bug is blocked until the perf and unit tests are actually passing.

**Comment by DrJukka** [comment]
successful perf test run: https://github.com/ThaliTester/TestResults/blob/4860079788277ed_Story_001_juksilve_DrJukka/test_log.md

successful unit test run: https://github.com/ThaliTester/TestResults/blob/4860079788277ed_Story_001_juksilve_DrJukka/test_log.md

**Comment by yaronyg** [comment]
SCORE!!!!!!!!!


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by vjrantal** [comment]
I am reopening, because it looks like the code currently prints `PROCESS_ON_EXIT_FAIL`, but the CI code looks for `PROCESS_ON_EXIT_FAILED` so the CI doesn't spot the failures. Apologies, if I misinterpreted the current situation.
