### ISSUE TITLE
Add possibility for Thali to replicate with database which name is different than our local one

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#1873]
So in Thali there is an assumption that the database that we will try to replicate with will be named in the same way as our local database. After latest changes in TeamONE application, the local database name is strictly connected with logged in user id, so every user, even if he is in the same team, will have database named in different way, which causes Thali to not work. 
The solution might be to slightly modify `ThaliReplicationPeerAction` that there will be possibility to pass a remote database name as additional parameter in the runtime, during `ThaliReplicationPeerAction.start` call. 
By default of course, the remote db name will the same as our local one, which name is passed during init.

**Comment by yaronyg** [comment]
Per our call today it makes sense to add localDbName and remoteDbName to the constructor of ThaliReplicationPeerAction.
