### ISSUE TITLE
Test: thaliMobileNativeTestUtils.js error handling on iOS

### ISSUE THREAD

**Issue by enricogior** [thaliproject/Thali_CordovaPlugin#1880]
The iOSConnectToPeer function should return a fatal error when a connection to a peer fails, in order to avoid retrying connecting to a peer that is not available anymore.

The code to be changed is this:
```
      if (error) {
        return reject(new Error(error));
      }
```
https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L171

It has to be changed to:
```
      if (error) {
        error = new Error(error);
        error.isFatal = true;
        return reject(error);
      }
```

**Comment by mlesnic** [comment]
Changed and already in master.
