### ISSUE TITLE
Test: call 'disconnect' in teardown

### ISSUE THREAD

**Issue by enricogior** [thaliproject/Thali_CordovaPlugin#1882]
The tests that call `thaliMobileNativeTestUtils.connectToPeer(peer)` should call `disconnect(peer)` in teardown.
There are seven tests in https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/test/www/jxcore/bv_tests/testThaliMobileNative.js that need to be fixed.

A suggested fix:
 - declare a global variable `var peerIdToBeClosed = "";` along with the existing `var serverToBeClosed = null;`
 - change all `function onConnectSuccess(err, connection)` to `function onConnectSuccess(err, connection, peer)`
 - store the peerID in `onConnectSuccess(err, connection, peer)` setting `peerIdToBeClosed = peer.peerIdentifier;`
 - change `teardown` replacing [`t.end()`](https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/test/www/jxcore/bv_tests/testThaliMobileNative.js#L54)
with
```
          Mobile('disconnect').callNative(peerIdToBeClosed, "0", function (err) {
            t.notOk(
              err,
              'Should be able to call disconnect in teardown'
            );
            t.end();
          });
```

This fix can't be fully tested with the current ThaliCore framework since the disconnect API has two bugs that prevent it from working. The bugs are tracked [here](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1875).

**Comment by mlesnic** [comment]
Changes related to this issue were be done in `testThaliMobileNative`, `testThaliMobileNativeiOS`, `testThaliMobileNativeWrapper`, `testHttp`. Already in master.
