### ISSUE TITLE
iOS Native: Replication works only once

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#1890]
Replication on iOS devices works only for some short period of time. This issue was previously reported to Dersim, but he told us that it might be related to inappropriate implementation of peer pool policy manager. We tried multiple solutions and after that, it still behaves the same, even using default one.
We also asked Enrico about that if he could investigate it further.

**Comment by enricogior** [comment]
Most of the bugs causing replication to stop working have been fixed in https://github.com/thaliproject/thali-ios/commits/master-enrico-error-handling-tmp
