### ISSUE TITLE
MPCF: Connection is not established after 21 virtual connections

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#1891]
So I ran `Can shift data via parallel connections` test using version that contains fix for zombies, on iOS devices, multiple times and it turned out, that it failed after 8 test. What was interesting is that it failed exactly at the same time when I ran it multiple times, so every time 8 tests were passing, and 9 one was failing due to timeout. 
Enrico investigated the issue and it turned out, that the problem occurs after 21 virtual connections have been used, at the 22nd connection the peer will disconnect. He tested it using 1, 2, 3, and 4 parallel connections and test failed after 21, 10, 7 and 5 run, always.
So it looks like we don't do something right when we close the virtual sockets
What might be interesting that it might be connected to the issue with replication on iOS, when it works only for some short period of time and then nothing happens, see #1890.

**Comment by enricogior** [comment]
Fixed in https://github.com/thaliproject/thali-ios/commits/master-enrico-error-handling-tmp
