### ISSUE TITLE
ThaliCore: EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#1909]
During running tests at some point the app stopped with following error/message:
![screen shot 2017-06-20 at 09 44 34](https://user-images.githubusercontent.com/19724972/27322151-430ce0f8-559d-11e7-8aff-52bcdc0107e1.png)

[Logs](https://gist.github.com/mlesnic/301fa048d6c79521aeb6a4df8f4de579)

**Comment by enricogior** [comment]
Fixed in https://github.com/thaliproject/thali-ios/commits/master-enrico-error-handling-tmp
