### ISSUE TITLE
Test setup script sometimes fails on OS X in thali postinstall script

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#192]
It might be just on my machine, but creating this as a reminder to figure out the root cause and as reference in case someone else sees this as well.

The error is coming when running:
```
./setUpTests.sh UnitTest_app.js 192.168.1.150
```
The error details below:
```
node.js:813
throw ee;
      ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:17:7)
    at Object.onanswer [as oncomplete] (dns.js:102:10)
npm ERR! thali@2.0.1 postinstall: `jx installCordovaPlugin.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the thali@2.0.1 postinstall script.
npm ERR! This is most likely a problem with the thali package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jx installCordovaPlugin.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls thali
npm ERR! There is likely additional logging output above.
```

**Comment by vjrantal** [comment]
@obastemur: To debug this, I'd like to see which address is not found. My issue was that I wasn't sure which `node.js` file is referenced here (to set breakpoints or console.logs). In the bash script, we are prefixing all commands with `jx`, i.e., not calling `node` or `npm` directly.

**Comment by vjrantal** [comment]
After a quick investigation, seems like it is coming when we try to reach `https://github.com/jxcore/jxcore-cordova-release/raw/master/0.0.7/io.jxcore.node.jx`. Since I am sure there is nothing wrong with that server, perhaps this is some local DNS issue or something like that.

@obastemur: When Googling `Error: getaddrinfo ENOTFOUND` seems like people have had this kind of issues with some older versions of `node`. What was the version the latest `jxcore` is based on?

**Comment by vjrantal** [comment]
@yaronyg and @tobybrad: I noticed you discussed in Slack about "bad download of io.jxcore.node.jx". Do you think the issue you see is what I reported here?

**Comment by vjrantal** [comment]
Continuing the monologue by saying that I also now saw this error which is what you might have been talking about:
```
Downloaded io.jxcore.node.jx
Failed with - Error: Command failed: 
module.js:1917
throw err;
      ^
Error: Package is either corrupted or not compatible with this JX binary.
```
When I got that one, seemed like the downloading of the binary didn't go through even though our node code thought that the download succeeded.

In my case, the downloaded binary size was only 447B:
```
$ ls -l ThaliTest/thaliDontCheckIn/jxcore/0.0.7/io.jxcore.node.jx
-rw-r--r--  1 vjrantal  staff   447B Oct 20 13:07 ThaliBuild/ThaliTest/thaliDontCheckIn/jxcore/0.0.7/io.jxcore.node.jx
```

**Comment by tobybrad** [comment]
Ok.. what I've tended to do in this case is to download io.jxcore.node.jx locally and fix up around thali/install/install:337 to just install from local directory rather than downloading

**Comment by deadlyfingers** [comment]
Related issue I've been hitting today while testing builds of Postcard app on Android and iOS - https://github.com/thaliproject/postcardapp/issues/53 
I'm using the download locally workaround that @tobybrad suggested for now.

**Comment by yaronyg** [comment]
10/20 - Everybody has run into this and Ville is working on this while he is blocked on deploying iOS to CI.

**Comment by vjrantal** [comment]
I have a commit at https://github.com/vjrantal/Thali_CordovaPlugin/commit/e98a2bb80493d9506c77f8f91651f1ca8ccc616e where I am improving the reliability of the script mainly in regards to how it handles error cases.

However, the root cause for this issue seems to be that the current hosting location for the `io.jxcore.node.jx` file isn't reliable:
```
$ curl -L -I https://github.com/jxcore/jxcore-cordova-release/raw/master/0.0.7/io.jxcore.node.jx > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   160    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:01:02 --:--:--     0curl: (52) Empty reply from server
```
Before closing this issue, I'd like to wait for a comment about if the releases could be hosted in a more reliable location. For that purpose, I am assigning this to @obastemur. Please comment here if a better hosting mechanism can be adapted or not and assign back to me and I'll act accordingly.

**Comment by obastemur** [comment]
(This is a `jxcore-cordova-release` issue.) https://github.com/jxcore/jxcore-cordova-release 

FYI; I couldn't reproduce this no matter what.

**Comment by yaronyg** [comment]
@obastemur said he will move hosting the JXcore binaries to Azure and see if that improves download performance.

**Comment by vjrantal** [comment]
@obastemur: What about if our install script would be checking some pre-defined environment variable (like `JXCORE_CORDOVE_RELEASE_FOLDER`) and if that exists, use the release from there instead of downloading? That would make this part reliable and faster than a download.

The same variable could be also set locally and be used similarly than what @tobybrad said in https://github.com/thaliproject/Thali_CordovaPlugin/issues/192#issuecomment-149534665 but wouldn't then require code changes (only setting a variable).

**Comment by yaronyg** [comment]
Use scp to pi@192.168.150:~/ and we can store stuff there. Just make sure to use a directory structure that differentiates version like io.jxcore.node.jx/7/(binary goes here).

**Comment by yaronyg** [comment]
10/26 - We should have a PR out tomorrow.

**Comment by vjrantal** [comment]
> Use scp to pi@192.168.150:~/ and we can store stuff there. Just make sure to use a directory structure that differentiates version like io.jxcore.node.jx/7/(binary goes here).

My PR at https://github.com/thaliproject/Thali_CordovaPlugin/pull/245 doesn't yet implement the logic above. It would be easy to add, but while working on this, I started wondering should we introduce a dependency to an scp library to our installation script due to a purely CI-related use case?

I wanted to check if either of these alternatives would be more reasonable:
1. Instead of scp, we would run an HTTP server on 192.168.150 that can serve the files and in the installation script, we can simply point to an alternative URL.
2. Have CI virtual machines pre-populate the temporary folder with the JXCore releases so that they get picked up automatically (doesn't require further code changes). If, for some reason, someone forgets to add new releases to the pre-populated content, the downloading still kicks in and things don't break.

**Comment by yaronyg** [comment]
10/27 - We have the PR for local install but more work to do for CI.
