### ISSUE TITLE
ThaliCore: Crash, VirtualSocket EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#1925]
![screen shot 2017-06-28 at 14 41 49](https://user-images.githubusercontent.com/19724972/27637450-0e5ceb54-5c10-11e7-9644-96a599f71e21.png)

**Comment by enricogior** [comment]
We haven't seen this particular crash in a while, let's consider it fixed for now.
