### ISSUE TITLE
On iOS, remove recreatePeer logic in ThaliMobileNativeWrapper.js

### ISSUE THREAD

**Issue by enricogior** [thaliproject/Thali_CordovaPlugin#1940]
See https://github.com/thaliproject/Thali_CordovaPlugin/issues/1924 for the discussion regarding why we need to change this login on iOS.

In `_multiConnectResolved` don't call [recreatePeer(peerIdentifier);](https://github.com/thaliproject/Thali_CordovaPlugin/blob/1f01b2e1751a2551f85d245eb8b575d7ef4fc2ad/thali/NextGeneration/thaliMobileNativeWrapper.js#L705) on iOS.

Same for `multiConnectConnectionFailure` [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/1f01b2e1751a2551f85d245eb8b575d7ef4fc2ad/thali/NextGeneration/thaliMobileNativeWrapper.js#L1316)

The changes are required after this commit to ThaliCore:
https://github.com/thaliproject/thali-ios/commit/0d8b48fac03f5dc372b3274b6fae80d25883dc3a

**Comment by mlesnic** [comment]
Done in master.
