### ISSUE TITLE
Test: two simultaneous multi connect request 

### ISSUE THREAD

**Issue by enricogior** [thaliproject/Thali_CordovaPlugin#1941]
This problem came up using these branches:
https://github.com/thaliproject/Thali_CordovaPlugin/commit/31384d0b279123fc0d1aa8e4180ea30784ff58c7
https://github.com/thaliproject/thali-ios/commit/0d8b48fac03f5dc372b3274b6fae80d25883dc3a

The test is 'Single coordinated request ios native'.
There are two notifications at the same time for two found peers and two multi connect requests executed before the first one is completed.
```
[ThaliCore] Browser.browser(_:foundPeer:withDiscoveryInfo:) found peer:61D3CB4A-4380-4398-BAF7-7466EA84AF23:0
[ThaliCore] BrowserManager.foundPeerHandler peer:Peer(uuid: "61D3CB4A-4380-4398-BAF7-7466EA84AF23", generation: 0)
[ThaliCore] Browser.browser(_:foundPeer:withDiscoveryInfo:) found peer:FA3D478A-04FB-4F74-A85B-3075BF2E9B5F:0
[ThaliCore] BrowserManager.foundPeerHandler peer:Peer(uuid: "FA3D478A-04FB-4F74-A85B-3075BF2E9B5F", generation: 0)
2017-07-14 18:30:34 - DEBUG thaliMobileNativeTestUtils: 'We got a peer {"peerAvailable":true,"peerIdentifier":"61D3CB4A-4380-4398-BAF7-7466EA84AF23","generation":0}'
2017-07-14 18:30:34 - DEBUG thaliMobileNativeTestUtils: 'Issuing multiConnect for 61D3CB4A-4380-4398-BAF7-7466EA84AF23 (syncValue: E3SqocZYG0hE7BePtTcOlP3M7b4jYv61)'
2017-07-14 18:30:34 - DEBUG thaliMobileNativeTestUtils: 'Got 'multiConnect' callback'
[ThaliCore] BrowserManager.connectToPeer(_:syncValue:retryCount:completion:) Peer(uuid: "61D3CB4A-4380-4398-BAF7-7466EA84AF23", generation: 0) creating a new relay
[ThaliCore] Browser.inviteToConnect(_:sessionConnected:sessionNotConnected:) Peer(uuid: "61D3CB4A-4380-4398-BAF7-7466EA84AF23", generation: 0)
[ThaliCore] Session.init(session:identifier:connected:notConnected:) peer:61D3CB4A-4380-4398-BAF7-7466EA84AF23:0
[ThaliCore] BrowserRelay.init(session:generation:createVirtualSocketTimeout:)
[ThaliCore] TCPListener.init(with:socketDisconnected:stoppedListening:)
2017-07-14 18:30:34 - DEBUG thaliMobileNativeTestUtils: 'We got a peer {"peerAvailable":true,"peerIdentifier":"FA3D478A-04FB-4F74-A85B-3075BF2E9B5F","generation":0}'
2017-07-14 18:30:34 - DEBUG thaliMobileNativeTestUtils: 'Issuing multiConnect for FA3D478A-04FB-4F74-A85B-3075BF2E9B5F (syncValue: eGw62fXAcMhv8KgXLur06fm9U7CQzHm1)'
2017-07-14 18:30:34 - DEBUG thaliMobileNativeTestUtils: 'Got 'multiConnect' callback'
[ThaliCore] BrowserManager.connectToPeer(_:syncValue:retryCount:completion:) Peer(uuid: "FA3D478A-04FB-4F74-A85B-3075BF2E9B5F", generation: 0) creating a new relay
[ThaliCore] Browser.inviteToConnect(_:sessionConnected:sessionNotConnected:) Peer(uuid: "FA3D478A-04FB-4F74-A85B-3075BF2E9B5F", generation: 0)
[ThaliCore] Session.init(session:identifier:connected:notConnected:) peer:FA3D478A-04FB-4F74-A85B-3075BF2E9B5F:0
[ThaliCore] BrowserRelay.init(session:generation:createVirtualSocketTimeout:)
[ThaliCore] TCPListener.init(with:socketDisconnected:stoppedListening:)
[ThaliCore] Session.session(_:peer:didChange:) peer:61D3CB4A-4380-4398-BAF7-7466EA84AF23:0 state: notConnected -> notConnected
[ThaliCore] BrowserRelay.closeRelay() state:connecting
```
As you can see there are two 'BrowserManager.connectToPeer()' requests, one after the other, but the first one hasn't called 'handleMultiConnectResolved' yet, but just 'validationCompletionHandler()'.
The 'BrowserManager.connectToPeer()' API doesn't support to receive another request if the first one is still pending.

**Comment by enricogior** [comment]
[`tryToConnect()`](https://github.com/thaliproject/Thali_CordovaPlugin/blob/master_fix_ios_replication/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L510) uses the local variable `runningTest` and the peer's `record.runningTest` value so it will try to connect to one peer at the time and never to the same peer twice.
But if `tryToConnect()` is called twice in a row for two different peers, there is no mechanism to wait for the previous call to complete before issuing another [`connectToPeer()`](https://github.com/thaliproject/Thali_CordovaPlugin/blob/master_fix_ios_replication/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L518) request.

The scenario that is more tricky to handle is exactly the scenario shown in the log: `peerAvailabilityChangedHandler()` receives a notification for a zombie advertiser and calls `tryToConnect()` that calls `connectToPeer()`. While `connectToPeer()` is still trying to connect to the zombie, `peerAvailabilityChangedHandler()` receives a notification for another peer and calls `tryToConnect()` that calls `connectToPeer()` and now we enter in a weird state in [`BrowserManager.connectToPeer()`](https://github.com/thaliproject/thali-ios/blob/master-enrico-error-handling-tmp/ThaliCore/MultipeerConnectivity/BrowserManager.swift) because it doesn't support to be called twice if the first call hasn't completed. Basically its error handler will mix up the two calls and the test will eventually fail.

**Comment by yaronyg** [comment]
Per [this](https://github.com/thaliproject/Thali_CordovaPlugin/blob/522dfbe7fe4523f63287ea8d5f38e402fa88e334/thali/NextGeneration/thaliMobileNative.js#L58) it is explicitly legal for the node layer to call multi-connect many times in parallel. The only restriction is that Node is not allowed to have multiple multi-connects outstanding for the same PeerID (which doesn't appear to be the issue here).

So we have a couple of options here to deal with the fact that MPCF doesn't like having multiple parallel connection requests outstanding.

1. Fix it in iOS - We can put a queue into iOS
2. Fix it in Node - We already have a command queue infrastructure in Node. We could slap that around multiConnect (and change the link above) but that will be a bit messy since the queue will actually have to run off the multiConnect failure and our the multiConnectResponse. But it's certainly do able.

The problem with Node is that I don't think (famous last words) that this problem would exist with M-87 and we would need to use the same command there. So then we would have to make the queue optional which would be sad. But this is just speculation.

**Comment by enricogior** [comment]
There were three issues in the native layer that I fixed.
First problem was the fact that the completion code was not capturing correctly the peer id, and therefore mixing things up.
The other two problem were related to 'lostPeerHandler()'.
When a peer is lost, I was closing the nonTCPSession, while instead it's better to explicityly close the relay and removed it right away, but only if the relay is not currently in use by 'connectToPeer()'.
The third problem was the 'connectToPeer()' and 'lostPeerHandler()' need to be synchronized, otherwise there are race conditions given the async nature of the code and the fact that while we close an active relay we need to prevent 'connectToPeer()' from trying to use it or viceversa while trying to connect to a peer we can't release that relay until the request fails.
So after these two commits, the problem is fixed:
https://github.com/thaliproject/thali-ios/commit/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d
https://github.com/thaliproject/thali-ios/commit/0a8b6001576321427f8286d697c2d6bce40733b0
