### ISSUE TITLE
ThaliCore: Race condition creating a VirtualSocket while the nonTCPSession is closing

### ISSUE THREAD

**Issue by lesn1kk** [thaliproject/Thali_CordovaPlugin#1965]
Crash occurred when testing replication between two devices using ThaliTestApp from `master_mlesnic_additional_attachments` in Native mode. 

Screen:
![screen shot 2017-10-03 at 13 46 26](https://user-images.githubusercontent.com/19724972/31124203-af39642e-a843-11e7-8478-03d1ec80a7ac.png)

Enrico's comment: `It looks like a race condition, an underneath MPFC connection was closed (probably because of the bug that is causing replication to fail) and that closed the TCPSession that was currently used to open another TCP connection for that Session. `

**Comment by jareksl** [comment]
fixed with: https://github.com/thaliproject/thali-ios/pull/13
