### ISSUE TITLE
Specifying notification TLS binding

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#197]
Wrote spec on how to bind to TLS from notifications using pre-shared keys. Also specified how to extend Node.js to support it. Sent spec to Toby for review.

**Comment by tobybrad** [comment]
@yaronyg Could you please link to the spec in this issue.. I'm having trouble matching issues to specs.

**Comment by yaronyg** [comment]
That is [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolBindings.md#transferring-from-notification-beacon-to-tls)

**Comment by yaronyg** [comment]
10/27 - Started reading.

**Comment by yaronyg** [comment]
10/28 - Still reading it between other work items

**Comment by tobybrad** [comment]
Read the whole thing. Broadly understand what's required.

I have to raise the question though. Is this really needed at this point in project ?
