### ISSUE TITLE
Create Cordova plugin infrastructure

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#2]
Tell us how we should create a Cordova plugin that will take in both the Android and iOS code and let people just drop us in and go!

**Comment by DrJukka** [comment]
The ansroi part is there (need to fix the two issues which do have manual workaround). Should the iOS be assigned to Brian ?

**Comment by yaronyg** [comment]
He's working on it now. But I won't close this out until I know Android is working.
