### ISSUE TITLE
Implement pre-amble and notification beacon library

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#209]
Please implement a library that handles pre-amble and notification beacon generation per the spec.

**Comment by yaronyg** [comment]
10/28 - About 50% done for primary coding (no testing yet).

**Comment by yaronyg** [comment]
10/29 - Most of yesterday was email hell so he should hopefully work on this today.

**Comment by yaronyg** [comment]
10/30 - Tabled while he worked on David's website review. But should get back to it today.

**Comment by yaronyg** [comment]
11/2 - No progress. He has been heads down on presentation stuff.

**Comment by mpodwysocki** [comment]
@yaronyg btw, the [HKDF library](https://www.npmjs.com/package/node-hkdf) is Apache 2.0 as listed on its readme.md

**Comment by yaronyg** [comment]
Indeed but JXCore has it implemented in native code. Of course given the Javascript to native overhead that doesn't necessarily mean it's faster. Although the HKDF library does worry me because it has so few users.

**Comment by yaronyg** [comment]
Also here is the API - https://github.com/thaliproject/Thali_CordovaPlugin/blob/story_03_yarong/thali/thaliNotificationBeacons.js
