### ISSUE TITLE
Tools to help us suck less on node_modules

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#211]
Tool #1 - Identify any path in node_modules (no matter how deep) that involves the same module as another path someone in the same directory (e.g. we have two versions of the same library)

tool #2 - Give us a list of the number of files per directory so we can figure out who the worst file count abusers are.

**Comment by yaronyg** [comment]
10/28 - Should work on that today.

**Comment by yaronyg** [comment]
10/29 - Still working on this.

**Comment by yaronyg** [comment]
Needs to be put into a repo

**Comment by tobybrad** [comment]
Repo exists here: https://github.com/thaliproject/scan_node_modules

**Comment by tobybrad** [comment]
I'm leaving this open only to invite comment on tweaks for readability/utility of the output. Close if you believe we have enough to work with.

**Comment by yaronyg** [comment]
There is only a readme currently in that repo

**Comment by tobybrad** [comment]
oops.. fixed. closed.
