### ISSUE TITLE
Get thali replication manager tests running!

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#214]
Once we have the CI environment under control this is the single most important test to get working reliably.

**Comment by yaronyg** [comment]
@tobybrad, @drjukka said that this test isn't passing locally. I believe this one was yours. Could you see about getting it to pass locally on Android and iOS so we can make sure it passes in CI? This is pretty much the single most important test we have at the moment so getting it running reliably is a big deal.

**Comment by yaronyg** [comment]
Toby is blocked because the downloads in setup script is failing.

**Comment by tobybrad** [comment]
Unblocked. Looks like this was actually all down to a corrupt .npm cache.

**Comment by yaronyg** [comment]
10/26 - Express Body Parser has a strict mode on by default but its throwing because some JSON body being returned by replication (it seems) is not in strict compliance with JSON. So the fix is switch to not being strict. Because the bug appears to be PouchDB's replication. Needs to test if this will fix it.

**Comment by tobybrad** [comment]
Hold your horses.. I mentioned on Slack this issue only appears when attempting to use the packaging feature of jx. There’s a bunch of stuff in body-parser about falling back to default implementations is certain modules are not available. I strongly suspect bugs in packaging are causing this to happen.

**Comment by yaronyg** [comment]
@tobybrad - Yup, I didn't update the bug after you clarified. We still need this bug until we get the replication manager tests running properly in CI. But do you want to open a separate bug on the packaging issue?

**Comment by yaronyg** [comment]
10/27 - He wrote the simplest code which is to just handle the error and retry and will test today.

**Comment by yaronyg** [comment]
10/28 - This seems to have spawned #255

**Comment by yaronyg** [comment]
10/28 - The PR is #255.
