### ISSUE TITLE
Remove the Thalitest specific files

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#23]
Right now we use app.js and the root package.json and index.html and a bunch of other files that we require to be moved over to whatever project is using us. But in the process we actually overwrite the files in the project that is using us. After all, that project will have its own index.html and its own package.json and its own app.js.

What we need to do is remove all the Thalitest specific files and we need to format our JS code so that it is a NPM module that the user can then require().

**Comment by obastemur** [comment]
Agree. Also, you better block 'thali' npm name as soon as possible.

**Comment by yaronyg** [comment]
Good idea! https://www.npmjs.com/package/thali
