### ISSUE TITLE
CI doesn't allow relative paths outside of the "original parent folder" as binary path

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#232]
If the `mobile_test.json` has a binary path set like this:
```
  "binary_path": {
    "ios": "../ThaliTest/platforms/ios/build/device/ThaliTest.app",
    "android": "../ThaliTest/platforms/android/build/outputs/apk/android-release-unsigned.apk"
  },
```
The CI will fail with error like this: https://github.com/thaliproject/Thali_CordovaPlugin/pull/216#issuecomment-150541223

**Comment by yaronyg** [comment]
@vjrantal - Oguz pointed out that we should probably only do relative paths under the root which was the original design where I had introduced a "ThaliBuild" folder under the local root and put things like "ThaliTest" in there. That way the path would be "ThaliTest/ThaliBuild/...". Why aren't we using that approach?

**Comment by vjrantal** [comment]
We could go into that direction as well, but I'll try to explain why that would require an "excess" copy as well.

When we have the CI monitor the `Thali_CordovaPlugin` repository (instead of the `TestDummy`), our root (a.k.a. "starting point") is the right version of the code to be tested. The issue with creating a folder structure like `ThaliTest/ThaliBuild/..` under this root directory is that it would create a "circular loop" when we try to add the Thali Cordova plugin onto an app that resides under the plugin folder itself. Adding the plugin tries to copy the plugin folder content under the app and that process would try to copy itself onto itself.

As workaround, we could start the build script by copying the root to some other directory, then creating the test app structure under the root and then add the plugin from the other directory so that there is no "circular loop".

If fixing this issue (https://github.com/thaliproject/Thali_CordovaPlugin/issues/232) is too much work, I think we can certainly also go into the proposed direction using the workaround above (or other workaround if others have better ideas).

**Comment by obastemur** [comment]
Remember the fact that the build server is OSX. You have 'rsync' command is available hence there is no circular copy problem. See 'rsync --exclude...'

**Comment by vjrantal** [comment]
> Remember the fact that the build server is OSX. You have 'rsync' command is available hence there is no circular copy problem. See 'rsync --exclude...'

The issue is "within" the `cordova plugin add` command. I am not sure what it internally uses for copying files if we use that command to add plugin from local folder.

**Comment by yaronyg** [comment]
@vjrantal do we still care about this?

**Comment by vjrantal** [comment]
We have a workaround for this issue in our `build.sh`.

I'd say we could close this with a "wontfix-style" resolution meaning the root cause isn't fixed, but we can manage with the workaround.
