### ISSUE TITLE
please review new iOS binding

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#234]
Please review the new spec

**Comment by tobybrad** [comment]
@yaronyg Could you please link to the spec in this issue.. I'm having trouble matching issues to specs.

**Comment by yaronyg** [comment]
The iOS binding is defined [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolBindings.md#multi-peer-connectivity-framework-mpcf) but you probably need to at least skim everything before it in that spec and you probably want to also skim [this](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolforopportunisticsynching.md) first.

**Comment by tobybrad** [comment]
Links are broken.

**Comment by yaronyg** [comment]
Sorry we are moving things around. [This](https://github.com/thaliproject/thali/pull/224) is the PR. So no matter what happens that will be there. [This](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/pages/TechnologyInvestigations/PresenceProtocolBindings.md) is the GitHub view of the file.

Probably more useful is [this](https://reviewable.io/reviews/thaliproject/thali/224) link which is the persistent link to the PR in reviewable. So long as the PR is around no matter what happens to the file you can find it. But [here](https://reviewable.io/reviews/thaliproject/thali/224/pages/TechnologyInvestigations/PresenceProtocolBindings.md#-) is the current link to the specific file to review. 

You should probably skim the whole thing but the section of direct relevance to you is titled "Multi-Peer Connectivity Framework (MPCF)"
