### ISSUE TITLE
Please review android bindings spec

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#235]

**Comment by yaronyg** [comment]
10/29 - Started reading

**Comment by yaronyg** [comment]
Note that [this](https://reviewable.io/reviews/thaliproject/thali/224/presenceprotocolBindings.md#-) is the doc to review but you probably want to at least skim [this](https://reviewable.io/reviews/thaliproject/thali/224/presenceprotocolforopportunisticsynching.md#-) first.

**Comment by DrJukka** [comment]
done, generally looks good. Had one question on unclear issue.
