### ISSUE TITLE
Please review SSDP spec

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#240]
The spec is [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolBindings.md#local-wi-fi-binding) but you really should at least skim the whole spec and you probably want to skim [this](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolforopportunisticsynching.md) first.

**Comment by yaronyg** [comment]
10/27 - Read it but needs to review a bit with some code.

**Comment by yaronyg** [comment]
10/28 - Will start tomorrow

**Comment by vjrantal** [comment]
I have read the spec and don't have any concerns about it.

Once we are further with the implementation and have done some testing, it might be that certain details / exact values could be revisited, but I think this is "business as usual"..?
