### ISSUE TITLE
Implement Node.js TLS extension for PSK

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#247]

**Comment by cicorias** [comment]
Is this a duplicate of #329 ?

**Comment by yaronyg** [comment]
Not so much a duplicate as the parent issue.

**Comment by cicorias** [comment]
@yaronyg if this is a parent of other items, then this should be 0

**Comment by yaronyg** [comment]
We typically don't have parent bugs. So I would argue that #247 and #329 are dupes of each other.

**Comment by cicorias** [comment]
closing as duplicate of #329
