### ISSUE TITLE
Aggressive times out and retry for iOS

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#258]
Per [problem 2](http://www.ymc.ch/en/multipeer-connectivity-a-bag-of-hurt) sometimes connections just go away. We need to set aggressive time outs at the node.js layer if we aren't seeing traffic and kill the connection so it will restart.

**Comment by tobybrad** [comment]
First we'd ideally write a test to demonstrate this problem exists.

**Comment by yaronyg** [comment]
Lets' see if the new code reproduces.
