### ISSUE TITLE
stream.push() after EOF issue on iOS

### ISSUE THREAD

**Issue by tobybrad** [thaliproject/Thali_CordovaPlugin#262]
When p2p link dies we see stream.push() after EOF error from which we don't recover. Fix this !!

- Issue caused by shutting down p2p socket from native side. Resolution is probably don't do that but we should probably also amend the tcpmultiplexer to deal with this situation for a once and for all fix.

**Comment by yaronyg** [comment]
10/29 - We seem to have a fix for this.

**Comment by tobybrad** [comment]
These are rolled into PR 272. Closing.
