### ISSUE TITLE
Please get us off the UX thread

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#266]
This is a tracker bug for https://github.com/jxcore/jxcore-cordova/issues/60

**Comment by yaronyg** [comment]
This is fixed in 0.1.0

**Comment by vjrantal** [comment]
> This is fixed in 0.1.0

The release hasn't yet been made available in the [release download site](http://az836273.vo.msecnd.net/), but we can update our plugin to point to it as soon as it is released.
