### ISSUE TITLE
Crash on iOS when running testSendData.js

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#275]

**Comment by yaronyg** [comment]
We have a heisenbug. :(

**Comment by yaronyg** [comment]
Got distracted for today because he had to fix a bug in CI about how it was handling merging (it was trying to rebase)

**Comment by yaronyg** [comment]
This is a known bug in the iOS framework. It doesn't appear to have a clear work around. Somewhere iOS in the MPCF sets nill in a hash table and you can't do that so it causes a crash. This has apparently being around since 7.

**Comment by tobybrad** [comment]
No longer an issue on ios9.
