### ISSUE TITLE
Replication is not happening with 3rd device

### ISSUE THREAD

**Issue by sreesharp** [thaliproject/Thali_CordovaPlugin#28]
I have installed the latest PostCard app in three android phones, and trying to replicate the cards across all the devices.  At any point, the replication is happening between only 2 devices.  If I kill all the apps, and restart again, replication might work work with different pairs, and leave one device alone.

**Comment by yaronyg** [comment]
Matt's tests should make it easy to repro this. So I'm going to assign it to him for now. However I don't consider this a blocker for Story 0 since just having two devices synching is good for right now.

**Comment by yaronyg** [comment]
I'm pretty sure that Jukka's checkin fixes this but we need a dedicated node test that proves that we are simultaneously talking to multiple peers.

**Comment by yaronyg** [comment]
Jukka, you need to write a node.js test that proves that Android (and of course iOS) are successfully replicating to multiple remote devices (assuming the environment has them) at the same time.

**Comment by yaronyg** [comment]
Do we have an explicit test that confirms that we can simultaneously synch with multiple devices? I believe our current tests only test one device at a time.

**Comment by tompaana** [comment]
There is no reason why Android couldn't do this. In fact, it should be doing this out-of-the-box if the JS code is right - apart from the occasional Bluetooth problems that manifest themselves on Android.
