### ISSUE TITLE
Start using Mobile.getDeviceName as device name in tests

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#290]
This makes it easier to associate log outputs to physical devices.

**Comment by DrJukka** [comment]
Currently the device name is formed as: String name = "\"" + android.os.Build.MANUFACTURER + "-"
            + android.os.Build.MODEL + "\"";

And as the Coordinatro server requires devices to have unique names, the methoid is not directly usable, I'm using it as:

Mobile('GetDeviceName').callNative(function (name) {
        myName = name + "_PT" + Math.round((Math.random() * (10000)));;
....
    })

**Comment by yaronyg** [comment]
Check to make sure that you are using the device's make, model # and its device name. We should not need to use a random string but rather the device's actual name. Jukka showed the code from JXCore that isn't returning the device's name. So this bug is blocked on JXCore giving us the device name.

**Comment by yaronyg** [comment]
Blocked on #299

**Comment by yaronyg** [comment]
Had trouble getting a hold of Oguz.
