### ISSUE TITLE
Calling connect again on iOS will fail unless disconnect called in between

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#291]
Can be seen from https://gist.github.com/vjrantal/9b752d5791b8033f8a0e#file-gistfile1-txt-L86 where the perf test tries to reconnect without calling disconnect.

As a part of fixing this, also update at least one of the unit tests to do re-connection without calling disconnect so that unit tests would catch this problem.

**Comment by DrJukka** [comment]
I had impression that we have the spec defined in a way that closing TCP/IP closes does the disconnect. anyway if it only comes in future editions, I could look adding mobile disconnect there

**Comment by vjrantal** [comment]
If it wasn't clear from the issue title, this was an issue raised against the iOS implementation.

The reference to the perf tests was just that this came up via those and not because the issue would be in the perf tests themselves.

**Comment by DrJukka** [comment]
This might be fixed with my last push (2 seconds ago), @tobybrad can you verify.
