### ISSUE TITLE
Get perf tests passing on iOS

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#293]
When using `story_001_juksilve` merged into `story_001` and running the performance test called `testSendData.js`, there is a crash on iOS.

A log output at https://gist.github.com/vjrantal/0368f632d0b8a000e519 including logs from two iOS devices that were the ones participating to the test.

**Comment by yaronyg** [comment]
Rewrites are necessary to clean up the perf code

**Comment by yaronyg** [comment]
There is a bug where we return the wrong result and need to fix.

**Comment by tobybrad** [comment]
Crash not seen since upgrade to ios9.

Example results post all the fixing: https://github.com/ThaliTester/TestResults/blob/54312298af2c956_Add_dummy_file_to_trigger_CI_tobybrad/test_log.md
