### ISSUE TITLE
The `testSendData.js` test failed with 3 Android devices

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#295]
Server log at https://gist.github.com/vjrantal/95a4e858f3b11f32d140 which shows the exact test configuration.

The result has one failed connection `Failed connections 1(50%)` and one device that got excluded from the test `LGE-Nexus 5_PT1067 removed from tests`.

Can send the logcat output from all 3 devices to the one who starts debugging this.

**Comment by DrJukka** [comment]
one of the devices got shut down in middle of the run. The logs are not showing reason why it did shut down.
