### ISSUE TITLE
JXCore: We need getDeviceName to return the user assigned name for the phone

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#299]
We need getDeviceName to return the phone's model, # and the user assigned device name.

Jukka, please confirm if getDeviceName in JXCore is in fact returning the user assigned device name. If it is then #290 just needs to remove the random string you added. If not then please assign this to Oguz to fix.

**Comment by DrJukka** [comment]
jxcore.RegisterMethod("GetDeviceName", new JXcoreCallback() {
      @SuppressLint("NewApi")
      @Override
      public void Receiver(ArrayList<Object> params, String callbackId) {

        String name = "\"" + android.os.Build.MANUFACTURER + "-"
            + android.os.Build.MODEL + "\"";

        jxcore.CallJSMethod(callbackId, name);
      }
    });

SDK docs:
public static final String MODEL
- The end-user-visible name for the end product.

public static final String MANUFACTURER
- The manufacturer of the product/hardware

Build.java
 /** The end-user-visible name for the end product. */
    public static final String MODEL = getString("ro.product.model");


I don't see any ways on changing these values, thus I would see that we do need to get something else to make the name unique & settable by user (would suggest Bluetooth name, it can be programmatically get/set)

**Comment by yaronyg** [comment]
Right now getDeviceName is not returning the custom phone name we need to talk to Oguz.

**Comment by DrJukka** [comment]
Discussed in standup. Checked that the device name can be found from some devices, has concerns that it might not be available on all, and there might not be standard way on setting it.

Thus decision is to use Bluetooth name instad, so we need to:-
- get the Bluetooth name added after the model name in GetDeviceName() function.
- make sure each device has unique Bluetooth name

**Comment by yaronyg** [comment]
Oguz is working on this now. The question is if we can get the bluetooth name if bluetooth is disabled. If not then we might have to come up with a different approach.

**Comment by obastemur** [comment]
This needs to be part of jxcore-cordova 0.0.8 or implement into thali-cordova temporarily ?

**Comment by yaronyg** [comment]
This must be fixed in 0.0.8 and on Thursday of next week we will upgrade to 0.0.8. But since this is blocking Jukka et al. right now if you can give us a temporary work around we can stick in thali-cordova that would be great.

**Comment by obastemur** [comment]
We can bind native http://stackoverflow.com/questions/6662216/display-android-bluetooth-device-name to jxcore ?
