### ISSUE TITLE
Create bluetooth binding for Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#3]
We need a binding for the Android Bluetooth transport on Android to Node.js.

**Comment by DrJukka** [comment]
Done, now when the connector is started you need to give it a port number where a HTTP server is listening (plugin can be used to fetch free port number). Any incoming conenctions are automatically connected to the server streams.

And when connection is established from other end, the connected event comes with port number, to which HTTP requests can be made.
