### ISSUE TITLE
We need to beef up our logging of exceptions

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#300]
There is an unhandled exception handler in the bt helper that isn't logging what it sees. We need to fix that.

**Comment by tompaana** [comment]
Review against story_001 branch: https://github.com/thaliproject/Thali_CordovaPlugin/compare/story_001...story_001_tomi

**Comment by yaronyg** [comment]
Needs to test this and then can do a PR

**Comment by yaronyg** [comment]
Please submit as a PR and that will kick off the review process automatically.

**Comment by yaronyg** [comment]
This is redundant to another PR.
