### ISSUE TITLE
Get Unit Tests passing on iOS

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#302]

**Comment by tobybrad** [comment]
in CI.

**Comment by yaronyg** [comment]
98% done on iOS 9!

**Comment by tobybrad** [comment]
Clean test pass for iOS here: https://github.com/ThaliTester/TestResults/blob/549702610b97681_Switch_to_Unit_Tests_tobybrad/test_log.md

**Comment by tobybrad** [comment]
Review here: https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/393#-
