### ISSUE TITLE
Can we create a lot of iOS advertisers?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#315]
The new binding spec requires us to create a new advertiser with a new display name/peerID every time we have new data for people to pick up. Is iOS going to be happy with tons and tons of advertisers being created? Only one should be active at a time however. Please verify.

**Comment by tobybrad** [comment]
Yep.. I think we're good with that. ios9 does seems to have made that issue go away. If we were super paranoid, and we are, perhaps we could establish a max sane rate for doing this and limit accordingly to be extra careful about triggering possible race in Apple's code.
