### ISSUE TITLE
Create quota manager spec

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#319]
This spec will define how we detect roughly how much space the database is taking up and how someone registers to get this notification so they can decide what to do. Right now we are only going to manage quotas on a database level so we don't really care who filled up the database, only that it is full.

**Comment by cicorias** [comment]
this does it: https://github.com/pouchdb/pouchdb-size

The timer has to warn if DB gets too big.

Main node thread - register the callback and the size trigger.

Standard delay...  

- Never want a situation where we wake up the device to check the DB...
- [other] hook the changes feed?
- First call it to check...
-- if not, hook into the changes events.
http://pouchdb.com/api.html#changes

Review: https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext/thali/NextGeneration/replication/thaliSendNotificationBasedOnReplication.js#L317

**Comment by artemjackson** [comment]
# Quota Manager <sub><sup>(?)</sup></sub> Specification

The <sub><sup>(?)</sup></sub> sign in title means that there is no need in extra Quota Manager class.
The class (e.g. `PouchDBDecorator`) that extends PouchDB could notify us about reached size itself.

# Motivation
There should be an ability to be notified when the PouchDB database size
reaches the desired value(s).

# Possible implementation
### Database `sizeCheckPoints` constructor option + event emission
  Define the database size check point as a database constructor option and subscribe for the `databaseSizeReachedCheckPoint` event of the database instance.

  ```
  const db = new PouchDBDecorator('foo', { sizeCheckPoints: [10240, 20480] }); // 10Mb, 20Mb

  ...
  // put some stuff of 11Mb size
  ...

  db.on('databaseSizeReachedCheckPoint', 
    reachedCheckPointValue => console.log(reachedCheckPointValue));  // 10240
  ```
## Implementation details
The `databaseSizeReachedCheckPoint` event should be fired when the database size reached some check point.
#### How often the database size should be checked?
There are some possible variants:
  * Every `n` milliseconds by using `setInterval`.
  * When any I/O operations where done by database.
    * because only I/O operations change the database size.
    * I/O operations can be detected by [changes](https://pouchdb.com/api.html#changes) PouchDB event emitter.
  * When any I/O operations where done by database but using [`debounce`](https://github.com/component/debounce) with specified threshold.

Second and third variants seem to be good.

#### How to determine database size?

Thankfully there is a module [pouchdb-size](https://github.com/pouchdb/pouchdb-size) that does this work for us.

**Comment by yaronyg** [comment]
I think it's a good idea to make this a config on our custom constructor. So I'm fine with the spec and please consider it :lgtm:

I do have a few questions:
- [ ] Have you checked if pouchdb-size actually works on JXcore on a device?
- [ ] Are we sure the project is healthy? It's build configuration is broken. It would be good to talk to Martin (the dev) and see if the project is still considered healthy
- [ ] Looking at the code all this is doing is walking the directory structure and lstating each file to get its size and adding the total together. If memory serves PouchDB keeps all its files in a single folder and the number of files depends on a combination of the size of the DB and its age. My concern though is that this code is making lstat calls which are system calls. This requires a full Node to native transition. It's not super expensive but if we are doing it on each and every change I am worried that the cost could get excessive. We need to do at least a tiny bit of perf measurements on actual phones to see how expensive these calls are and if we need to be smarter than just running on each change. I could imagine a design where we basically say 'we will run no more and no less than every X milliseconds'. So if we get in a change and we haven't seen a change in X milliseconds then we would fire off a pouchdb-size call. But if we get a change and the last call we made to pouchdb-size was Y ms in the past where Y < X then we would wait (X-Y) ms before firing off the next check.

**Comment by artemjackson** [comment]
@yaronyg  I've got the answer for the second question:
> pouchdb-size is in the process of being migrated to the pouchdb-server 
> monorepo. (See: https://github.com/pouchdb/pouchdb-server/pull/143 .) 
> That PR still fails Travis (which is why it's not merged yet), but it's 
> nothing related to pouchdb-size so I presume any build configuration 
> problems are not present in that version. 
> 
> As for future support: I do try to respond to bug reports in any of 'my' 
> plugins, but I'm not working as actively on them as I used to. Mostly 
> they're just stable and only need to change now if one of their 
> dependencies (or PouchDB) has an API change. That said, no guarantees. 
> I'm doing this for fun. 
> 
> Hope that helps, 
> Marten.

**Comment by artemjackson** [comment]
@yaronyg I may be mistaken but we should run the implementation on real devices to answer for the first question

**Comment by artemjackson** [comment]
@yaronyg on the third question your suggestion seems reasonable and I'm going to implement that

**Comment by yaronyg** [comment]
Latency should be a config item and yes we absolutely need to run tests on a device. I don't know if lstat will work on Android and iOS in the way we expect. Work with @baydet and @evabishchevich to get your test running alone on an iOS and Android device.

As for implementing the wait logic, please look at thaliSendNotificationBasedOnReplication._setUpChangeListener which implements pretty much exactly this logic.
