### ISSUE TITLE
Use a JSON library, please don't manually create JSON

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#32]
The code used in Android to talk with the JXCore native layer manually creates JSON objects. This is both error prone and hard to read. It would be better to use a JSON serializer with a native Java object.

**Comment by obastemur** [comment]
PS: When performance is the case, instead of creating JSON, you might consider using primitive types for better performance.

**Comment by yaronyg** [comment]
Fair enough but this is JSON for returning data in JXCore native calls. All of our native calls are "chunky" enough that perf isn't an issue. So in that case I would argue that code cleanliness is more important.

**Comment by DrJukka** [comment]
Did change the implementation to use real JSON APIs, definitely required for string encoding, characters such as line-feed, are not handled right with earlier implementation story_00_juksilve as well as today updated library implementation are both now using real JSON API.
