### ISSUE TITLE
Start work on adding PSK to JxCore TLS (Node.js) TLS

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#329]

**Comment by cicorias** [comment]
Review this stuff:

[https://github.com/thaliproject/thali/blob/yaronyg-patch-4/pages/TechnologyInvestigations/PresenceProtocolBindings.md#transferring-from-notification-beacon-to-tls](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/pages/TechnologyInvestigations/PresenceProtocolBindings.md#transferring-from-notification-beacon-to-tls)

[https://github.com/thaliproject/thali/blob/yaronyg-patch-4/pages/TechnologyInvestigations/PresenceProtocolForOpportunisticSynching.md](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/pages/TechnologyInvestigations/PresenceProtocolForOpportunisticSynching.md)

**Comment by cicorias** [comment]
Possibly add to[JXCore](https://github.com/jxcore/jxcore)

**Comment by cicorias** [comment]
fyi: [WIP is here](https://github.com/cicorias/jxcore/tree/adding_psk)

**Comment by cicorias** [comment]
@yaronyg  I'd guess w/ further testing, cleanup, etc. ~ 5 more days of effort.  blocked on some client side aspects now..

**Comment by yaronyg** [comment]
O.k. so the current estimate works.

**Comment by cicorias** [comment]
some more implementation details [here](https://eprint.iacr.org/2014/037.pdf)

![capture20160120102407242](https://cloud.githubusercontent.com/assets/1080406/12453197/2732ca02-bf60-11e5-8c72-110e1ca57005.png)

**Comment by cicorias** [comment]
work remaining: 2

**Comment by cicorias** [comment]
I am going to close this and add another related story...
