### ISSUE TITLE
Add additional jshint recommendations with .jshintrc

### ISSUE THREAD

**Issue by mpodwysocki** [thaliproject/Thali_CordovaPlugin#331]
Need to add .jshintrc with most of [pouchdb](https://github.com/pouchdb/pouchdb/blob/master/.jshintrc) recommendations

**Comment by mpodwysocki** [comment]
@tobybrad can we get this RI'ed into 001 among others?

**Comment by yaronyg** [comment]
@mpodwysocki Is this done?
