### ISSUE TITLE
Update Android code to match updated interface of BtLibrary

### ISSUE THREAD

**Issue by tompaana** [thaliproject/Thali_CordovaPlugin#345]
The Android connector library interface was updated (see [issue #17 in BtLib project](https://github.com/thaliproject/Thali_CordovaPlugin_BtLibrary/issues/17)) and the Android code in this project needs to be updated accordingly. A code clean up is also required (EDIT: But will create another issue to clean up the code).

**Comment by yaronyg** [comment]
Worked on today, hope to finish by tomorrow
