### ISSUE TITLE
Re-activate all unit tests except for Identity Exchange

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#353]
We had de-activated some tests, mostly because we are working around problems like Android not having a working discovery mechanism. But once we get BLE up and running all existing unit tests but identity exchange need to be re-activated and show to be passing.

**Comment by yaronyg** [comment]
Isn't this now done?

**Comment by vjrantal** [comment]
> Isn't this now done?

In my opinion, this should be still kept open. The disabled tests can be found from https://github.com/thaliproject/Thali_CordovaPlugin/tree/story_001/test/www/jxcore/bv_tests/disabled .

@tobybrad: The test we commented out from `testMultiplex.js` could be also brought back as part of fixing this issue.
