### ISSUE TITLE
Implement new mux layer (TCPServersManager)

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#358]
Please see https://github.com/thaliproject/Thali_CordovaPlugin/blob/story_001/thali/NextGeneration/TCPServersManager.js

# Remaining work:

## thaliTcpServersManager
- [ ] Finish terminateOutgoingConnection and connect to terminateListener in thaliMobileNativeWrapper and surface in thaliMobile

## createNativeListener

- [X] Figure out the maximum call stack size exceeded crashing bug, we know Winston is involved but is this a bug in Winston or some kind of weird loop on our part?
- [x] Review createNativeListener to find all the places where the CBs make bad assumptions
- [x] Punch up the createNativeListener tests to test the weak points where things can fail
- [x] Add test that we properly close incoming connections when they time out
- [x] Fix incomingConnectionState events aren't emitting correct values
- [x] Fix the createNativeListener tests so they will work when we are using the connected test runner
- [X] Check if routerPortConnectionFailed is emitted correctly & fix tests
- [X] Implement terminateIncomingConnection & test
- [ ] Connect terminateIncomingConnection to terminateConnection (whose name we need to change) in thaliMobileNativeWrapper

## createPeerListener:

- [ ] Fix tests in testThaliMobileNativeWrapper that call trivialBadEndtoEndTest, there is a bug there that is sourced somewhere in this code
- [ ] Validate that all of our requirements in jsdoc are met in the code
- [ ] Check if failedconnection is emitted correctly & fix tests
- [ ] Make sure in non-failure scenarios that we don't emit failedconnection, the fact that we call destroy on the mux can cause spurious errors
- [ ] Check to see if we are using any other native methods and if so that they are expecting strings
- [ ] Check all the cbs in the forward connection code for bad assumptions, also check the pipes for possible closed objects
- [ ] Check forward connection weak points to make sure we clean up properly
- [ ] Check the code that creates a listener in response to a peer availability event and make sure that at some point we clean port up.
- [ ] Figure out if the start interface on tcpServersManager really needs to return the local port it is listening on for connections from the native interface. Does or should anyone but tcpServersManager care about that value?
- [ ] Make sure all multiplex streams have a finish handler that calls destroy on the stream so that our clean up code is in close (which isn't guaranteed to always be called).
- [ ] Make sure we have error handlers on all streams and other objects because otherwise we can get unhandled exceptions.
- [ ] In general we should prefer destroy to end for closing most streams in most cases because it guarantees to kill everything regardless of its state.
- [ ] Figure out how we can convince the peer code (e.g. outgoing connections) to behave itself when we are using the connection manager for tests.
- [ ] Add code to test that when we pick the oldest peer to kill we pick the right one because I fixed a bug in the code that indicates we aren't testing this at all.
- [ ] We have outgoing.on('timeout'... but no where do we actually set the timeout so it won't ever fire. We need to set the timeout and test that it works.
- [ ] We don't wait for listen to call a callback proving it is available, isn't that an issue with resolving the promise?

**Comment by tobybrad** [comment]
https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext/thali/NextGeneration/tcpServersManager.js

**Comment by yaronyg** [comment]
We are getting rid of the old iOS code so we don't need this work item anymore
