### ISSUE TITLE
Implement thaliMobile

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#359]
- [x] Start using promise queue within the file to avoid race conditions if calls are coming concurrently from multiple places.
- [x] Subscribe to network changes and write logic to act based on the changes.
- [x] Add calls to `ThaliMobileNativeWrapper`.
- [x] Implement transport-specific heuristics to determine when peer could be marked unavailable (in case we haven't heard about it in a while).

**Comment by vjrantal** [comment]
@yaronyg: The specification at `thaliMobile.js` did not talk about the requirement to use the promise queue (like wifi and native wrapper), but I think that queue should be used. Would you agree with this or was there a reason why queue shouldn't be used?

**Comment by yaronyg** [comment]
It should absolutely use the queue. It will simplify a ton of stuff.

**Comment by vjrantal** [comment]
Missing implementation moved to https://github.com/thaliproject/Thali_CordovaPlugin/issues/582 and rest handled as part of review of https://github.com/thaliproject/Thali_CordovaPlugin/pull/583.
