### ISSUE TITLE
Never do work on the JXcore thread in Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#365]
We have to audit our code to make sure that when we get called on callNative we never do any work on the JXcore thread but instead schedule our work on a different thread, return the callNative call immediately and then later call the registered callback from the other thread.

**Comment by yaronyg** [comment]
I believe we are clean on this one? What do you think @tompaana, can we close?

**Comment by tompaana** [comment]
No hard work is done in JXcore thread. OK to close this.
