### ISSUE TITLE
Never do work on the JXcore thread in iOS

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#366]
We have to audit our code to make sure that when we get called on callNative we never do any work on the JXcore thread but instead schedule our work on a different thread, return the callNative call immediately and then later call the registered callback from the other thread.

**Comment by vjrantal** [comment]
@yaronyg, @tobybrad: Not sure if this is relevant to this issue, but when I start the unit test app on iOS, I noticed something like this gets printed:

```
2016-02-23 09:12:20.528 ThaliTest[661:892834] THREAD WARNING: ['JXcore'] took '10247.144043' ms. Plugin should use a background thread.
```
A longer debug output with more context at https://gist.github.com/vjrantal/d939a743b693eeacbf63.

**Comment by yaronyg** [comment]
One wonders if we initialize JXcore on the main thread.
