### ISSUE TITLE
Run desktop tests in CI

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#386]
Run the tests that work on desktop in the CI.

This makes sense as a normal quality practice, but also helps protect the real device resources in CI from unintended broken code. Running the desktop tests would act as first quality gate to to check that syntax errors / typos and such don't end up creating builds that potentially consume the full CI timeout of device resources since we don't have a capability currently to cancel ongoing test runs.

**Comment by vjrantal** [comment]
Depends on https://github.com/thaliproject/Thali_CordovaPlugin/issues/385.

**Comment by yaronyg** [comment]
The idea is that we would add to our existing build script 'npm test' (which means we need to make that actually work) and if the local npm test run on the VM that is doing the build should fail then we will abort the whole test and not waste a bunch of time running code on devices that will just fail.
