### ISSUE TITLE
Get rid of leveldown dependency (and only use leveldown-mobile)

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#394]
This is more of an "optimization" to get rid of unneeded dependencies and to be closer on the "production environment" in desktop testing. See https://github.com/jxcore/jxcore/issues/719#issuecomment-168690620 what triggered creating this issue.

**Comment by yaronyg** [comment]
Are there any perf penalties to use leveldown-mobile on the desktop? I'm guessing the answer is no. So the only real impact of this is that it almost certainly means that now Thali will only run on the desktop using JXcore? I'm o.k. with that but I was curious.

**Comment by vjrantal** [comment]
I haven't tested myself, but based on the [leveldown-mobile travis script](https://github.com/Level/leveldown-mobile/blob/master/.travis.yml) it should work also with node.

I don't have a strong opinion about which way we should go and from my perspective, we can very well leave the dependency as is.

**Comment by yaronyg** [comment]
I am biased towards removing dependencies we don't need.
