### ISSUE TITLE
Integrate PSK TLS support in Node to Thali

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#395]
Once #240 is handled we need to make sure the replication manager can use the PSK to establish a TLS connection via PouchDB.

**Comment by cicorias** [comment]
@yaronyg id' say 3 - 5 days... given context switches

**Comment by yaronyg** [comment]
Don't think about context switches. We aren't looking for 'work time' not 'calendar time'. E.g. how long do you think the work will take you if you just measured the time you actually worked on it. Trying to predict estimates with your schedule (in terms of calendar time) is hopeless. :)

**Comment by cicorias** [comment]
Verified that PouchDB along with express-pouchdb server will work with new tls/PSK implementation..

https://github.com/cicorias/PskReplicant

This also requires the build of jxcore that has PSK which is an outstanding PR
https://github.com/cicorias/jxcore/tree/adding-psk-tls
https://github.com/jxcore/jxcore/pull/813
