### ISSUE TITLE
Implement Bluetooth transport for Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#397]
Please see https://github.com/thaliproject/thali/blob/gh-pages/pages/documentation/PresenceProtocolBindings.md#implications-of-bluetooth-and-multi-peer-connectivity-frameworks-mpcf-tcpip-binding-approaches and https://github.com/thaliproject/thali/blob/gh-pages/pages/documentation/PresenceProtocolBindings.md#the-bluetooth-handshake-and-binding-tcpip-to-bluetooth

**Comment by tompaana** [comment]
advertiseData MUST be set to:

    addManufacturerData() - This MUST NOT be set. We need all the space in the BLE Advertisement we can get.
    addServiceData(serviceDataUuid, serviceData) - serviceDataUuid MUST be set to the Thali service's BLE UUID and serviceData MUST be set to the single byte "0" followed by the BLE UUID as a byte stream.
    addServiceUuid(serviceUuid) - serviceUuid MUST be set to the Thali service's BLE UUID.
    setIncludeDeviceName() - Must be set to false. We need the space.
    setIncludeTxPowerLevel() - Must be set to false. We need the space.

When calling startAdvertising() the scanResponse argument MUST NOT be used as we do not support a scanResponse.
If one constructs the advertisement data as per current instructions, the data size is too long (more than 31 bytes): `[mServiceUuids=[9ab3c173-66d5-4da6-9e23-e8ce520b479b], mManufacturerSpecificData={}, mServiceData={9ab3c173-66d5-4da6-9e23-e8ce520b479b=[0, -102, -77, -63, 115, 102, -43, 77, -90, -98, 35, -24, -50, 82, 11, 71, -101]}, mIncludeTxPowerLevel=false, mIncludeDeviceName=false]`

**Comment by tompaana** [comment]
Created a separate issue for handshake protocol: #526
