### ISSUE TITLE
Add support for installing jxcore-cordova plugin using JXC

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#411]
We need to clean up our existing install so it uses JXC. Ideally we would also detect if jxcore-cordova has already been installed and not re-install. Not sure if JXC does that automatically or not.

**Comment by vjrantal** [comment]
Implementation is done and this has been tested to work. However, there is still an issue that happens sometimes in CI that blocks merging this in https://github.com/jxcore/jxc/issues/6 .
