### ISSUE TITLE
How do we debug through a PSK connection?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#414]
Go think through how to debug this

**Comment by cicorias** [comment]
@yaronyg I'd look at this as let's timebox how much we document for now..  again 3 - 5 days.

**Comment by yaronyg** [comment]
So far this bizarrely enough hasn't mattered. Our test environment lets us test both ends of the connection and so we debug the machines and not the link itself. So I'm going to close this until it actually blows up.
