### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by tompaana** [thaliproject/Thali_CordovaPlugin#422]
Running the build script fails on Windows (using MinGW):

```
npm ERR! leveldown@1.4.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.4.3 install script.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.3.9600
npm ERR! command "c:\\Program Files (x86)\\JXcore\\jx.exe" "c:\\Users\\<username>\
\.jx\\npm" "install" "--build-from-source"
npm ERR! cwd c:\work\projects\thali\ThaliTest\www\jxcore
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
```

Related: #394

**Comment by vjrantal** [comment]
After doing some debugging, I think this might not be an issue with the `leveldown` package since I seem to be getting an error also with other packages after updating jxcore. Here https://gist.github.com/vjrantal/a0097fb4aba8720f9120 is a more detailed error message.

@obastemur: Can it be that after updating jxcore, one must also install Visual Studio 2013 (which seems to be the newest listed in the node-gyp version that jxcore uses)?

**Comment by vjrantal** [comment]
@tompaana: Can you confirm was this an error you started getting after updating jxcore? Were you able to build on this machine before the update? Do you have only Visual Studio 2015 installed on the machine?

**Comment by tompaana** [comment]
The same error before and after JXcore. I was able to build with the very same machine before and all I did was to update Cordova. But I think it was some change in Thali that broke it.

**Comment by obastemur** [comment]
```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the compon
ent to the system path if it is installed elsewhere.  [C:\Users\vjrantal\AppData\Local\Temp\leveldown-mobile-test\node_modules\leveldown-mobile\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the compon
ent to the system path if it is installed elsewhere.  [C:\Users\vjrantal\AppData\Local\Temp\leveldown-mobile-test\node_modules\leveldown-mobile\build\binding.sln]
```
from @vjrantal 's gist.

**Comment by obastemur** [comment]
BTW; confirmed it works without an issue (0.3.1.0) 'jx install leveldown-mobile'

**Comment by vjrantal** [comment]
> BTW; confirmed it works without an issue (0.3.1.0) 'jx install leveldown-mobile'

@obastemur: I think the issue is with `jx npm install leveldown`. Apologies for the gist earlier which was very misleading. I posted that from a machine that doesn't have Visual Studio 2013 installed so I couldn't even build `leveldown-mobile`.
