### ISSUE TITLE
Android build fails if platform added after thali installation

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#431]
In our build scripts, we first add android and ios platforms and then install thali. This works fine.

However, it thali is installed first and platform added afterwards, a build failure occurs.

The root cause is in the difference in the Cordova hooks run order between these scenarios.

**Comment by yaronyg** [comment]
For whatever it's worth we were fully aware of this and decided not to care. We had so many issues with getting the build to work properly that we didn't want to spend more time trying to figure this out. We are under really tight time constraints now so please don't make the world perfect, just good enough. :)
