### ISSUE TITLE
Need to check Android code's thread safety

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#46]
It's unclear if the code in Thali_CordovaPlugin as well as the code in Thali_CordovaPlugin_BtLibrary is actually thread safe or not. I need to investigate.

**Comment by DrJukka** [comment]
thread safe implementation updated to story_00_juksilve

**Comment by yaronyg** [comment]
Please submit the change as  PR so I can review. Thanks!

**Comment by yaronyg** [comment]
Actually I take that back. You can close this for now and when you submit a change from story_00_juksilve to story_00 then we can review the PR.
