### ISSUE TITLE
Uncaught exception on devices that don't support BLE advertisement

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#460]
Can be reproduced with the unit test app. An example log output at https://gist.github.com/vjrantal/e5170266b911df889085.

**Comment by yaronyg** [comment]
Please verify and if o.k. then close

**Comment by vjrantal** [comment]
@tompaana: I checked the CI logs of the build where you updated to latest library (https://github.com/thaliproject/Thali_CordovaPlugin/pull/503#issuecomment-176840979) and it seems like for some reason, we are not getting the callback always called to `Mobile('IsBLESupported').callNative`.

The reason I suspect is, because of these two greps:

```
$ grep "JXcore engine is ready" thali* | wc -l
      12
$ grep "BLE advertisement is " thali* | wc -l
       8
```

Above tells that we started our app on 12 Android devices, but only 8 has a print that we print in the JS code after we get the callback.

The reason for above might be also elsewhere than in the Java code, but could you have a look?

**Comment by vjrantal** [comment]
@tompaana: And as reference, we call the function in `testUtils.js` with the following code:

```
// Below is only for logging purposes.
  // Once we have had the BT off and we just turned it on,
  // we need to wait untill the BLE support is reported rigth way
  // seen with LG G4, Not seen with Motorola Nexus 6.
  setTimeout(function () {
    Mobile('IsBLESupported').callNative(function (err) {
      if (err) {
        console.log('BLE advertisement is not supported: ' + err );
        return;
      }
      console.log("BLE advertisement is supported");
    });
  }, 5000);
```

Note the comment made by Jukka in case that is relevant and the fact that we call this API 5 seconds after the app is loaded (not sure if that is relevant).

**Comment by tompaana** [comment]
With the current implementation I believe you can check if the BLE advertisements are supported even when Bluetooth is disabled.

**Comment by tompaana** [comment]
Related issue is #594, but this is invalid now.
