### ISSUE TITLE
Do we have an uncaught promise reject handler?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#473]
The promise queue I created is throwing an unhandledRejection error which I believe isn't right. I think there is actually a flaw in the lie promise library I'm using. So I have disabled the failure in the test for now and am using this bug to track the issue. I have filed https://github.com/calvinmetcalf/lie/issues/30 with lie to see if the issue is on their end.

**Comment by yaronyg** [comment]
Turned out to be a bug in lie and has now been fixed.

**Comment by mattpodwysocki** [comment]
@yaronyg good to know that checking versus ES6 was a good idea 😄
