### ISSUE TITLE
Unit test execution sometimes gets stuck on devices

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#483]
See example from https://github.com/ThaliTester/TestResults/blob/56672827039a409__472_Promise_Queue_yaronyg/iOS_Iphone5s-1.md where an iOS device doesn't proceed from the first test.

@tobybrad: This is the issue I talked you about earlier over Skype. Based on our investigation, the test itself is not broken, but the root cause would be in the way how currently the test server coordinates tests and events related to that over socket.io.

**Comment by yaronyg** [comment]
I know @tobybrad just had a bug that caused the coordination server to get stuck but I believe that was an error in the test and not the infrastructure. Are we still seeing this bug or can I close?

**Comment by vjrantal** [comment]
This has already been fixed by @tobybrad and we haven't seen any issues in this regards for a while.
