### ISSUE TITLE
We should centralized on Leveldown-Mobile

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#497]
In theory this issue will be addressed by #422 but just in case it isn't I wanted to call it out separately. Right now we install both Level Down and Level Down-Mobile. This is bad because it wastes space and requires longer to build in order to build both. The good news is that Level Down-Mobile should be able to run anywhere that LevelDown can so in theory we can get rid of LevelDown everywhere. The bad news is that there is a JXcore bug that causes LevelDown-Mobile to crash on the desktop. See [here\(https://github.com/jxcore/jxcore/issues/719) so until that is resolved we can't do anything here.

**Comment by vjrantal** [comment]
I'd agree with this one, but I think this could be seen as a duplicate of https://github.com/thaliproject/Thali_CordovaPlugin/issues/394.

**Comment by yaronyg** [comment]
Closing as a dupe of #394
