### ISSUE TITLE
Make PromiseQueue into a stand alone NPM package

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#498]
Matt pointed out that this would be a really useful package to have in NPM for other folks to leverage. We should do this work as part of technical debt.

**Comment by mattpodwysocki** [comment]
@yaronyg fair enough, thinking it would probably take about a half day max to create the package and upload to NPM complete with readme, docs and tests.

**Comment by yaronyg** [comment]
Exactly, a 1/2 day we don't have.
