### ISSUE TITLE
minimum Android SDK Decision

### ISSUE THREAD

**Issue by obastemur** [thaliproject/Thali_CordovaPlugin#5]
This plugin requires min SDK 16 (4.1) BLE introduced with 18 (4.3) The requirement document says min 4.4 (19) 

So, any objection for 19 ?

**Comment by yaronyg** [comment]
Actually we ideally need to go all the way back to 16 which gives us 89% of the market.
Also we do not require BLE. It's strictly a nice to have. What we require is Wi-Fi Direct discovery and Bluetooth. Those were added in 16 and 5 respectively. So we really should set our minimum to 16.

@DrJukka any comment on what minimum SDK we should support for our Cordova plugin?

**Comment by DrJukka** [comment]
Insecure BT has failed few times with API level 16 device, thus not recommending to use it. I have successfully used all API parts with API level 18 (Nokia X2) device.

BLE I have no opinion yet, though I di remember few people saying that its not Great with API level 18, suggesting that it works better on 19.

**Comment by yaronyg** [comment]
BLE is a nice to have and we need to cover as much of the market as possible. Still... if we have to go all the way to 18 then we might as well go to 19. 18 is only 5.2% of the market at this point. Bummer.
