### ISSUE TITLE
Implement discoveryAdvertisingStateUpdateEvent in thaliWifiInfrastructure

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#529]
It was discussed that the event `discoveryAdvertisingStateUpdateEvent` defined in `thaliWifiInfrastructure.js` is not required in first phase so it was not implemented yet.

**Comment by yaronyg** [comment]
@vjrantal Didn't we actually end up implementing this anyway in which case we can close this bug?

**Comment by vjrantal** [comment]
That is right.
