### ISSUE TITLE
On iOS networkChanged events don't accurately reflect the right state

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#536]
In `vNext` branch, the networkChanged events should be fired if Wifi or Bluetooth HW gets enabled or disabled. Based on manual testing, the event isn't fired according to what one would expect when toggling Wifi or Bluetooth using the iOS "Control Center" (the menu that can be swiped from the bottom of the screen).

**Comment by vjrantal** [comment]
@tobybrad: Here is a clip from the specification at thaliMobileNativeWrapper.js that I'd need to be able to test on iOS devices (see the MUST statement):
```
/**
 * Provides a notification when the network's state changes as well as when our
 * use of the network changes, specifically when discovery or
 * advertising/listening starts and stops. This event MUST fire with the current
 * network state when the first subscription to the event is received.
 *
 * @public
 * @event networkChangedNonTCP
 * @type {Object}
 * @property {module:thaliMobileNative~networkChanged} networkChangedValue
 */
```

**Comment by vjrantal** [comment]
@tobybrad mentioned in Slack that the issue in the description was not yet fixed, but only the referred MUST part from the specification so reopening this.

**Comment by yaronyg** [comment]
@baydet I'm assigning this to you to make sure we don't repeat this error in the new code.
