### ISSUE TITLE
Test in testThaliNotificationBeacons.js sometimes fails

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#539]
To reproduce:
```
$ git checkout vNext
$ ./thali/install/setUpDesktop.sh
$ cd test/www/jxcore
$ jx bv_tests/testThaliNotificationBeacons.js
```
The issue happens only rarely, but when it does, there is what it looks like:
```
# setup
# #parseBeacons addressBookCallback returns public key
not ok 19 should be equal
  ---
    operator: equal
    expected: 1
    actual:   2
    at: Test.<anonymous> (/Users/vjrantal/Software/Thali/Thali_CordovaPlugin/test/www/jxcore/bv_tests/testThaliNotificationBeacons.js:404:5)
  ...
```
The easiest way to reproduce that I have found is just to loop the test as long as the error occurs. This can be done with a bash script like:
```
#!/bin/bash

set -e

COUNTER=0
while [  $COUNTER -lt 1000 ]; do
    jx bv_tests/testThaliNotificationBeacons.js
    let COUNTER=COUNTER+1
done
```

**Comment by vjrantal** [comment]
@yaronyg: Here is the issue I mentioned and a bash script (see above comment) to help reproduce.

**Comment by yaronyg** [comment]
Yup, I repro'd this myself. I've now run the test for several minutes in the loop without repo'ing it. But I'm going to include the fix with the PR that Shawn is reviewing since it also deals with the same code.

**Comment by yaronyg** [comment]
I ran it a 1000 times without a repro.
