### ISSUE TITLE
'jx install thali' is not installing the plugin second time

### ISSUE THREAD

**Issue by sreesharp** [thaliproject/Thali_CordovaPlugin#54]
Steps to reproduce the issue
***************************************
1) Create cordova app, and jxcore folder inside www
2) run 'jx install thali'  inside jxcore folder
3) uninstall the thali plugin using (cordova plugin remove org.thaliproject.p2p)
4) run 'jx install thali' inside jxcore folder
Expected result - org.thaliproject.p2p and io.jxcore.node should be there in plugins folder
Actual result - thali plugins are not there in plugin folders

**Comment by yaronyg** [comment]
@sreesharp - I believe this issue is now resolved. Can you please confirm and close?
