### ISSUE TITLE
Improve reliability of the native test

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#549]
Currently, in `testThaliMobileNative.js`, there are tests to try to connect to a peer and to send data between peers. They are written in a way that the Mobile('connect') call is only tried once and if it fails, the test fails.

According to @tobybrad it is the case that on iOS, connect sometimes fails or we lose a peer during data transfer, but are able to re-connect. To take this fact into account, the tests should be improved with some re-connect behavior that survives from these cases.

**Comment by yaronyg** [comment]
I thought you did this work? Can we close this?

**Comment by vjrantal** [comment]
There is now 10 re-tries for the connect, but "no mercy" for the data transfer.

It used to be that Android required some amount of retries for larger data amounts, but it is possible that the BT library has been improved so much that retries aren't needed.

Let's close this and keep monitoring how the data tests behave with latest software stack and open separate issues if further improvements needed.
