### ISSUE TITLE
Couldn't download the btconnectorlib2 package in Windows

### ISSUE THREAD

**Issue by sreesharp** [thaliproject/Thali_CordovaPlugin#55]
Steps to reproduce the issue
*************************************
1) Create a cordova app in Windows 8.1
2) created jxfolder inside www folder
3) Added Android platform using 'cordova platform add android'
4) Installed the plugins using 'jx install thali'
5) build using 'cordova build android'

Expected result - Build should be successful
Actual result -  Couldn't locate the  btconnectorlib2 library, and build failure

**Comment by yaronyg** [comment]
@sreesharp - I believe this issue is now resolved. Can you please confirm and if so close?
