### ISSUE TITLE
Break out admin ACL

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#567]
So it turns out that Rockwell needs the admin ACL for their own Express server (independent of Pouch) so they can control it from inside of their webview. So it would be good if we could specifically take the Admin ACL and publish it as a little baby NPM package. We would then use it in Thali and Rockwell could use it in Stanton. This is ONLY for the admin ACL. Not the beacon or pull replication ACLs.

**Comment by cicorias** [comment]
10-4

**Comment by cicorias** [comment]
@yaronyg  a sample npm package has been published to https://www.npmjs.com/package/salti-admin

Source code here: https://github.com/cicorias/salti-admin

Along with a sample express app using express-pouchdb.

There are nuances in that while it tosses a 401, the PouchDB client just assumes "unknown db error" - so, i believe the proper way to get it tighter integrated is to extend their http adapter (https://github.com/pouchdb/pouchdb/blob/master/src/adapters/http/index.js).
