### ISSUE TITLE
Race condition in ThaliWifiInfrastructure.prototype.start

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#578]
In the start function in ThaliWifiInfrastructure we call getNonTCPNetworkStatus and only once we get a response do we register a handler for the ThaliMobileNativeWrapper emitter's networkChangedNonTCP.

This is a problem because it is possible that in the time between when we called getNonTCPNetworkStatus and when it finally returned to us another change in status could have snuck through without us known. That's why it's standard practice that you first register the event handler and THEN you would call getNonTCPNetworkStatus. But you have to be ready that while you were calling getNonTCPNetworkStatus that you got a more recent event. The way to handle that is that you always give precedence to what you get via the emitter over the response to your call to getNonTCPNetworkStatus.

**Comment by vjrantal** [comment]
Fixed in https://github.com/thaliproject/Thali_CordovaPlugin/pull/583.
