### ISSUE TITLE
npm ERR! thali@2.1.0 postinstall: `"jx installCordovaPlugin.js"` npm ERR! Exit status 1

### ISSUE THREAD

**Issue by arniesaha** [thaliproject/Thali_CordovaPlugin#598]
Hello Guys, 

Been trying to setup the cordova thali plugin. But I receive this NPM error when firing this command: jx install thali --autoremove "*.gz" --save

My Environment: 
OS: Windows 10 x64
Android: Installed Platform 5.1.1
JXCore: v0.3.1 x64
Cordova: 6.0.0

I created an empty app.js under the jxcore folder, after adding android platform under the cordova project. Initialized the package.json and hit: jx install thali --autoremove "*.gz" --save 

This does it's business, but @ jx installCordovaPlugin.js fails with status 1

Trying to install jxcore-cordova version: 0.0.8
The `cordova info` test failed: Error: Current working directory is not a Cordova-based project.

Error: Current working directory is not a Cordova-based project.

Starting to download Thali Cordova plugin from: https://codeload.github.com/thaliproject/Thali_CordovaPlugin/zip/npmv2.1.0
Adding Thali Cordova plugin from: C:\Users\arnab.saha\thaliDontCheckIn\Thali_CordovaPlugin-npmv2.1.0
Failed with - Error: Command failed: Error: Current working directory is not a Cordova-based project.

npm WARN EPACKAGEJSON cuttingchai@1.0.0 No repository field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\JXcore\\jx.exe" "C:\\Users\\arnab.saha\\.jx\\npm\\bin\\npm-cli.js" "install" "--loglevel" "http" "thali" "--save" "--build-from-source"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! thali@2.1.0 postinstall: `"jx installCordovaPlugin.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thali@2.1.0 postinstall script '"jx installCordovaPlugin.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thali package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     "jx installCordovaPlugin.js"
npm ERR! You can get their info via:
npm ERR!     npm owner ls thali

Could anyone point me to what is going with my build? 
Thanks in advance!

Arnab

**Comment by czyzm** [comment]
Just trying to get around same issue and some tips from my side:
- create the package.json file under the jxcore folder
- issue the jx install thali --autoremove "*.gz" --save  from your jxcore folder

**Comment by arniesaha** [comment]
I did create the package.json under the jxcore folder and issued the jx install thali command from the jxcore folder as well. The reported error persists!

**Comment by yaronyg** [comment]
@arniesaha First let me apologize for how painful this is in general. We are trying to get to our first deliverable and so are heads down on that and honestly we haven't made the install process as easy as it should be. In this case the error looks like Cordova doesn't recognize that you are in a Cordova project. Can you go anywhere inside of your project and type 'cordova info' at the command line? What does it output?

**Comment by arniesaha** [comment]
Hey @yaronyg !

Thanks for looking into this. 'cordova info' under the jxcore or the parent path both return:

Collecting Data...


Node version: v0.10.40

Cordova version: 6.0.0

Config.xml file:

<?xml version='1.0' encoding='utf-8'?>
<widget id="com.test.thalitest" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>ThaliTest</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
</widget>


Plugins:

cordova-plugin-whitelist

Error retrieving Android platform information: Error: cmd: Command failed with exit code 1 Error output:
'android' is not recognized as an internal or external command,
operable program or batch file.

**Comment by vjrantal** [comment]
@arniesaha: One thing that I wanted to ask is in which folder you run the install command to install thali?

Below, I am writing an example set of commands that is probably the simplest setup steps that you need before installation. If possible, please run these into your environment and paste the full output (as a gist, for example) and I'll try to help figuring out what the issue is:

```
$ cd /tmp
$ cordova create SomeApp
Creating a new cordova project.
$ mkdir SomeApp/www/jxcore
$ cd SomeApp/www/jxcore/
$ jx npm install thali
... lots of output ...
```

**Comment by arniesaha** [comment]
@vjrantal Thanks! I made an error and was not running the install command under cordovaApp/www/jxcore folder, instead under cordovaApp/jxcore !! 

Its installed correctly now. Is there a sample app of the thali implementation I could check? Since this is a plugin, there's only the device ready screen that launches in the build. Should this be something I should be looking at https://github.com/thaliproject/postcardapp?

Thanks,
Arnab

**Comment by vjrantal** [comment]
@arniesaha: Good that the issue got solved!

The postcardapp is an example app that shows thali usage.
