### ISSUE TITLE
Too long advertise data on Android

### ISSUE THREAD

**Issue by tompaana** [thaliproject/Thali_CordovaPlugin#608]
@vjrantal caught this issue. For some weird reason the advertise data is too long and because of that the BLE peer discovery cannot be started. Haven't been able to reproduce this though.

https://gist.github.com/vjrantal/17c0cdc59c94a2939814

**Comment by tompaana** [comment]
In this particular case the scanner also fails to start and the error code provides a clue: `,E/org.thaliproject.p2p.btconnectorlib.internal.bluetooth.le.BleScanner( 5686): onScanFailed: Feature is not supported, error code is 4`

**Comment by vjrantal** [comment]
Seen again in CI so requires further investigation.

**Comment by tompaana** [comment]
Relevant information from logs:

First I was like...

```
I org.thaliproject.p2p.btconnectorlib.internal.bluetooth.le.PeerAdvertisementFactory: createAdvertiseDataToServiceData: Service UUID: "b6a44ad1-d319-4b3a-815d-8b805a47fb51", Bluetooth MAC address: "E0:DB:10:14:E2:C0"
V org.thaliproject.p2p.btconnectorlib.internal.bluetooth.le.PeerAdvertisementFactory: createAdvertiseDataToServiceData: Service data (length is 7 bytes): 00 E0 DB 10 14 E2 C0
V org.thaliproject.p2p.btconnectorlib.internal.bluetooth.le.PeerAdvertisementFactory: createAdvertiseDataToServiceData: Created: AdvertiseData [mServiceUuids=[b6a44ad1-d319-4b3a-815d-8b805a47fb51], mManufacturerSpecificData={}, mServiceData={b6a44ad1-d319-4b3a-815d-8b805a47fb51=[0, -32, -37, 16, 20, -30, -64]}, mIncludeTxPowerLevel=false, mIncludeDeviceName=false]
I org.thaliproject.p2p.btconnectorlib.internal.bluetooth.le.BleAdvertiser: setAdvertiseData: AdvertiseData [mServiceUuids=[b6a44ad1-d319-4b3a-815d-8b805a47fb51], mManufacturerSpecificData={}, mServiceData={b6a44ad1-d319-4b3a-815d-8b805a47fb51=[0, -32, -37, 16, 20, -30, -64]}, mIncludeTxPowerLevel=false, mIncludeDeviceName=false]
```
...but then...

```
E org.thaliproject.p2p.btconnectorlib.internal.bluetooth.le.BleAdvertiser: onStartFailure: The advertise data to be broadcast is larger than 31 bytes, error code is 1
```

The device in question is Samsung Galaxy Note 4. Could it have a weird chipset doesn't quite support what we are trying to do?

**Comment by tompaana** [comment]
Now @vjrantal got this reproduced locally. This is a freakin' HEISENBUG!

**Comment by vjrantal** [comment]
> Now @vjrantal got this reproduced locally.

Seems to be currently 100% local repro on an HTC device on which Thali with BLE has worked in the past. I tried rebooting the device in case this would be just a weird state in the BT stack, but the same issue persists also after a reboot.

**Comment by tompaana** [comment]
Cannot repro on Nexus 6, LG G4 or LG Flex2.

**Comment by tompaana** [comment]
Library version 0.3.0 now contains a workaround for this.
