### ISSUE TITLE
Build and create a deploy point for Thali JXcore

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#610]
I talked with Oguz and he said we need to do our own build. So can you please figure out:
1. How do build for Windows, Mac, Android and iOS. In each case, we just want Spider Monkey. Do you have access to a Mac?
2. Where do we want to host these binaries? Anywhere reliable will do. Perf does matter since every test run we do will use these binaries.

**Comment by cicorias** [comment]
Are we doing a CI or just build and release - with no continuous updates - and only on-demand?
1. I don't have a spare Mac for CI. So, either we can do a hosted one or build/buy. 
2. probably use Azure storage or S3 depending upon scriptability...  May mirror on GitHub though.

**Comment by yaronyg** [comment]
This would be no continuous updates, just on-demand. Literally build on some box somewhere and then push it up to a cloud location that has solid perf world wide. So you wouldn't need a 'spare' mac. You would just need 'a' mac that you can use once and then upload the binaries.

**Comment by cicorias** [comment]
If somebody could review and confirm the iOS build:

https://jxcore.blob.core.windows.net/jxcore-release/0312/jx_iosFATsm.zip
