### ISSUE TITLE
Add Marshmallow device to testing

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#633]
Make sure we update at least one device to marshmallow and put in the new ADB command to enable us to give the app permissions.

**Comment by tompaana** [comment]
The ADB command (tested and verified) for granting permissions: `adb shell pm grant <app name> android.permission.<permission name>` e.g. `adb shell pm grant com.test.thalitest android.permission.ACCESS_COARSE_LOCATION`

**Comment by yaronyg** [comment]
I'm closing this in favor of 30 which Marek pointed out.
