### ISSUE TITLE
We are getting bad closes on syncRetry

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#64]
Take a look [here](https://gist.githubusercontent.com/mohlsen/b78dc8cf18b112b01f67/raw/c410cbc0ea427807c64650793628668128bf641b/device%25201%2520-%2520can%2520send%2520postcards.txt) specifically at the 8-10 09:50:24.741 entry where we are getting Error!: Not Running exceptions. This is a close call on a socket that is already closed. This shouldn't happen. It means our state model is broken since we should know if the socket is already closed.

**Comment by mattpodwysocki** [comment]
@yaronyg is this a fix to be bolted onto story 0 or moved to story 00?

**Comment by yaronyg** [comment]
Let's figure out what the fix is. The important part is NOT the throw/catch. The important part is that there is something fundamentally wrong with how we are managing connections because we shouldn't have gotten that error in the first place.

**Comment by yaronyg** [comment]
As a side note, if you look at the log it seems like the real issue is that we got a Bluetooth error and we aren't handling it correctly. It's sort of an existence proof that our testing isn't modeling how connection failure actually happens. So I personally wouldn't sleep well until we can recreate this bug in a test and only THEN "fix" it.

**Comment by yaronyg** [comment]
@mattpodwysocki - Does this bug still exist?

**Comment by mattpodwysocki** [comment]
@yaronyg this error is not actually Cordova nor the native layer, but the node.js/JXcore layer that is throwing this error.   And not as far as I know does it exist.

**Comment by yaronyg** [comment]
So can we close the bug?

**Comment by mattpodwysocki** [comment]
@yaronyg yes, let's close this
