### ISSUE TITLE
Return proper error in case Android device does not have required capabilities

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#641]
Proposal is to add a new error message to thaliMobileNativeWrapper.start that is returned if capabilities don't match.

**Comment by vjrantal** [comment]
@yaronyg: Let me know what you think about this or if I have overlooked and this is already specified, but my brain just doesn't remember..

**Comment by yaronyg** [comment]
This is what the networkChanged event is for. It specifies what technologies are available and identifies what requirement level we have for each. So, for example, if we get anything but ON or DO_NOT_CARE then we have a problem and know we can't run on that device. So the real question is - do we have a test for this where we turn off bluetooth or wifi or whatever and see if we get the right result back? We could at least test that on Android.

**Comment by vjrantal** [comment]
Thanks for reminding that `networkChanged` is the "public API" for this functionality. I added a basic test at https://github.com/thaliproject/Thali_CordovaPlugin/pull/612/commits/ece3ba07697fefbb09157c7f99e564b7cf4db2f2 which seems to work on a device that doesn't support the BLE as we require.

**Comment by yaronyg** [comment]
@vjrantal So does that mean we can now close this?

**Comment by vjrantal** [comment]
Yes. I think the basic test covers it.
