### ISSUE TITLE
10 connection retries was not enough for two Android devices connected

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#642]
Reproduced locally when running unit test app with two Android devices.

Logs zipped here:
[1458287264.zip](https://github.com/thaliproject/Thali_CordovaPlugin/files/179239/1458287264.zip)

**Comment by vjrantal** [comment]
@tompaana requested logcat logs without filtering so here we go:

[1458296523.zip](https://github.com/thaliproject/Thali_CordovaPlugin/files/179445/1458296523.zip)

The logs are from a different run than before, but the issue seems similar.

One question I have is why connect starts to return:
```
Connect returned an error: startListeningForAdvertisements is not active
```
When all we should be doing from node is connect retries. What makes the state inactive?

**Comment by tompaana** [comment]
JXcore re-initializes itself (could be it's the whole `MainActivity`). I remember @drjukka saying he had one device, which kept restarting the activity, but he's on vacay now - can verify when he comes back. Branch `vNext_tompaana_608` has LifeCycleMonitor restored and added logging to see if, in fact, the whole `Activity` is restarted.
