### ISSUE TITLE
Operation timeout state error Discovery manager not started

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#649]
Reproduced with unit test app in CI. Device was HTC One M8 and full logs at https://raw.githubusercontent.com/ThaliTester/TestResults/625481245382a4d_More_thaliMobileNativeWrapper_vjrantal/thali06_HTC-HTC%20One%20M8s.md (search `Discovery manager not started` to get to the first occurrence).

**Comment by vjrantal** [comment]
@tompaana: This time it was with the 0.3.0 library version and not about the too long advertisement data.

**Comment by tompaana** [comment]
I see `E org.thaliproject.p2p.btconnectorlib.internal.bluetooth.le.BleScanner: onScanFailed: Feature is not supported, error code is 4` and that error message originates from the OS.
