### ISSUE TITLE
Fix wifiBasedNativedMock for iOS

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#652]
The current mock doesn't appear to follow the rules for the mobile layer. So this bug is to collect all the problems and fix them.

- [x] Change your emergency console.logs to logger.debug so they show up in the coordinator and then figure out how to kill unnecessary connectPeers once the test has passed so we can exit.
- [x] Implement a test that we don't see peerAvailabilityChanged events until one of the start methods is called (this will require the use of the coordinator)
- [x] Finish going through the thaliMobileNativeWrapper and thaliMobileNative specs to make sure that we are following the requirements in the mock and that we test those requirements
- [x] Teach the mock to speak iOS

**Comment by yaronyg** [comment]
@chapko I believe this bug is now effectively a dupe of thaliproject/Thali_CordovaPlugin#903 and we should close it in favor of thaliproject/Thali_CordovaPlugin#903. But can you please check the work items and if you agree then please close this bug?

**Comment by yaronyg** [comment]
@chapko?!?!?!? Can you please respond to the previous question.

**Comment by chapko** [comment]
@yaronyg yes, my bad. I didn't have time to investigate enough the mock to answer this question. But #903 is obviously a duplicate of the last todo item. But I can't say anything about other items

**Comment by yaronyg** [comment]
This has been superseded by thaliproject/Thali_CordovaPlugin#903
