### ISSUE TITLE
Fix OS X V8 build to actually be the V8 build

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#661]
See https://github.com/thaliproject/CI/issues/25#issuecomment-200241341 for background.

My hope would be that we still keep also the SpiderMonkey build, but just host it with a filename that matches the content.

**Comment by cicorias** [comment]
updated the CDN and initiated a purge. I verified jx -jsv is V8 after. SM is still there too
```
curl -o jx.zip http://jxcore.azureedge.net/jxcore/0312/release/jx_osx64v8.zip
unzip jx.zip
cicoriasmbp13@Shawns-MBP:~/Downloads/jx_osx64v8$ ./jx -jsv
Google V8 v3.14.5.9
```

While CDN purge may take time, the direct link to origin is: https://jxcore.blob.core.windows.net/jxcore-release/jxcore/0312/release/jx_osx64v8.zip
