### ISSUE TITLE
When peer port number changes peer availability needs to be toggled

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#675]
TCP servers manager might sometimes change the port number via which a peer is accessible. This might happen without anyone sending a peer unavailability event. In thaliMobile.js we should spot this and first send peer unavailable event (this is missing) and only after that send peer available event (this is already sent).

**Comment by yaronyg** [comment]
With your check in can't we close this?

**Comment by vjrantal** [comment]
Yes. This is now implemented.
