### ISSUE TITLE
Prevent ever getting events based on own SSDP messages

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#684]
This PR https://github.com/thaliproject/Thali_CordovaPlugin/pull/680 fixes the typical case where we want to avoid getting events from ourself when USN changes. However, in the code review, it was discussed that there might be edge cases where the implemented check isn't enough and one might get a peer unavailability change based on a byebye message originating from the peer itself (this isn't critical since the upper layers needs to handle this case anyways).

This issue is about implementing a bullet-proof logic to detect own SSDP messages.

**Comment by yaronyg** [comment]
Specifically what we were thinking is that in the case of SSDP we get a location header. Even if we change our USN (the unique ID) the location header stays the same unless we call stop advertising. So an easy fix could be to just check if we get a notification that contains an unrecognized USN (read: old) but with our current location. Then we can just automatically filter it out.

**Comment by yaronyg** [comment]
@chapko  I believe you fixed this in thaliproject/Thali_CordovaPlugin#1103. If you agree then please close this issue.

**Comment by yaronyg** [comment]
@chapko?

**Comment by chapko** [comment]
Yes it is fixed, but I wouldn't call it bullet-proof. It just stores several recently used peer identifiers and ignores all incoming SSDP messages containing this ids. However it stores only limited number of own identifiers (I set it to 10 in thaliConfig) so if you manage to stop and start advertising 10 times before you get your own notification from the 1st stop, then it will be detected as if it is another peer. It is unlikely to happen in the real world scenario and hardly can be abused, so I'm just closing this issue.
