### ISSUE TITLE
We really need to use Shrinkwrap

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#758]
npm shrinkwrap lets us freeze all of the dependencies of all our dependencies to specific versions. The point is that this ensures that two people running the same version of Thali will have the same version of all our dependencies. Otherwise with semver it's possible for two people to install the same version of Thali but end up with different versions of various sub-dependencies because of new releases within those sub-dependencies. This is the sort of thing that makes debugging into a screaming nightmare.

**Comment by artemjackson** [comment]
I found next folders that probably should be shrink-wrapped:
* `test/tesServer`
*  `test/www/jxcore`
*  `thali`
* `thali/install`
Could you clarify whether we need to shrink-wrap them all?

**Comment by yaronyg** [comment]
We should shrinkwrap everything. That way we always have reproducible environments across test and production.
