### ISSUE TITLE
Why is leveldown mobile failing to install on Windows?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#763]
If you look at https://ci.appveyor.com/project/thaliproject/thali-cordovaplugin/build/1.0.552#L2534 you can see that leveldown mobile is not behaving itself. This is a new behavior that showed up in the last few weeks and we're not sure why since as far as we know none of the dependencies have actually changed. I'm going to try and do some testing on windows just to sniff this out. It might have nothing to do with leveldown-mobile and just be something we screwed up.

**Comment by enricogior** [comment]
@yaronyg can you point me to the scripts used by appveyor to replicate the exact same steps on my dev machine?

**Comment by yaronyg** [comment]
https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_417_1/appveyor.yml

**Comment by enricogior** [comment]
Thank you.

**Comment by yaronyg** [comment]
@enricogior Please see my notes in Slack as at least on my less than clean machine some of the appveyor build steps won't run right. As part of closing this issue we should consider updating the appveyor scripts so they run in a manner that will work on a 'dirty' machine just so that we can point people at the script generically.

**Comment by enricogior** [comment]
The first error caused by the current scripts is:
```
EPERM, mkdir 'c:\Users\cicoriasmbp13
```
the `npmrc` file contained in https://jxcore.azureedge.net/npmjx/npmjx311.tar.gz uses the `Users\cicoriasmbp13` path in several configuration variables.

**Comment by enricogior** [comment]
Removing the npmrc file from https://jxcore.azureedge.net/npmjx/npmjx311.tar.gz is not enough, there are other files that contains the `Users\cicoriasmbp13` path that causes build problems on Windows.

npmjx311.tar.gz needs to be built on a clean machine where the current user's npmrc doesn't contain custom paths since the scripts that create npmjx311.tar.gz use the user's npmrc file.

We may also consider changing the build script to make sure the current user's npmrc is not used in order to avoid the problem in the first place.

**Comment by yaronyg** [comment]
We hope that today we will finally be able to focus on the level down mobile compile error because we turned out to have a bunch of JXNPM related problems that we had to clear out ahead of it so we could finally reach this issue. Enrico is hoping to have an answer on this today.

**Comment by enricogior** [comment]
After some more hacking with npmjx I've finally reached the point where I have a "clean" jxcore + npmjx installation and I can compiling the leveldown-mobile module.
I'm getting the exact same build error seen in appvoyer:
```
C:\Users\enrico\.jx\npm\node_modules\node-gyp\src\win_delay_load_hook.c(31): error C2373:
 '__pfnDliNotifyHook2': redefinition; different type modifiers 
[C:\Users\enrico\.jx\node_modules\leveldown-mobile\deps\leveldb\leveldb.vcxproj]
```

**Comment by enricogior** [comment]
The error only appears when compiling with VS2015, using VS2013 compiles without errors.

**Comment by enricogior** [comment]
The error may be caused by an incompatibility between our version of npm and VS2015.
I tested the fix and it worked.
Should I send the PR to our thaliproject/jxcore repo first or directly to jxcore/jxcore?

**Comment by yaronyg** [comment]
Let's submit it to thaliproject/jxcore so we can do our build out of the official master on thaliproject/jxcore and then we will submit it from there to jxcore/jxcore so they know where it's coming from (e.g. this is a Thali submission).

**Comment by enricogior** [comment]
https://github.com/thaliproject/jxcore/commit/ab1d06b4d6395474b043f9b12bb5fd990ee56e39

**Comment by enricogior** [comment]
The fix is fine, given is the same fix made in npm 3.4.0.
The thing that I'm not confident with is the way npmjx311.tar.gz is recreated, since on my clean machine it seems to be missing a submodule.
Also, recreating npmjx311.tar.gz will get rid of the hardcoded 'C:\Users\cicoriasmbp13' path, that may actually break appvoyer or other build enviroment.

**Comment by yaronyg** [comment]
I think we kinda sorta have to change the npm jx version number. :( Otherwise we won't know when we need to upgrade our local version of jxnpm. And obviously you need to track down that submodule issue. I also wouldn't worry about breaking appveyor. So long as we get rid of the hard coded path then everything should work better, not worse. So I would probably stick all the changes together (e.g. both the leveldown fix and the path fix) and go for it all at once. The less frequently we update our binaries the better.

**Comment by enricogior** [comment]
I was looking at the version number changed and I found that
https://jxcore.azureedge.net/npmjx/npmjxv312.jx
https://jxcore.azureedge.net/npmjx/npmjx312.tar.gz
already exist, so I guess the new version number should be something like 311b for both the proxy and the real npmjx, correct?

**Comment by enricogior** [comment]
The updated npm and npm-proxy modules have been uploaded to azure.
https://jxcore.azureedge.net/npmjx/npmjx311b.tar.gz
https://jxcore.azureedge.net/npmjx/npmjxv311b.jx

The following test succeeded on a clean Windows machine:
 - mkdir C:\build
 - copy jx.exe C:\build\
 - SET NVM_NODEJS_ORG_MIRROR=https://jxcore.azureedge.net
 - SET JX_NPM_JXB=jxb311
 - set PATH=%PATH%;C:\build\
 - cd build
 - jx npm install
 - jx npm install cordova@6.1.0
 - jx npm install leveldown-mobile
 - run two jx scripts to verify that the cordova and the leveldown-mobile modules are loaded by the scripts

I then run a modified version of the appvoyer script, the part where the compilation of leveldown-mobile was failing now passes. But I got two errors:
```
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.test.thalitest
        Name: ThaliTest
        Activity: MainActivity
        Android target: android-23
Android project created with cordova-android@5.1.1
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android
Failed to install 'cordova-plugin-whitelist':Error: cmd: Command failed with exit code 1 Error output:
'node' is not recognized as an internal or external command,
operable program or batch file.
    at ChildProcess.whenDone (C:\jx_win64v8\node_modules\cordova\node_modules\cordova-lib\node_modules\cordova-common\sr
c\superspawn.js:169:23)
    at ChildProcess.emit (events.js:85:17)
    at maybeClose (child_process.js:773:16)
    at Socket.<anonymous> (child_process.js:994:11)
    at Socket.emit (events.js:82:17)
    at Pipe.close (net.js:422:12)
```

after the first error, the install script continued and stopped later on because of this:

```
Trying to install jxcore-cordova version: 0.1.2
Downloading: http://jxcore.azureedge.net/jxcore-cordova/0.1.2/release/io.jxcore.node.jx

Attempt 1 / 3
Progress: Done
Extracting plugin package...
Done.
Removing plugin from project...
Removing plugin from project...
Adding plugin to project...
Adding plugin to project...

Failed with - jxc install exited with code: 1
npm WARN EPACKAGEJSON thali-cordova-plugin-jxcore@1.0.0 No repository field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\jx_win64v8\\jx.exe" "C:\\Users\\enrico\\.jx\\npm\\bin\\npm-cli.js" "--loglevel" "http" "install" "C:/
Thali_CordovaPlugin/thali" "--save" "--no-optional"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! thali@2.1.0 postinstall: `"jx installCordovaPlugin.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thali@2.1.0 postinstall script '"jx installCordovaPlugin.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thali package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     "jx installCordovaPlugin.js"
npm ERR! You can get their info via:
npm ERR!     npm owner ls thali
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ThaliTest\www\jxcore\npm-debug.log
compilation aborted
```

The first error log indicates node.js is required,  I need to figure out what exact version of node.js should be installed.

**Comment by enricogior** [comment]
Fixed all the remaining issues, the build now completes successfully:
```
BUILD SUCCESSFUL

Total time: 1 mins 34.592 secs
Built the following apk(s):
        C:/ThaliTest/platforms/android/build/outputs/apk/android-release-unsigned.apk
Remember to start the test coordination server by running jx index.js
```

**Comment by enricogior** [comment]
Manual step to get the build to pass:
 - create a symbolic link jx.exe -> node.exe (or simply copy jx.exe to node.exe)
With that step, we can now do the build without requiring node.js.

Other steps required to have the build environment up and running:
 - download the Android SDK
 - set ANDROID_HOME=C:\android-sdk
 - set PATH=%PATH%;%ANDROID_HOME%\tools;%ANDROID_HOME%\platform-tools
- download gradle
 - set PATH=%PATH%;C:\gradle-2.14.1\bin\

**Comment by enricogior** [comment]
PR submitted: https://github.com/thaliproject/jxcore/pull/15
Files updated:
 - https://jxcore.blob.core.windows.net/jxcore-release/0312/release/jx_win64v8b.zip
 - https://jxcore.blob.core.windows.net/jxcore-release/npmjx/npmjx311b.tar.gz
 - https://jxcore.blob.core.windows.net/jxcore-release/npmjx/npmjxv311b.jx
