### ISSUE TITLE
Please test if we can depend on MPCF as a full mux replacement

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#767]
Note: MPCF == Multipeer Connectivity Framework

The goal of this bug is to determine if we can directly bridge TCP/IP connections from the node layer to the iOS native layer by mapping each TCP/IP connection's individual input/output stream to pairs of 'virtual sockets' in the MPCF layer. 

A 'virtual socket' is a pair of output streams going in each direction (e.g. an output stream from A to B and from B to A) that we will map to an individual TCP/IP connection's two streams.

To test if this goal is possible we need to write a test application that does the following:
1. Use two phones, each phone MUST run identical test software doing identical things with the exception that it's fine to just anoint one phone as the phone that will invite the other phone to a MCSession
2. Each phone MUST open N output streams at the MPCF layer to the other phone (where N should default to 20). Over each of these output streams the phone MUST output Y bytes of randomly generated data (Y can start at say 10 MB). Each group of bytes MUST be sent in randomly sized buffers from 1 to 4KB in size. The randomly sized buffers simulate TCP's behavior of sending different buffer sizes. Each phone MUST then wait for the other phone to echo back the data it sent and then the phone MUST confirm that it was echoed back the same data it was sent. When all N connections successfully send and get echoed back Y bytes then the test is a success on that phone.
3. Each phone MUST listen for incoming streams from the other phone and MUST generate a matching outgoing stream that echoes the bytes received. The echoed bytes MUST be sent in the same buffer sizes they were received. The phone will know it no longer needs to echo data when it has created N echo streams each of which has successfully sent Y bytes of data.
4. Each phone MUST NOT be connected to a wifi access point while this test is run. Otherwise the test will be bogus because when iOS devices are connected to WiFi they will just use local TCP/IP across the access point to move the data. Therefore both WiFi and Bluetooth MUST be turned on but the WiFi MUST NOT be connected to any access point.

So the above means we will send N streams * Y bytes * 2 times (once out and once echoed back) * 2 devices worth of bytes.

I will discuss a possible architecture for this test code below but how you implement the code is up to you. The key thing is to go to create a GitHub repo some place and start it with no content and configure it to support reviewable.io. Then submit a PR with the XCode project to it. The code review I will then perform will have the goal of both letting me review how you attacked the problem but also how you deal with multi-threading, code style issues, etc. It's a good dry run to understand how we want code to be written. I'll also want to run the test locally.

## Optional Architecture

You do not have to implement the code this way. It's just a suggestion and hopefully will clarify goals even if you take a different approach.

Now a fairly simple architecture to implement the previous would be that each phone would have a main thread that would fire off N output workers.

Each output worker would generate a GUID and that GUID would then be entered into a global dictionary indexed by GUID. Each entry would have associated with it a LIFO queue of bytes. The output worker would then open an output stream with that GUID as its name.  The output worker would then start generating Y bytes of data using a random number generator stream outputter and would output those bytes in buffers of size 1 to 4K bytes where the actual buffer size will be randomly picked for each output event (in other words the first buffer might be 10 bytes, the next 1234 bytes, the next 23 bytes, the next 10 bytes, etc.). The various buffer sizes are meant to simulate TCP/IP's random buffer sizes. While the worker is outputting the bytes to the output stream it would simultaneously put those bytes into the LIFO queue in the global dictionary associated with the output worker's GUID. Each worker would exit when it finished transmitting its Y bytes. [Note: You actually don't need a GUID. You could also just pass in a counter created by the main thread to each worker, so long as each worker gets a different counter value then it can use that value as its index and stream name and everything will be fine]

Simultaneously there would be a listener for input streams. Whenever an input stream is received an input worker would be assigned to it. The first thing the input worker would do is see if the stream's name is in the global dictionary of GUIDS mentioned above. 

If it is not then the input worker would immediately open an output stream to the other device with the same name as the input stream. The input worker would then take any buffers of bytes received from the input stream and immediately copy them using the same buffer size to the identically named output stream. The input worker would count how many bytes it has sent and when it reaches Y bytes it will know it is done and can exit.

If the name of the input stream is in the global dictionary of GUIDs then this means that the stream is an echo back to the local device of bytes it has sent to the remote device. In that case the input worker needs to look up the LIFO in the global dictionary for that GUID and start matching the incoming bytes it is receiving against the bytes in the LIFO. If there are any mis-matches (e.g. bytes received on the input stream don't match the bytes in the LIFO) then an exception MUST be thrown and the test MUST fail. If all Y bytes are received and matched then the input worker will exit.

The main thread knows the test is over when the N output workers successfully exit and when 2N input workers (N of which are just echo'ing the other devices bytes and N of which are confirming echos sent over from the other device) successfully exit.

**Comment by yaronyg** [comment]
We should have this finished by tomorrow.

**Comment by yaronyg** [comment]
The current issue is that we aren't getting any data back or at least it hangs for a long time before showing up. Also it turns out that the current test isn't symmetric, the initiator is the only one who starts sending data and the other device just responds. We need the test to be symmetric. So Alex will fix the test and also test with N = 1 to see if data flows when there is just one connection as Toby found of if the problem is something in his code. Alex will also look at Toby's old code to see how he handled things and we'll start a thread with Toby to see if he has any advice.

**Comment by yaronyg** [comment]
It works!!!!!!

**Comment by baydet** [comment]
@yaronyg, I've implemented a test app with architecture you've mentioned above.
You can look on it here:
https://github.com/baydet/MPCF_Mutltistream_Test
to specify who is the master and who is the slave you should pass `-server 0` or `-server 1` to command line. Also in `Constants.h` file you can change parameters (size of transferring data, size max size of single bunch of data)

In the first version of this app I have some issues with multithreading (deadlocking) which causes NSStream freezing. So I assume that we have similar nature bugs with Thali.

**Comment by yaronyg** [comment]
@baydet Unfortunately the current code does not appear to implement the spec as above. If I read the code correctly (you can see my notes in #779) then the biggest problem is that there doesn't appear to be any validation that the data that is reflected back is the data that was sent. This is critical because otherwise we have no idea if useful data is actually flowing. If I'm reading the code correctly then I believe that OutputDataGenerator needs to record the data it outputs. Then didReceiveStream in MultipeerSession, when it receives an incoming stream with retr_ in it, has to compare it against what OutputDataGenerator has outputted. Just remember that the size of buffer we output isn't going to necessarily equal the size of buffer we get back so we need to store the output bytes as a flat byte array and then compare the input bytes against it. If you can use a LIFO queue then you can push bytes in as they are generated and pull them out as they are validated on the return channel. But you will still have to keep track of total byte count so we exit when we have got all the bytes.

Also we MUST validate as bytes are received. We MUST NOT wait until they are all received on reflection before validating. If we do that we are not coming even close to the way data flows in a real app. So every time data comes in on a retr_ stream we need to validate it as we get it.

There should also be some explicit event that fires and displays something when we have validated all the data against all the retr streams.

I also suspect there is a bug in DataStream.m/InputDataStream/readData. It will read up to kStreamReadMaxLength but depending on how the data gets buffered there can easily be more information than that. I suspect that if all the available data isn't read (say in a while loop that goes until there is no more data available) then we aren't going to get any more hasBytesAvailable notifications telling us to read data that has already arrived. So I'm guessing we need that while loop.

Also is dataForStream in DataBuffer in DataGenerators implementing a busy wait in [this line](https://github.com/baydet/MPCF_Mutltistream_Test/blob/3244a99a4b457217e2b93729a80350fefbcf992f/MPCF_Multistream_test/MPCF_Multistream_test/DataGenerators.m#L46)? Sorry if I'm confused. I'm not an expert in Objective-C. But it looks like it's going to sit in that while loop when the buffer is empty until the readingDidEndForStream gets called or data gets added. If it is a busy wait then it needs to be changed to an asynchronous pattern.

**Comment by baydet** [comment]
Yes, you're right - it's busy waiting. In this implementation I'm sure that this code will not produce deadlocks. Also I did not care a lot about resources management. The key point for this project is checking possibility of multistream connection with MPCF. So because of that I haven't put key focus on app's threading architecture.

**Comment by yaronyg** [comment]
1. Please re-implement the project in Swift 2.2
2. Please put in a random (very short, no more than 1 second, usually closer to 200 or 300 ms) delay in outputting day to replicate the kind of bursty behavior we see with TCP
3. Please change the validator that checks that what is reflected is what we sent so it can handle very large streams

Then please re-run the tests with much larger data, say 1 Gig total across all streams

**Comment by baydet** [comment]
@yaronyg, I've implemented swift version of these changes. You may check it here
https://github.com/baydet/MPCF_Multistream_Test/tree/swift. All the code stored in MPCF_Multistream_test-swift folder
Also I've change architecture a bit to make it more clear.

But I have no time today to run it on 1 gig of data.

**Comment by yaronyg** [comment]
@baydet Please run the code on three phones, one as leader and the other two as followers.
