### ISSUE TITLE
Update iOS code with new multi-stream approach

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#769]
Please file a series of bugs defining the PRs that you want to use to incrementally check in the new functionality.

**Comment by baydet** [comment]
@yaronyg here is list of linked issues. Every PR linked to the one of issues below will be merged into branch linked to current issue

- [ ] #819 
- [ ] #820
- [ ] #821
- [ ] #822
- [ ] #823
- [ ] #824
