### ISSUE TITLE
Please pick a test runner framework to use with iOS that will work well with CI

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#770]

**Comment by larryonoff** [comment]
@yaronyg 

If I understand the issue properly I think that we should start by using default Apple tools, i.e. `xcodebuild test`. Most of the testing tools based on `xcodebuild` as far as I know. 

We can consider using different frameworks for native tests, but most of them just wraps Apple testing framework. And again I think that we should use standard framework for now.

PS. I can recommend to consider using [scan](https://github.com/fastlane/fastlane/tree/master/scan) as a tool that simplifies usage of `xcodebuild`. Or at least check how they use `xcodebuild `. The only issue that I see is that `scan` requires dependencies like Ruby and different RubyGems.

**Comment by yaronyg** [comment]
We need to find a stand alone unit test framework that just runs on the phone that can run without using any external code. Please make a recommendation.

**Comment by yaronyg** [comment]
The good news is that we were able to run tests on a device using Apple's test framework but setting this up requires a bunch of fancy work at the file level that can't be done inside of XCode. So we'll need two XCode projects. One for CI that couldn't be used in the XCode IDE because of some weird things we have to do. The other would work in XCode but only on a dev machine with local devices. Which is fine.

Next step is to make sure that we can really build a totally stand alone app that isn't connected to a dev box via USB that can run our tests. We think this will work but we have to test it.

**Comment by larryonoff** [comment]
I documented this fancy stuff, see it below:

1. Copy `XCTest.framework` from `/Applications/Xcode.app/Contents/Developer/Platforms/...` into the project folder. Note that to run tests on device you need `iPhoneOS.platform`, for simulator - `iPhoneSimulator.platform`.
2. Add `XCTest.framework` from the step 1 into `Embedded Binaries` and `Linked Frameworks and Libraries` General Xcode target settings.
3. Check that `RUNPATH_SEARCH_PATHS` has `@executable_path/Frameworks`.
4. Disable bitcode.

One of the steps I did and doesn't work after copying `XCTest.framework. So this step is unnecessary I just would like to document this step too. See it below.

1. Add the following to `FRAMEWORK_SEARCH_PATHS` target that requires XCTest: `$(PLATFORM_DIR)/Developer/Library/Frameworks`. Now you can import XCTest framework into your project. `#import <XCTest/XCTest.h>`.


The process can be much easier, but more time to analyze is needed.

**Comment by yaronyg** [comment]
@larryonoff So just as a reminder. build.sh is what CI runs to set itself up. But the file you care about is setUpTests.sh which is where we actually create and configure the cordova project. So the xCode voodoo you need has to happen as a result of a call in that file since it has to happen after we set up the cordova project but before we build it.
