### ISSUE TITLE
Enhance CI to run iOS tests

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#771]
This will require adding the code to detect when we are on iOS, run the tests and communicate the results to CI

**Comment by yaronyg** [comment]
Working on figuring out how to integrate the tests into Cordova.

**Comment by larryonoff** [comment]
Started work in the branch [vNext_ilya_771](https://github.com/thaliproject/Thali_CordovaPlugin/tree/vNext_ilya_771)

**Comment by yaronyg** [comment]
The next step is to create a cordova plugin with the iOS code inside of the test sub-folder

**Comment by yaronyg** [comment]
We still need to modify the XCode file generated by Cordova because we need an embedded framework and that currently isn't supported by Cordova (there is a PR on it but it hasn't been accepted) and there are work arounds and we have to pick one.

**Comment by yaronyg** [comment]
Everything works now!

**Comment by yaronyg** [comment]
Before we were doing the set up work manually and now we are writing a script to automate and things are getting buggy.

**Comment by yaronyg** [comment]
We need some clean up on the code and then we will submit a PR.

**Comment by larryonoff** [comment]
CI is outdated. Since It has
* El Capitan
* Xcode 7.2

We need the latest Xcode 7.3. So it can be an issue why builds aren't running on devices.

We're working on updating CI.

**Comment by larryonoff** [comment]
CI was updated with Xcode 7.3. The issues still remains.

**Comment by yaronyg** [comment]
We seem to be having an issue with code signing but only in CI, not on any of the local machines. We aren't 100% sure this is true or not but it's our best theory. So we want to try to use Carthage because it handles part of the code signing.

Our problem is that we are using a dynamic library and such libraries can either be signed or not and right now we aren't signed. So either we need to become a static library or we have configured something wrong in dynamic signing.

But for Swift everything pretty much has to be dynamic so even if we fix the xctest framework problem this issue is going to come back.

**Comment by larryonoff** [comment]
link to PR #818

**Comment by larryonoff** [comment]
@yaronyg @jareksl  I have an assumption how we can solve the issue.

Currently as I understand CI uses developer provisioning profile, so we need to try using AdHoc provisioning profile to build test app.

During the investigating this issue I run the command ```codesign --verify``` for two builds: CI build and my local build. As result CI build has CSSMERR_TP_NOT_TRUSTED error.

**Comment by larryonoff** [comment]
@jareksl please check app bundle id in developer.apple.com. It looks that `build.sh` creates `com.test.thalitest` when developer portal has provisioning profile with id `com.test.thalitet` (without __s__ in last word __test__).

**Comment by larryonoff** [comment]
The error `CSSMERR_TP_NOT_TRUSTED` was solved.

**Comment by yaronyg** [comment]
Right now tests say they are passing when they are not. We need to figure out why and fix it.
