### ISSUE TITLE
Unit tests that needs to be written

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#777]
1. We should create a test for run() method in IncomingSocketThread. 
2. We should create something that creates a local socket and sends in data in order to properly test OutgoingSocketThread run() method.
3. We should create more scenarios to test StreamCopyingThread run() method (different data to send). 
4. We should test onStreamCopyError in StreamCopyingThread.
5. We should write tests for onPeerDisovered and onPeerLost methods in ConnectionHelper. 
6. We should expand testRun on StreamCopyingThreadTest to make it send multiple chunks of data to make sure we are properly handling them.

**Comment by yaronyg** [comment]
Work has started on some of the tests.

**Comment by yaronyg** [comment]
The tests are all written but @mlesnic has had some issues with JXcore on Windows which he got a custom build for from Enrico and most of the tests are tested and working but there are tests involving node and he needs to get those passing.

**Comment by yaronyg** [comment]
Submitted a test only PR to see how it runs and it didn't work due to no devices getting connected to the CI. Marcin needs to sync with vNext_yarong_780 and then wait for it to get checked in. Until then he is blocked.

**Comment by yaronyg** [comment]
So Marcin got a mac today and setting it up ate most of his day but he is now running the coordinator tests and figuring out why his single node test isn't running right.

**Comment by yaronyg** [comment]
The node tests are now passing locally but we are running into issues into CI. A phone had wifi turned off and we took it out of rotation because even when wifi was on it didn't work and now we are having a weird build error on the CI machine.

**Comment by yaronyg** [comment]
Couldn't make progress because CI wasn't available as Jarek and Marek were fighting with CI.

**Comment by yaronyg** [comment]
One of the motorola devices is failing in CI but not failing when the exact same phone is run from the desktop. Investigating now.

**Comment by yaronyg** [comment]
All the native tests are passing again with new JXcore and we just need to get the node based native tests running and disable all the other node tests. Once this is passing in CI we can check in.
