### ISSUE TITLE
Two simultaneous MCSessions with the same peers?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#789]
Our understanding is that it's not allowed to have two MCSessions between the same two peers. This causes us a lot of complexity as we need leader election and complicates the living day lights out of opening and managing sessions.

The purpose of this bug is to investigate if maybe we can open two MCSessions simultaneously between the same two peers.

We would change the MPCF demo as follows:
1. Each device would immediately advertise itself
2. Each device when it found the other device would invite the other device to a MCSession.
3. When the inviting device gets confirmation from the invited device that the invitation has been accepted then the inviting device would open the N parallel output streams to the invited device. The invited device would then respond with N _repl streams echoing back the data.

So the idea is that when A invites B to a session then A will send data and B will reflect it back. Simultaneously B will invite A to a session and B will send data and A will reflect it back. So we get the same data transfer as we have with the current demo but split across two sessions.

**Comment by baydet** [comment]
Ha! Kind of good news! I've played around this issue more and and it looks like it's possible to open 2 simultaneous session between 2 devices. The main reason that it was not possible earlier that we tried to open bidirectional `MCSession` for the same `MCPeerID`. But if we create 2 different MCPeerID (one for advertising and another one for browsing) there is no disconnects during connection between 2 devices. 

Now I'll focus on specs you've provided above to be sure it's working properly.

From my perspective it seems to be a good news. Tell me please if there are any caveats I don't see

**Comment by baydet** [comment]
You may look on results here
https://github.com/baydet/MPCF_Multistream_Test/tree/simultaneous-sessions

**Comment by baydet** [comment]
With wi-fi direct it works pretty fine. But unfortunately with bluetooth it has random disconnects.

**Comment by baydet** [comment]
1. in `peer1<->peer2` expressions `peer1` (left) is master and `peer2` (right) is slave
2. A, B, C, ... represents devices. 
3. In expressions `An`, number n - integer that represent `MCPeerID`
4. All test should be tested on bluetooth environment

--
1.	Try to create new session with existed high load session
    - create A1 <-> B1
    -   create N sessions with high load
    -   try to establish:
        -   B2<->A2     
        -   A2<->B2
        -   A1<->C1
        -   A2<->C1
    -   Results
        -   ???
2.  Try to create new session with existed partially load session
    -   create A1 <-> B1
    -   create N sessions with lower channel width
    -   try to establish 
        -   B2<->A2     
        -   A2<->B2
        -   A1<->C1
        -   A2<->C1
    -   Results
        -   ???
	
3. Try to create new sessions after closing existing streams
    -   create A1 <-> B1
    -   create N sessions with partialyl/high load
    -   pausing/closing/waiting existing streams for session A1<->B1
    -   try to establish 
        -   B2<->A2     
        -   A2<->B2
        -   A1<->C1
        -   A2<->C1
    -   Results
        -   ???

**Comment by yaronyg** [comment]
All the indications are that this works. The tests really pounded it and the code seems to validate that it all works. So off we go!
