### ISSUE TITLE
Figure out mechanism to tell us about breaking changes in JxCore

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#8]
We really need some way to get forward notification of breaking changes in JxCore.

**Comment by obastemur** [comment]
One suggestion is that watching jxcore-cordova project repo. After the dev phase is done. Changelogs must be sufficiant.

**Comment by yaronyg** [comment]
Watching it doesn't really work because just today there were 3 commits. Given all the notifications we are all drowned in all day we won't notice significant things. Humans can't just stare at notification feeds all day and notice interesting things (think of that next time you go through airport security). Our brains numb out. So we need a way to call out significant changes. Just a quick email or something saying "hey guys we are about to blow this up" would be enough. That way we can schedule the work.

**Comment by obastemur** [comment]
We will be duplicating the issues here those are relevant.
