### ISSUE TITLE
Answer what Tomi was doing with the reserved value for the change counter

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#810]
I've decided to check in 720 since it is passing tests. But I still need you to get an answer to [this](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/720#-KGQN8oxXPy15BNb38sD) question.

**Comment by vasilevskayaem** [comment]
change counter is used to determine if we should update peer properties. if old change counter!= new change counter or old peer properties==null android bluetooth lib will update peer properties.

org.thaliproject.p2p.btconnectorlib.utils.PeerModel#addOrUpdateDiscoveredPeer . So if it's new peer properties (with any value of change counter) it will be updated. Or if old change counter == 255 and new change counter ==0 .
