### ISSUE TITLE
Update thaliMobileNative.js for the new iOS API

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#812]
According to #789 we've decided to change iOS architecture by replacing lexical peer comparison with multiple sessions. Therefore thaliMobileNative.js needs to be updated

**Comment by yaronyg** [comment]
- [ ] Define multiConnect method
- [ ] Define disconnect method
- [ ] Introduce a new event (or maybe overload peerAvailabilityChanged?) that indicates that the MCSession is lost but doesn't necessarily mean the peer isn't available.
- [ ] Create a queing mechanism in Node for multiConnect/disconnect that ensures we only issue a single one of those two methods for any peerID at any time and that ref counts how many connect and disconnect calls we get to make sure we only disconnect when all the connects are done

**Comment by yaronyg** [comment]
I have at least a solid day of work left

**Comment by yaronyg** [comment]
I got about 1/2 a day of work done today and so I will hopefully get the other 1/2 tomorrow and be done!
