### ISSUE TITLE
Fix casing issue in GIT

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#817]
- [x] Use MV to fix the casing of thalilogger to be thaliLogger
- [x] Fix the calls in require in node for thaliLogger to be properly cased (just to be clean)
- [x] Update the [dev handbook](https://github.com/thaliproject/thali/blob/gh-pages/pages/documentation/DeveloperHandbook.md) to tell people to set core.ignorecase in Git to false

**Comment by evabishchevich** [comment]
Fixed in #825 and in https://github.com/thaliproject/thali/commit/18e779c1fecdf4f988fb7f5a78da441cdcd2cac4
