### ISSUE TITLE
Implement network changed function

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#823]
Part of #769 

`networkChanged`

**Comment by yaronyg** [comment]
Hope implementation will be done by tomorrow and then start on testing.

**Comment by yaronyg** [comment]
The implementation is done but we aren't sure how to test this. We can use a private framework (no jail breaking) to control bluetooth. It's fragile but it's all we've got. We are trying to see if we can find something similar for WiFi.

**Comment by yaronyg** [comment]
Found a way to turn on and off wifi using a private framework! But he needs to check for iOS. The Bluetooth tests though are there.

**Comment by yaronyg** [comment]
This is done but the PR has not been submitted yet.

**Comment by yaronyg** [comment]
The PR didn't get submitted because Dersim was blocked on other issues but he should submit today so I can review.

**Comment by dersim-davaod** [comment]
Creating PR, need to rebase my branch and fix conflicts.

**Comment by dersim-davaod** [comment]
Currently private API that controls Wi-Fi hardware is protected by entitlement.
We have to have jailbroken device to control WiFi programmatically.

So my question is: do we need to test WiFi in networkChanged dynamically?
And if answer is yes, do we use jailbroken devices on CI? Or can we use it?

For now we have an opportunity to control hardware Bluetooth only.
See https://zube.io/projects/3188/cards/173462613 for details.

**Comment by yaronyg** [comment]
We'll just stick with Bluetooth for now. It's a bummer but I don't think it is worth introducing the complexity of jail broken devices and that they can pass certain tests and not others into CI at this time. Alternatively we could come up with some sort of flagging system where by devices can run or not run certain tests based on their state (e.g. the non-jailbroken iOS devices wouldn't even both trying to run tests that require WiFi to be off). But I don't think any of this is worth doing right now. See #949.
