### ISSUE TITLE
Build with custom pouchDB fails on Windows

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#827]
Cordova version: 6.1.0
Node version: 6.3.1
JXcore version: 3.1.2

I was trying to build Thali_CordovaPlugin from branch vNext_yarong_780 on Windows. Unfortunately, there is something wrong. I also tried to manually publish this custom version of pouchDB (as it is said in installCustomPouchDB.js) but with no results.
Sinopia was installed and configured properly (npm set registry http://localhost:4873 and npm adduser --registry http://localhost:4873). 

Logs from sinopia before compilation abort:

```
 http  --> 304, req: 'GET https://registry.npmjs.org/pouchdb-node', bytes: 0/0
 http  <-- 404, user: undefined, req: 'GET /pouchdb-node/5.5.0-prerelease', error: version not found: 5.5.0-prerelease
 http  --> 304, req: 'GET https://registry.npmjs.org/express-pouchdb', bytes: 0/0
 http  <-- 404, user: undefined, req: 'GET /express-pouchdb/1.0.5-thali', error: version not found: 1.0.5-thali
```

Logs from console where `./build.sh`was fired

```
Cloning into 'customPouchDir'...

Cloning into 'customPouchServerDir'...

HEAD is now at 6f40454 Just updating version

events.js:55
        throw arg1; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1025:11)
    at Process.ChildProcess._handle.onexit (child_process.js:808:34)
compilation aborted
```

**Comment by yaronyg** [comment]
The problem is that the commands that work on Mac don't work on Windows. If you are going to stay on Windows then you need to upgrade to Windows 10 and use the bash shell. But do we care?
