### ISSUE TITLE
Please disable the PSK node tests

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#834]

**Comment by evabishchevich** [comment]
- [x] testLocalSeqManager.js 
- [x] testThaliNotification.js 
- [x] testthaliReplicationPeerAction
- [x] testThaliReplicationPeerAction

**Comment by yaronyg** [comment]
@andrew-aladev already finished re-implementing the PEM features to work around the bug so we shouldn't need this work item.
