### ISSUE TITLE
Help the clueless idiot get the app working

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#837]
I'm trying to run the MPCF test app on my iPhones and it builds just fine but it never actually deploys to the device. Normally I would fight through this myself as a useful lesson but I can't right now. I have to get the iOS specs written up. So this bug is to remind me to bug you on Monday to debug with me what I'm screwing up.

**Comment by baydet** [comment]
I've recreated xCode project. You can grab the new version from master now. I assume that somehow AppCode broke it.

**Comment by yaronyg** [comment]
So I switched to master and pulled down the latest changes but it still just builds. It doesn't deploy. :( We'll have to figure this out tomorrow.

**Comment by baydet** [comment]
sometimes xCode drives me crazy :/

**Comment by yaronyg** [comment]
And I got the two tests passing!
