### ISSUE TITLE
Re-enable iOS in CI

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#846]
We have to figure out what we want to test in iOS let's certainly start with your tests for the native iOS test framework but we should pick a few node tests that don't need the native layer and enable those.

**Comment by czyzm** [comment]
To reenable iOS build in CI you need to revert changes from this commit:
https://github.com/thaliproject/Thali_CordovaPlugin/pull/801/commits/ec711b89d6a8bec94a4b3c8492c5f70d3f39c317

**Comment by yaronyg** [comment]
This is a dupe of thaliproject/Thali_CordovaPlugin#771
