### ISSUE TITLE
Threading issue with using XCTest​Expectation in unit tests on device

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#869]
there is some kind of threading issue. For example we have test case like that:
```
class Test: XCTestCase {
    func testAsync() {
        let expectation = expectationWithDescription("wait for async callback")
        var value: Int?
        callAsyncFuncWithCallbackOnMainQueue { newValue in
            value = newValue
            expectation.fulfill()
        }
        waitForExpectationsWithTimeout(10, handler: nil)
        XCTAssertNotNil(value)
    }
}
```

And it runs successfully with xcode's default test runner. But if we try to run code like that with our runner we are having some kind of locking issue because right after timeout violation and failed `XCTAssertNotNil` check we're receiving callback from `asyncFuncWithCallbackOnMainQueue`. It's not a timeout issue because my experiments with real code showed that it's doesn't matter what timeout we have - anyway we're receiving callback right after main test function body've finished execution.

**Comment by larryonoff** [comment]
fixed in PR #818
