### ISSUE TITLE
How do we get access to www/jxcore from node.js?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#87]
We have a set of tests we want to run and the way we want to run the tests is:

```javascript
    fs.readdirSync('.').forEach(function(fileName) {
        if ((fileName.indexOf("test") == 0) &&
            fileName.indexOf(".js", fileName.length - 3) != -1) {
            require('./' + fileName);
        }
    });
```

If we pass in '.' to the readdirSync on Android then we get back the root of the Android device's file system. What do we pass in to get the Assets folder so we can look inside of www/jxcore? Also what do we do on iOS?

**Comment by obastemur** [comment]
options : `__dirname`, `process.cwd()` i.e. for app.js , __dirname  == www/jxcore

**Comment by yaronyg** [comment]
Having you around is officially bad for me. I seem to rely on you as a substitute for thinking. The original test used "." to get access to the local directory and I focused on that. When it didn't work right on Android I tried 'magic' path names "like jxcore, www/jxcore, etc.". What I literally forgot about was process.cwd() and __dirname. I then decided to move on because I had other bugs to fix and I knew you could answer this. Which is the bad part. Rather than stepping back and asking myself "Why isn't this working"? Which could have led to fun things like remember that __dirname and process.cwd() exist. I just relied on you. Of course you made things worse by coming through instantly. Stop being so damn useful!!!!
