### ISSUE TITLE
Please test that vNext is still passing

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#878]
I'm going to be sending out a mail about how to clean up our PR mess. As part of that we need to make sure that vNext is still working after the various changes we have made to hardware and software in the CI system itself. Can you please run the vNext branch again just to make sure it is passing and follow up if you find any problems?

**Comment by jareksl** [comment]
Note: vNext branch contains temporarily switched off node tests and all ios devices are also not tested. The build from vNext was generated successfully. All android tests passed. Please see logs from #879
