### ISSUE TITLE
Сreate multipeer connection between devices and prepare MCSession to open streams

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#880]

**Comment by yaronyg** [comment]
Should be ready tomorrow

**Comment by yaronyg** [comment]
Got blocked on reviewing my PR will hopefully finish tomorrow

**Comment by yaronyg** [comment]
He is trying to choose between a lot of fancy abstractions or simple closures?

**Comment by yaronyg** [comment]
Main flow is done and working on testing.

**Comment by yaronyg** [comment]
Hope to have a PR for 880 tomorrow.

**Comment by yaronyg** [comment]
Just polishing and PR is coming.

**Comment by yaronyg** [comment]
The PR came but we ran into some issues with threading that required some non-trivial code changes. So we are bringing this issue back while those changes are made.
