### ISSUE TITLE
Create TCP listener

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#881]
rewrite and refactor if necessary logic from THEMultipeerSocketRelay of objc implementation of Thali iOS plugin

**Comment by baydet** [comment]
There is a kind of "top-star" list of 3rd party solutions for managing socket connections to analyze:

- https://github.com/IBM-Swift/BlueSocket
- https://github.com/swiftsocket/SwiftSocket
- https://github.com/socketio/socket.io-client-swift
- https://github.com/robbiehanson/CocoaAsyncSocket

I'm going to pick one of these.

**Comment by baydet** [comment]
[BlueSocket](https://github.com/IBM-Swift/BlueSocket) looks very fancy - cross platform well maintained pure swift socket library from IBM. But it is written in 3.0 so we can't use it for now.

[socket.io-client-swift](https://github.com/socketio/socket.io-client-swift) - swiss army knife. We don't need too complex framework.

[SwiftSocket](https://github.com/swiftsocket/SwiftSocket) - a lot of open issues and low activity from maintainers.

[CocoaAsyncSocket](https://github.com/robbiehanson/CocoaAsyncSocket) - seems to be the most appropriate library for our goals

**Comment by yaronyg** [comment]
Reading through the specs. Will start coding today.

**Comment by dersim-davaod** [comment]
I've chosen CocoaAsyncSocket and started implementation.
Also we wanna build simple and flexible basic architecture. So me and @baydet are in the process of discussing how some details will be implemented.

**Comment by yaronyg** [comment]
Dersim and Alex have to agree on their APIs and then Dersim can write the code.

**Comment by yaronyg** [comment]
This and #882 should be done at the end of this week

**Comment by yaronyg** [comment]
Wrote tests today should have PR tomorrow or Monday

**Comment by yaronyg** [comment]
Still writing code.

**Comment by dersim-davaod** [comment]
Fixing linter issues, after that will be ready for PR.

**Comment by yaronyg** [comment]
The code wasn't production ready so we need to clean it up, add tests, etc. But it's just fixes the actual code does exist.

**Comment by yaronyg** [comment]
So we should be re-opening the PR on this very very soon.

**Comment by dersim-davaod** [comment]
PR will be today (rebased on `origin/vNext_aevsyuchenya_769`).

**Comment by dersim-davaod** [comment]
Yesterday we decided to rewrite code to fix #1052 and #1090.
Hoping implementation will be finished today.

**Comment by dersim-davaod** [comment]
Rewriting is finished.
Need to fix tests.

**Comment by yaronyg** [comment]
Probably won't have a PR until EOD Friday or even Monday.

**Comment by yaronyg** [comment]
We think 4 or 5 hours.

**Comment by dersim-davaod** [comment]
Today still blocked on #1151

**Comment by dersim-davaod** [comment]
Continue working (mostly need to check tests and polishing code).

**Comment by yaronyg** [comment]
This was blocked today on thaliproject/Thali_CordovaPlugin#1151. Implementation is done and test are about 80% done.

**Comment by dersim-davaod** [comment]
Tests were written.
Having a little issues with tests that stress TCP and virtual socket. Fixing code.
