### ISSUE TITLE
Open NSStreams and bind them to TCP socket

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#882]

**Comment by dersim-davaod** [comment]
Starting implementation.

**Comment by yaronyg** [comment]
Hoping implementation will be done by tomorrow. And start testing.

**Comment by yaronyg** [comment]
PR should go out today.

**Comment by yaronyg** [comment]
Not yet ready for PR yet. hopefully tomorrow.

**Comment by dersim-davaod** [comment]
PR is out.

**Comment by yaronyg** [comment]
We need to update this code to adopt the new approach to handling thread safety.

**Comment by yaronyg** [comment]
The code and tests are finished but we are waiting to submit a PR until we get Alex's code accepted and then we will rebase this code onto Alex's code.

**Comment by yaronyg** [comment]
This is blocked on thaliproject/Thali_CordovaPlugin#880. Once Alex pushes the new version then Dersim will rebase on it and they will review each other's changes as a result of combining together.

**Comment by dersim-davaod** [comment]
Alex's story is merged.
I'm working on rebasing my changes.

**Comment by dersim-davaod** [comment]
Temporarily blocked on #881.
