### ISSUE TITLE
Unbind connectionListener in testThaliMobileNative

### ISSUE THREAD

**Issue by andrew-aladev** [thaliproject/Thali_CordovaPlugin#887]
[Here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_evabishchevich_848/test/www/jxcore/bv_tests/testThaliMobileNative.js#L1236) we have a problem: `removeAllListeners` deletes all `connection` bindings. `pretendLocalMux` was created in `makeIntoCloseAllServer`.

We are loosing [binding](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_evabishchevich_848/thali/NextGeneration/makeIntoCloseAllServer.js#L29) and `makeIntoCloseAllServer.closeAll` wont work.

I am sure that the idea was to unbind previous `connectionListener` handler. We can fix this be adding `.then(cleanup).catch(cleanup)` after the promise. Right?

**Comment by yaronyg** [comment]
I suspect the cleanest way to handle this is for the makeIntoCloseAllServer function to take over the removeAllListeners function and when it gets a call it will use listeners for the event to see if it is one of the listeners for the event and if it is then it will issue a removeListener event for all the listeners but itself.

The less cool but easier way to handle this is to just get rid of the removeAllListeners call in the test and instead record the round 0 listener and remove it individually with a removeListener call in round 1.

**Comment by andrew-aladev** [comment]
Fixed
