### ISSUE TITLE
testThaliCryptoManager test block on #87

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#89]
We have a test 'failed to extract public key because of corrupt pkc12 file' that can't pass on mobile because it requires a file in the assets folder and we don't know how to get that yet. #87 should tell us how to fix that and then this test will pass.

**Comment by obastemur** [comment]
If this is referring to jxcore's crypto extension, you could also feed the method with buffer instead of location of a file.

**Comment by obastemur** [comment]
P.S. you can not write into asset folder. It's a closed virtual space under APK.

**Comment by yaronyg** [comment]
No, the problem is that I literally forgot about __dirname and process.cwd. Sorry for wasting your time again with something I should have been able to solve on my own.
