### ISSUE TITLE
Implement new native features for iOS

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#895]
This bug is meant to provide highlights from the changes in thaliMobileNative.js. But one of you two needs to own that file and really make sure I captured all the things you need to do. This bug is really more about you two making sure you have all the changes captured and filed as bugs than necessarily using this bug as the work item to drive them all. So if you want to break this out differently please feel free to do so and once you have everything filed as bugs you can close this bug.

- [x] If you get a connect method you need to return the right error - 'Platform does not support multiConnect'
- [x] Implement multiConnect
- [x] Implement multiConnectConnectionFailure
- [x] Implement disconnect
- [x] Note the change in peerAvailabilityChanged, it now separates the UUID and generation into two different fields

**Comment by baydet** [comment]
Implement multiConnect - #824
Implement multiConnectConnectionFailure - #907
Implement disconnect - #908
If you get a connect method you need to return the right error - 'Platform does not support multiConnect' - #909
Note the change in peerAvailabilityChanged, it now separates the UUID and generation into two different fields - #910
