### ISSUE TITLE
Android only changes for thaliMobileNativeWrapper

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#896]
The following are highlights of changes in thaliMobileNativeWrapper that are unique to Android. I suggest you start there first and then fix the related tests so that we can check your changes directly into the mainline code. Of course these changes will involve other bugs (that I'm filing) because when you add getPort that is going to break a bunch of things.

- [x] Implement getPort
- [x] terminateConnection is now a private method, this is going to break tests and such, please update the code. Those tests should now be switched over to disconnect
- [x] Implement the failedNativeConnectionEvent for Android
- [x] Update nonTCPPeerAvailabilityChanged to return peerAvailable and generation as specified in the spec.
- [x] Note that we issue a nonTCPPeerAvailabilityChangedEvent in the code that handles listenerRecreatedAfterFailure but that codes doesn't use the new nonTCPPeerAvailabilityChanged formate specified in the previous work item. We have to put logic here to make sure that we return the same generation as the current one BUT the port MUST be different. We have to be careful of a rare race condition where the new port we get issued could potentially be the same as the old one!

**Comment by yaronyg** [comment]
About 15% done.

**Comment by yaronyg** [comment]
We updated the nonTCPPeerAvailabilityChanged and fix up the tests, especially with recreate after failure.

**Comment by artemjackson** [comment]
`getPort` was renamed to `getHostInfo` and it's already implemented in #929.

**Comment by chapko** [comment]
4th item is completed, right now working on the last one

**Comment by chapko** [comment]
Remaining tasks:
- write tests for `getPort`
- implement reliable port changing after `'nonTCPPeerAvailabilityChanged'` event

**Comment by chapko** [comment]
`getPort` is deprecated (see #1164 for details)

**Comment by chapko** [comment]
> We have to put logic here to make sure that we return the same generation as the current one BUT **the port MUST be different**

@yaronyg as you said, current implementation allows OS to issue the same port after recreating peer listener (we are closing peerListener server and then create a new one on `process.nextTick`). I think the only way to make sure that new port is different is to not free old one until new server is created. It means we must create new peerListener server, start listening on random port and only then close previously used server.

**Comment by yaronyg** [comment]
No, let's not do that we just can't guarantee that we'll get a new port although usually we will. And anyway with the new design it doesn't matter.

**Comment by chapko** [comment]
What matter is when the system issues the same port during listener recreation, `thaliMobile` MUST fire `peerAvailabilityChanged` event with `newAddressPort` set to `true`, even when new peer has the same port and host as the previous one.
