### ISSUE TITLE
Changes for thaliMobileNativeWrapper for iOS

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#897]
These changes should only be done after we have implemented all the Android changes. Also note that these changes shouldn't be done until we have updated the WiFi based Mock to support iOS (yes, I have a bug I'm filing on that).
- [x] Make sure that nonTCPPeerAvailabilityChanged doesn't return a portNumber (it shouldn't get one, you can assert on this) for iOS
- [x] Implement the failedNativeConnectionEvent for iOS (multiConnectConnectionFailure)
- [x] On the start method please check the list of things that now only happen when we are on Android. We need logic to make sure those things don't happen when we are on iOS.
- [x] Stop should only stop the tcpServersManager object if we are on Android. On iOS we just pass the router's address directly since the native layer will talk to the node hosted express server directly, not via a mux.
- [x] startUpdateAdvertisingAndListening should only put the tcpServersManager listener in the way if we are on Android, not iOS.
- [x] Make sure that connect methods for the same peerIdentifier are serialized (so we won't ever have more than one connect method for a specific peerID at a time)
- [x] Turn the multiConnectResolved callback into the multiConnectResolvedEvent
- [x] Note that multiConnect works differently than connect. With connect you fire off the request and the response contains the port. With multiConnect when you fire off the request you just got a confirmation that the request was received. You have to stick a unique ID into the request because there is going to be a separate callback over the multiConnectResolved callback which will contain the actual result and need to be correlated using the ID you put into the multiConnect request.
- [x] Make sure that multiConnect and Disconnect share a single queue for the same peerID (e.g. so that for any given peerID there can only be a single multiConnect or Disconnect method outstanding at a time for that ID0
- [x] Implement multiConnect including the queue logic from the previous item
- [x] Make sure we return the correct error if terminateConnection is called on iOS
- [x] For iOS we need to listen directly for the incomingConnectionToPortNumberFailed native event. For Android this is actually handled by the thaliTCPServersManager code.
- [x] For terminateListener return an error if we get called on iOS

**Comment by yaronyg** [comment]
https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_artemjackson_904/thali/NextGeneration/thaliMobileNativeWrapper.js#L581 - Artyom apparently started on this, check out his code.

**Comment by chapko** [comment]
@yaronyg I have a question regarding

> Make sure that multiConnect and Disconnect share a single queue for the same peerID (e.g. so that for any given peerID there can only be a single multiConnect or Disconnect method outstanding at a time for that ID0

Current of implementation of `multiConnect` and `disconnect` uses global promise queue for all peers. It does not contradict spec, but more optimal way would be separate queue for every peer. 

My suggestion is to keep is simple for now until we have capabilities to measure performance impact. And then we can decide to split global queue onto peer-specific queues. 

What do you think?

**Comment by yaronyg** [comment]
@chapko I'm o.k. with it for now. Please open a specific bug to track this since we should eventually fix it.

**Comment by chapko** [comment]
@yaronyg done

**Comment by yaronyg** [comment]
We think that thaliproject/Thali_CordovaPlugin#1527 is blocking this check in since tests are failing.
