### ISSUE TITLE
Updates to thaliWifiInfrastructure

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#898]
This needs to happen in parallel with the Android only work on thaliMobileNativeWrapper and just before the Android only work on thaliMobile. It will slot right now.

- [x] Make sure the USN generation logic will use the composite UUID + generation format and that we will maintain the same UUID from when startUpdateAdvertisingAndListening it called until stopAdvertisingAndListening is called. When startUpdateAdvertisingAndListening is called for the first time AFTER stopAdvertisingAndListening is called THEN we should generate a new UUID.
- [x] Change wifiPeerAvailabilityChanged to advertise the UUID in peerIdentifier and generation in the generation value.

**Comment by yaronyg** [comment]
Just started to write tests. Should be done tomorrow.

**Comment by chapko** [comment]
Almost ready, one test from `testThaliWifiInfrastructure.js` is still failing. Also updated wifi infrastructure requires some changes in node-ssdp. More details a bit later
