### ISSUE TITLE
Updating Mux

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#901]
These changes apply to all the files in the mux folder. None of these changes should cause ANY changes to anything else (except getting rid of a few unnecessary arguments to function calls from thaliMobileNativeWrapper) and especially not to tests. This is just purely removing unnecessary code. What you need to do is look for the things listed below in those three files and pull them out. They were code (that never worked) for iOS's old design.

# thaliTcpServersManager
- [x] Remove pleaseConnect from createPeerListener
- [x] Remove pendingReverseConnections

# createNativeListener
- [x] Remove _pendingReverseConnections

# createPeerListener
- [x] Remove check for listeningPort === 0
- [x] Remove handleReverseConnection
- [x] Remove _pendingReverseConnections
- [x] Remove findMuxForReverseConnection
- [x] Remove pleaseConnect from createPeerListener
- [x] Remove pleaseConnect from connectToRemotePeer
- [x] Remove support for reverse connections on the outgoing mux
- [x] Rename handleForwardConnection to handleConnection

# testCreatePeerListener
- [x] setUp
 - [x] Rename forwardConnection to remotePort
 - [x] Remove logic where forwardConnection (aka remotePort) is 0
 - [x] Remove pleaseConnect
- [x] startAdvertisingAndListening - Remove pleaseConnect
- [x] Remove reverseConnection tests
- [x] Remove pleaseconnect === true tests
- [x] Remove references to forwardConnection and pleaseConnect
- [x] Remove createListenerOrIncomingConnection's client and server port

# testThaliMobileNative
- [x] Remove a ton of bad test names :)
- [x] shiftData - remove reverseConnection
- [x] Remove clientPort & serverPort

# MockMobile
- [x] Change createListenerOrIncomingConnection to not take clientPort & serverPort

# WifiBasedNativeMock
- [x] Remove clientPort & SeverPort

# everywhere
- [x] Remove pleaseConnect
- [x] Remove please connect
- [x] Remove forward connection
- [x] Remove forwardConnection
- [x] Remove reverseConnection
- [x] Remove reverse connection
- [x] Find all clientPort references and delete
- [x] Find all serverPort references and delete
- [x] Look for all references to listeningPort and see if any are checking if it's 0
- [x] Search *all* of our code for references to things like 'lexically', 'smaller', 'larger' and 'pleaseConnect' for out of date iOS references.

**Comment by artemjackson** [comment]
@yaronyg unfortunately, I don't completely understand what happens in this part of codebase(it would be great to get any explanations), so please check the [changes](https://github.com/thaliproject/Thali_CordovaPlugin/compare/vNext_yarong_812...vNext_artemjackson_901?diff=unified&name=vNext_artemjackson_901) that I made to be sure that I'm on the right way(or not).

**Comment by yaronyg** [comment]
Honestly in the time it would take me to figure out if you did the right thing I could just do the edits myself. Instead my suggestion is that you run the test suites. If all our tests are still passing then you are probably o.k. :)

**Comment by artemjackson** [comment]
@yaronyg 
Tests fail after removing `connection/pleaseConnect/clientPort/serverPort/listeningPort === 0` ().
And actually I can not determine if it's an effect of my [changes](https://github.com/thaliproject/Thali_CordovaPlugin/compare/vNext_yarong_812...vNext_artemjackson_901) because tests on original branch(`vNext_yarong_812`) fail too.

**Comment by yaronyg** [comment]
@artemjackson 812 is now passing all tests on desktop. I just confirmed and pushed to GitHub. So please resync.

**Comment by artemjackson** [comment]
@yaronyg as we have already discussed mux update should start from #740, isn't it?

**Comment by yaronyg** [comment]
Yes. Let's wait until we get the 812 and the rest merged into 740. Of course that is going to take a while since I can't build anything anymore since I "upgraded" JXcore.
