### ISSUE TITLE
Updating wifiBasedNativeMock for Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#902]
These changes should update wifiBasedNativeMock so it will work again with the new Android native infrastructure.

- [x] Update our desktop tests so that they run both unit tests and coordinator tests TWICE, once as Android and once as iOS
- [x] Finally implement the code that honors the platform passed into the constructor for wifiBasedNativeMock so that process.platform is overridden and returns the right value when we are on desktop
- [x] The wifiPeerAvailabilityChanged event we will get from the underlying thaliWifiInfrastructure code is now going to return generation and peerID, we need to be ready for that when we process it.
- [x] Update peerAvailabilityChanged to the new syntax (the previous work item will help)

**Comment by artemjackson** [comment]
@yaronyg 
> Update our desktop tests so that they run both unit tests and coordinator tests TWICE, once as Android and once as iOS

Can we just update test server configuration to include some(e.g 3) Android devices?

**Comment by yaronyg** [comment]
@artemjackson Ahh I see.... I like that. So long as you make sure that we are somehow smart enough to know when we are on desktop which device which node instances are supposed to be emulating. In other words the desktop coordination server has to know how to tell 3 of its node instances that they are pretending to be Android and the other 3 that they are pretending to be iOS.

**Comment by artemjackson** [comment]
> Update our desktop tests so that they run both unit tests and coordinator tests TWICE, once as Android and once as iOS

@yarong As I understand we can use the #1072 implementation to put Android and iOS devices into their own disjoint networks. So it would be enough to run the test server once for all devices.

**Comment by artemjackson** [comment]
> Finally implement the code that honors the platform passed into the constructor for wifiBasedNativeMock so that process.platform is overridden and returns the right value when we are on desktop

@yaronyg I think that it's not a really good approach to override build-in tools like `process.platform` even if JavaScript allows it. So I decided to implement some kind of `platform` wrapper in `testUtils`.

**Comment by yaronyg** [comment]
@artemjackson per our conversation the goal is that if we specify both android and iOS devices when running the coordinator on the desktop then we should start two different groups of node processes, one group simulating iOS and the other simulating Android and run the coordinator tests in parallel on each group. But I need to fix the design for thaliproject/Thali_CordovaPlugin#1072 so that it will work in that case.

In regards to platform, the problem is what do you do with our production code? We will soon have production code in places like thaliMobileNativeWrapper that will behave differently on iOS and Android. That code is checking (and should be checked) process.platform. So if we don't override process.platform what are we supposed to do?

**Comment by artemjackson** [comment]
@yaronyg Well, I got your point. Will fix it.

**Comment by yaronyg** [comment]
Please go for Thali.platform and clean up the existing process.platform code! Thanks!

**Comment by yaronyg** [comment]
This is blocked on https://zube.io/projects/3188/tickets/1363 (interference free testing)

**Comment by artemjackson** [comment]
Bear in mind that there is a branch `vNext_artemjackson_902` for the issue that has unfinished implementation.

**Comment by artemjackson** [comment]
A generation can be retrieved from#1103

**Comment by artemjackson** [comment]
>  Update our desktop tests so that they run both unit tests and coordinator tests TWICE, once as Android and once as iOS

Already implemented by @andrew-aladev in #1072
