### ISSUE TITLE
Update wifiBasedNativeMock for iOS

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#903]
We can do this before the new iOS code is even ready. That way you can not be blocked in make iOS changes for Node.

- [x] Make sure connect throws the right error if called on iOS
- [x] Implement multiConnect
- [x] Implement multiConnectConnectionFailure (if we use TCPServersManager we can use this via its failure event)
- [x] Implement disconnect (and make sure it throws the right error if we are on Android)

**Comment by artemjackson** [comment]
It should be noticed for implementing `multiConnect`
https://github.com/thaliproject/Thali_CordovaPlugin/pull/963

**Comment by artemjackson** [comment]
There is a PR #957 related to this issue

**Comment by artemjackson** [comment]
Bear in mind that there is a branch `vNext_artemjackson_903` for the issue that has unfinished implementation.

**Comment by yaronyg** [comment]
thaliproject/Thali_CordovaPlugin#1275 submitted
