### ISSUE TITLE
Notification/Replication Updates

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#904]
The getAddressPort changes are going to break notification and replication. We also need to now call disconnect.
- [x] They need to use thaliMobile.getAddressPort instead of expecting to get the address and port from the peerAvailablityChanged event

**Comment by yaronyg** [comment]
Artem is blocked on me resonding on reviewable

**Comment by artemjackson** [comment]
Bear in mind that there is a branch `vNext_artemjackson_904` for the issue that has unfinished implementation. Some tests should be fixed according to the new `peerHostInfo` retrieving approach.

**Comment by chapko** [comment]
Fixed in #1512
