### ISSUE TITLE
Choose swift codestyle guide for ThaliCore

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#906]
- [x] Pick one of the available swift code styles guides (ray wenderlich swift guide)
- [ ] update Developer Handbook
- [ ] update swiftlinter according new guides.

**Comment by dersim-davaod** [comment]
Will do on Monday 22th aug.

**Comment by larryonoff** [comment]
I think we should consider using this style guide https://github.com/raywenderlich/swift-style-guide.

**Comment by dersim-davaod** [comment]
I agree. It looks good.

**Comment by baydet** [comment]
Ok, let's stick on raywenderlich's guides

**Comment by dersim-davaod** [comment]
PR will be in an hour.
