### ISSUE TITLE
Please fix 'jx npm run test-meta' in vNext_yarong_417_812

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#934]
We have a timer failure. I don't know why and I ran out of time today to investigate. Since this blocks everything please sync to the latest vNext_yarong_417_812, investigate and repair the issue.

**Comment by artemjackson** [comment]
Closed in favour of #936

**Comment by artemjackson** [comment]
Closed in favour of #936
