### ISSUE TITLE
Add logic which will start advertising after the Bluetooth turns off and on again after a short period of time

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#939]
A part of #872

**Comment by yaronyg** [comment]
This bug is about coming up with a heuristic to figure out when Bluetooth has crashed and figuring out when it has recovered so we can start working again.

**Comment by yaronyg** [comment]
What we are seeing is that the Bluetooth radio spontaneously disables itself during tests for a few hundred milliseconds and then comes right back on. We aren't properly detecting this and so  we turn advertising off when we go out but we don't turn it back on when the radio turns back on and so we disappear from the test.

**Comment by yaronyg** [comment]
We have to see if we can get Android to tell us if the user intended to disable bluetooth. If we can then if Bluetooth fails and the user didn't intend to disable Bluetooth then we should turn Bluetooth back on. If we can't figure out what the user intended then we have to let Bluetooth stay off when it turns off unless we have a known error condition like the one where we get the dead object exception. In those known failure cases then we can force Bluetooth back on but only when we have this additional information that we recognize as a known failure condition.

**Comment by yaronyg** [comment]
We think we have hardened this enough so we are closing.
