### ISSUE TITLE
Before doing the advertising or discovering it`s necessary to check whether the Bluetooth is on

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#940]
A part of #872

**Comment by yaronyg** [comment]
We don't reliably return the 'radios turned off' error when startUpdateAdvertisingAndListening.

**Comment by yaronyg** [comment]
We get a dead object exception. We aren't really sure why. We just need to re-enable bluetooth and try again. That is the logic for this bug.

**Comment by evabishchevich** [comment]
The copy of  thaliproject/Thali_CordovaPlugin_BtLibrary#85
