### ISSUE TITLE
We should run tests only when BT and WiFi are turned on.

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#953]
It turned out that even some of native unit tests fails when bluetooth and wifi are off before running tests. I think we should move executing native tests to promise list, where we are turning on these radios in UnitTest_app.js.

**Comment by yaronyg** [comment]
@mlesnic Are you going to take care of this or is this a request for someone else to handle it?

**Comment by yaronyg** [comment]
@mlesnic Can you please respond to my question above?

**Comment by yaronyg** [comment]
Closed because we have a PR, thaliproject/Thali_CordovaPlugin#958
