### ISSUE TITLE
It looks like the quitSignal isn't being called on test success for round two of simple test

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#961]
https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_evabishchevich_848/test/www/jxcore/bv_tests/disabled/TestThaliMobileNative/simple/test.js
https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_evabishchevich_848/test/www/jxcore/bv_tests/disabled/TestThaliMobileNative/complex/test.js

The issue is that in the simple test in some cases we get into a state where we are trying to reconnect to a peer due to a race condition which isn't even really an error. It would all be fine except that the quitSignal is apparently not raised when the simple test ends successfully and so we keep retrying which then screws up the ability of the next test to connect to the same peer. So the fix is to make sure that the simple and complex tests ALWAYS raise the quitSignal on all code paths (success or failure). And we should also check that 'Test updating advertising and parallel data transfer' is also ALWAYS calling quitSignal on all paths.

So please make sure the following tests ALWAYS call quitSignal on all paths, success and failure:
- [ ] Simple test
- [ ] Complex test
- [ ] 'Test updating advertising and parallel data transfer'

**Comment by yaronyg** [comment]
We are investigating but we haven't managed to find a code path where we wouldn't have called quitSignal. We think it might be that this isn't actually the tests listed in the original bug it might possibly be another badly behaving test that causes tests farther down the test run to then fail because there is a 10 second wait time on the connection retry. @evabishchevich will post full logs when he sees this problem to gist and put the link to this bug so we can more easily investigate.

**Comment by evabishchevich** [comment]
I have the same behaviour on our discovery tests. Please, see the logs
https://gist.github.com/evabishchevich/b37bf6cc34c5d80793c75929957ce6e7
https://gist.github.com/evabishchevich/3583f91ec80164ff698bd52704d7776d
https://gist.github.com/evabishchevich/0319082632f4dfc4aebd7bb3dad08cd7
