### ISSUE TITLE
Investigate what's wrong with coordinated test when running on SpiderMonkey

### ISSUE THREAD

**Issue by artemjackson** [thaliproject/Thali_CordovaPlugin#968]
The #928 should be a start point for most of new branches. Right now the #928 tests fail.
We need to figure out what's wrong with it. BTW js engine that is used by jxcore was changed from V8 to SpiderMonkey.

The first try to solve the issue is #936. The tests from #936 pass with V8 but neither with SpiderMonkey.

There were 5 tries to run tests and there are 5 different logs. In first four cases coordinationServer just hanged. It should be noticed that the last run passed.

* https://gist.github.com/artemjackson/19099173f199f3c043397c261001dbc6
* https://gist.github.com/artemjackson/005cc4f27c310bc5fbbdd567f76a86f0
* https://gist.github.com/artemjackson/638a05e03db7f577b9af8500fe19fcaf
* https://gist.github.com/artemjackson/9f8f930b953d02465d00caf7226a3038
* https://gist.github.com/artemjackson/7129c39af7888ff51fc9ef8dffeef063

There is assumption that the reason of all of that is race condition. But further investigations are needed.

**Comment by artemjackson** [comment]
@yarong @andrew-aladev  What I've just investigated is that all tests pass on SpiderMonkey if running them one by one.

And there are two assumptions:
* [Loading of all test files](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_artemjackson_934/test/www/jxcore/runTests.js#L38) may cause a side-effect 
* Something wrong with thaliTape and how it handles test sequences

Further investigations are needed...

**Comment by yaronyg** [comment]
We compared the v8 and SM logs and we see lots of connection errors in the v8 logs but they don't cause problems with SM they cause crashes. The errors are not necessarily a problem in and of themselves if they are just noise generated while we are shutting down a test but we need to confirm if that is the case or if there is some problem in how we are managing connections.

This branch is different than the branch that has the wifi only capability. We need to RI the wifi only ability to this branch so that we can simplify the environment and make it easier to figure out what is going wrong.

**Comment by artemjackson** [comment]
@yaron 
First of all I can conclude that the issue is not a SpriderMonkey issue, because there are no issues when files with tests are started one-by-one and not at once on SpiderMonkey. The errors of tests logs appear when test files are started all together. It's important that the same logs appear on V8.

I investigated the logs above (enclosed to this issue), so please see the results below.

1. The `Document update conflict` issue ([log file](https://gist.github.com/artemjackson/19099173f199f3c043397c261001dbc6), line 2394)
  ```
  Got an error trying to update seq {"error":"conflict","reason":"Document update   conflict","name":"conflict","status":409,"message":"Document update conflict","ok":true}
  ```
  arise because [PouchDB working directory](https://github.com/thaliproject/Thali_CordovaPlugin/blame/vNext_artemjackson_934/test/www/jxcore/lib/testUtils.js#L250) is the same for all tests and it is never cleaned between the tests.
   @andrew-aladev is aware of this issue.
  My suggestion is to create a unique PouchDB working directory before and for **each** test and clean this directory after **each** test.

2. It seems that the issue #972 arises because of `wifiBasedNativeMock.js` structure, see an [example](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_artemjackson_934/test/www/jxcore/lib/wifiBasedNativeMock.js#L18-L23).
  It stores available peers and created sockets without cleaning them up between the tests. As result peers store in this file contains peers identifiers that are only related to **all** test (e.g. from already finished tests). As I said above there is no issue if tests started one-by-one so there are no collision between available peers and created sockets that are used in tests.
  My suggestion is to create a new instance of `wifiBasebNativeMock` and mock global `Mobile` with it before **each** test and restore it after **each** test. I tried to hack (to solve the issue ASAP) it by wrapping `wifiBasebNativeMock`  with [sockets](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_artemjackson_934/test/www/jxcore/lib/wifiBasedNativeMock.js#L18-L20) and [peers](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_artemjackson_934/test/www/jxcore/lib/wifiBasedNativeMock.js#L23) into javascript closure like that 
  ```
  var WifiBasedNativeMockModule = function (platform, router) {
    ...
    return WifiBasedNativeMock(platform, module);
  };

  module.exports = WifiBasedNativeMockModule;
  ```
  But it didn't help since new issues occurred. The `testThaliMobile.js` test hanged when running all tests together. But it works if exclude `testLocalSeqManger*.js` and `testThaliManager*.js` tests. I discussed this issue with @andrew-aladev and he pointed me that all of `testLocalSeqManger*` and `testThaliManager*.js` tests use `PouchDB` so it refers us to the first item of this list again.

So I'm still working on this issue.

**Comment by larryonoff** [comment]
@artemjackson please make sure that we're fixing the issue for WiFi only mode.

**Comment by yaronyg** [comment]
@artemjackson BTW, just to be clear, the wifiBasedNativeMock issues MUST be fixed. You found a real problem and we have to fix it. Ilya's note is just that right now we really need to unblock Rockwell so our focus is first and foremost on getting WiFi only mode running and WiFi only mode shouldn't be using wifiBasedNativeMock. If it is then that is a bug we have to fix. Once we have WiFi only mode working then we MUST fix the wifiBasedNativeMock issues. But after we get WiFi only mode working.

**Comment by artemjackson** [comment]
@yaronyg This issue seems to be a combination of  #970, #972, #975.
Can we close it?
