### ISSUE TITLE
How are our tests passing with assertion errors?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#970]
We need to make sure they fail when we have assertions. But in Spider Monkey we are getting assertions all over the place but the tests aren't failing out. That can't be right.

**Comment by artemjackson** [comment]
After some investigations that were maden for #972  I can assume that thaliTape works wrong(or a lot of tests were written incorrectly) because there are a lot of errors that are skipped by test runner. Please, see [these](https://github.com/thaliproject/Thali_CordovaPlugin/issues/972#issuecomment-244087864) observations for more information.

**Comment by andrew-aladev** [comment]
Fixed

**Comment by yaronyg** [comment]
No so fixed, we just ran into this. @artemjackson will send details.

**Comment by artemjackson** [comment]
@andrew-aladev 
I've just seen the AssertionError like in the #1165 (see the second log) during local Coordinated tests. But when I tried to catch it like `jx ./runCoordinatedTests.js --filter bv_tests/testThaliManagerCoordinated.js > log.txt` I didn't see it in logs :cry:
I tried 3 more times. No success. It's a terrible...

**Comment by artemjackson** [comment]
@evabishchevich confirmed that the `AssertionError` appears randomly.

**Comment by andrew-aladev** [comment]
The problem is sitting in pouch:

```
function tryCatchInChangeListener(self, change) {
  // isolate try/catches to avoid V8 deoptimizations
  try {
    self.emit('change', change);
  } catch (e) {
    guardedConsole('error', 'Error in .on("change", function):', e);
  }
}
```

So any our exception in pouch event handler will be handled by pouch and our test won't be stopped.

**Comment by andrew-aladev** [comment]
I've reproduced 2 types of errors: timeout and assertion failed, same as on mobile. We need just to increase amount of `instanceCount` to `8-10`. I am fixing this bug.

**Comment by andrew-aladev** [comment]
We are working with this issue.

**Comment by yaronyg** [comment]
Bug thaliproject/Thali_CordovaPlugin#1226, the first [log](https://gist.githubusercontent.com/chapko/1e998c6f6c8d10b37e3c942c5e1f61c8/raw/3a26cc8ff3e67f8c4f7b61d572d4aaf4b9e7ca7a/1%2520run%2520-%2520Nexus_6P%2520%28ENU7N16425000118%29.log) if you search for "{"name":"AssertionError"," you will see that we had an assertion error in the test "Test Write" and and you will see that we emit an assertion, we even emit a [PROCESS_ON_EXIT_FAILED] but the tests don't stop running. They continue. What's going on?

**Comment by andrew-aladev** [comment]
I couldn't reproduce it anymore.
