### ISSUE TITLE
Why are we getting so many connection failures in mock on SM?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#972]
When we run tests in SM on desktop we are seeing a huge number of connection failures which really shouldn't be happening. We also see that the test 48. test repeat write 2 caused hangs in at least two of the 4 failure logs that Artem had captured. But even when we pass 48 we see a lot of failures. We need to compare the log output from SM to the log output from v8 and see if we are seeing the same errors there. But even if we are we shouldn't have this many connection errors, what is going on?

**Comment by artemjackson** [comment]
Same about test 13.

**Comment by artemjackson** [comment]
The output from tests 46, 47 and 48 are full of errors on both SM and V8
```
[33mDEBUG createPeerListener: failedConnection
[39m
[33mDEBUG createPeerListener: Recreating listener
[39m
[33mDEBUG createPeerListener: failed incoming connection because of mux promise failure - Error: Connection could not be established
[39m
[33mDEBUG createPeerListener: createPeerListener creating new server
[39m
[33mDEBUG createPeerListener: listening 58004
[39m
[33mDEBUG createPeerListener: pleaseConnect= false
[39m
[33mDEBUG createPeerListener: first connection
```

**Comment by artemjackson** [comment]
The tests hang on test 195 on SM
```
2016-09-01T13:24:28.538Z - info: Running on ios test: 195. Test TransientState

[36m# 195. Test TransientState
[39m
[32m# 195. Test TransientState
[39m
[33m# 195. Test TransientState
[39m
[33mok 816 should throw
[39m
[32mok 807 should throw
[39m
[32mok 808 should throw
[39m
[33mok 817 should throw
[39m
[32mok 809 should be equal
[39m
[33mok 818 should be equal
[39m
[32mok 810 should be equal
[39m
[32mok 811 should be equal
[39m
[33mok 819 should be equal
[39m
[32mok 812 should be equal
[39m
[33mok 820 should be equal
[39m
[33mok 821 should be equal
[39m
[32mok 813 (unnamed assert)
[39m
[32mok 814 (unnamed assert)
[39m
[33mok 822 (unnamed assert)
[39m
[33mok 823 (unnamed assert)
[39m
[32m# teardown
[39m
[33m# teardown
[39m
[36mundefined[39m
2016-09-01T13:24:32.617Z - info: Socket to device 8abbf58d-0437-4ba7-9579-845b445922f7 disconnected: transport close

2016-09-01T13:26:27.954Z - debug: Too many emit retries to device: 8abbf58d-0437-4ba7-9579-845b445922f7
```
but on V8 all is fine.

**Comment by yaronyg** [comment]
Obviously the hang on Test TransientState is very bad. But the other errors you are seeing aren't necessarily bad. For example, there are race conditions where we are tearing down a test and before we have it completely torn down we might be trying to connect to remote peers who are already tearing down so we will get connection errors. That isn't bad and the test itself shouldn't fail as a result. Remember we are building a system where devices walk into and out of reach all the damn time so we constantly expect broken connections. So just getting a mux promise failure or an ECONNECTIONREFUSED is not enough to say that we have a failure. We have to see where this error occurs. That having been said we at least know that wifi based mock isn't clearing its state properly so that would cause lots of fun problems.

**Comment by yaronyg** [comment]
I believe this is now fixed when we fixed the retry logic.
