### ISSUE TITLE
Please replace lie with ThaliPromise

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#973]
We need to replace our direct usage of 'require('lie')' with a call to something like 'require('../../thaliPromise')' where thaliPromise.js is just a call to require lie. The point of this is that when we are debugging we can replace lie with bluebird with long stacks so we can get better stacks.

This requires 3 find and replaces:
* For the test files just replace with require(thali/NextGeneration/thaliPromise)
* For the files in the root of NextGeneration use require(./thaliPromise)
* For the files in sub folders of NextGeneration use require(../thaliPromise)

**Comment by artemjackson** [comment]
Closed in favour of #980
