### ISSUE TITLE
testUtils doesn't turn on BT and Wifi radios.

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#981]
So I ran some tests today on Android 5 and 6 and it turned out that the promise in UnitTest_app.js doesn't turn on BT and Wifi radios. So I think it should be investigated why it is not working. It could be also that it is not working only on vNext, because this is the branch I started from.

**Comment by yaronyg** [comment]
Any comments @evabishchevich?

**Comment by evabishchevich** [comment]
Marcin said that it looks like devices need some time to turn on/off radios. It can be connected with #989
