### ISSUE TITLE
We are getting random undefineds outputted by SM (not V8) and it's associated with crashes

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#983]
Please work with @andrew-aladev to do the repo (it's the same process as the last Thali bug we sent) and please help us find out why we are getting these undefineds.

**Comment by andrew-aladev** [comment]
We've found a [code](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_artemjackson_934/test/www/jxcore/runCoordinatedTests.js#L83):

```
instance.stdout.on('end', function (data) {
  logInstanceOutput(data, instanceId);
});
```

This code is producing `undefined`. Is it possible for jxcore to provide any `data` in `end` event?

**Comment by andrew-aladev** [comment]
We sure that this `undefined` is not related to crash. Crashed program just closes the stdout and we are getting this `undefined` in the code above.

`instance.stdout.on('end', function (data) {` - this code is a surprise for us. I was personally sure that `end` event wont provide any `data`. I was sure that `data === undefined`.

So we have a question: is it possible for jxcode to provide any `data` here? We are going to select a solution:

1. remove this line of code.
2. add `if (data) {}` to the handler.

Thank you.

**Comment by yaronyg** [comment]
It appears that this issue was on v8 but we didn't see it because tests weren't failing. This has to do with a test failing, the child process is closing that standard out gets into a bad state and so the end event is either the wrong event or the system gets into a bad state. Diego thinks he knows what this is and we should have progress today or tomorrow morning. We don't think this has anything to do with spidermonkey, it has to do with the child process and how it emits the end event.

**Comment by enricogior** [comment]
We agree with Andrew statement that the 'end' event doesn't provide any 'data'.
We haven't found any problem with the jxcore code and the current behavior seems correct.
The following code should 'fix' the problem:

```
var stdout_data = '';

instance.stdout.on('data',
  function(chunk){
    stdout_data += chunk;
  }
);    

instance.stdout.on('end',
  function(){
    logInstanceOutput(stdout_data, instanceId);
  }
);
```

**Comment by larryonoff** [comment]
@andrew-aladev please check @enricogior comment.
